### ISSUE TITLE
Failed to load video: The operation could not be completed

### ISSUE THREAD

**Issue by Abhishek-Shukla1989** [googlevr/gvr-ios-sdk#101]
Hello EveryOne,
## I am using the code as mentioned in the given sample project. I have latest version of sdk i.e 0.9.0

  _videoView.delegate = self;
  _videoView.enableFullscreenButton = YES;
  _videoView.enableCardboardButton = YES;
  _videoView.enableTouchTracking = YES;
  _isPaused = NO;
  // Load the sample 360 video, which is of type stereo-over-under.
##   [_videoView loadFromUrl:[[NSURL alloc] initWithString:@"http://event.aliveonescan.com/store/congo.mp4"]  ofType:kGVRVideoTypeMono];

I am making changes in the same sample app for now. EveryVideo is working fine as local video but not able to play any remote video. You can see that this http://event.aliveonescan.com/store/congo.mp4  URL is working fine on browser.
Your help would be really helpful. Eagerly waiting for your response.

Thanks

**Comment by arumani** [comment]
Same problem with your URL.
But it's ok when I downloaded your mp4 and then uploaded it onto my AWS S3.

I guess the HTTP response(Content-Type) header's difference cause this results.

$ curl -I http://event.aliveonescan.com/store/congo.mp4
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Accept-Ranges: bytes
ETag: W/"10080498-1470381993000"
Last-Modified: Fri, 05 Aug 2016 07:26:33 GMT
Content-Type: video/mp4
Content-Length: 10080498
Date: Tue, 09 Aug 2016 02:23:36 GMT

$ curl -I https://s3.amazonaws.com/my_path/congo.mp4
HTTP/1.1 200 OK
x-amz-id-2: rkT2MAGcgqFxAphYpacUcC4J/KJxWCsRWwiZsY87S7DU+O06UD9zPmifnTUy1XFf9z7wcEbzEzA=
x-amz-request-id: BCD1F8F890D243DA
Date: Tue, 09 Aug 2016 02:21:55 GMT
Last-Modified: Tue, 09 Aug 2016 02:18:00 GMT
ETag: "393bcf57f16f929eb528c76300ff74d8"
Accept-Ranges: bytes
Content-Type: application/octet-stream
Content-Length: 10080498
Server: AmazonS3

**Comment by Abhishek-Shukla1989** [comment]
Hi ,

Can you tell me what changes we need to implement for making this video work on our server as well?
Waiting for your response.

**Comment by arumani** [comment]
First of all, it's my guess that Content-Type cause your result.
And even if it is correct, I don't understand your server environment and configuration. So I can't guarantee my comment below.

If you use Tomcat ( from "Server: Apache-Coyote/1.1") or any general web server, you can set MIME mappings as far as I know.

"mp4" -> "video/mp4"
to 
"mp4" -> "application/octet-stream"

**Comment by Abhishek-Shukla1989** [comment]
Can anyone please give me a working video URL for testing for some time? because i am facing issue that our video url is not working.
That will be very helpful.

Thanks

**Comment by yuanyouli** [comment]
I change the Content-Type to application/octet-stream ,but same problem .

**Comment by dancingalone** [comment]
I meet the same issue. How to fix it? Can anyone give me some guide,thanks

**Comment by MohammadrezaZamanieh** [comment]
@dancingalone you set that to YES?

**Comment by tibewww** [comment]
Did anybody manage to make run a stereo video on swift ??

I've mtrying the following:

`//        videoVRView.load(from: URL(string: "myvideo.mp4"), ofType: kGVRVideoTypeStereoOverUnder)
`

but I'm getting the error "Use of unresolve identitifer kGVRVideoTypeStereoOverUnder" what can we do ???

Thanks a lot guys :):)

**Comment by marcoslacerda** [comment]
Any Solution for this problem? I have a same issue
