### ISSUE TITLE
Very slow video rendering performance.

### ISSUE THREAD

**Issue by ssurgen** [googlevr/gvr-ios-sdk#103]
Initially the video plays in an expected framerate, all fine so far..

-> After going in fullscreen-mode and then switching several times between fullscreen-mode and cardboard-mode, the framerate of the video downgrades dramatically ( like 3 frames every 5 seconds ).

Tested on multiple devices (iPhone 5s and iPhone 6) width different video-sources ( both in mono mode, 1080p and 720p ) 
Video-Files are stored locally on the device itself. No memory issues, no CPU issues.

Would be great if you guys could provide some support there.

Best, S.

----

Update: It turned out that disabling "enableFullscreenButton" on the videoView did the trick.

**Comment by Abhishek-Shukla1989** [comment]
Can anyone please give me a working video URL for testing for some time? because i am facing issue that our video url is not working.
That will be very helpful.

**Comment by nathanmartz** [comment]
S, what version of the SDK are you using?

Abhishek, please stop hijacking other people's threads and create a thread
with your own issues.

**Comment by ssurgen** [comment]
on the latest version 0.9.

**Comment by ssurgen** [comment]
Could you guys reproduce this issue on ios? It's still existing when the user often switches between cardboard-fullscreen-view ( _videoView.displayMode = 3; ) and back to normal view. And again and again.

Would be nice if someone could help me out there.

Best, S.

**Comment by nathanmartz** [comment]
We haven't been able to repro this yet, but we are trying.
