### ISSUE TITLE
Remove (i) icon  form GVRVideoView

### ISSUE THREAD

**Issue by Abhishek-Shukla1989** [googlevr/gvr-ios-sdk#104]
Hello All,

Please let me know how I can remove Tip icon (i icon) from GVRVideoView. Is there any way or property to disable it in order to go in production? What is your plan regarding UI customisation of GVRVideoView ?

Thanks

**Comment by nathanmartz** [comment]
This question has been asked and answered several times here already. Just do a quick search.

**Comment by Abhishek-Shukla1989** [comment]
Can we change destination link of tip icon only? I didn't find any answer related to this query.

Thanks

**Comment by dinhnhat0401** [comment]
@Abhishek-Shukla1989 
https://github.com/googlevr/gvr-ios-sdk/issues/9

**Comment by tejpratap0** [comment]
GVRVideoView  *videoView = [[GVRVideoView alloc] initWithFrame:CGRectMake(0, 0, [[UIScreen mainScreen] bounds].size.width, [[UIScreen mainScreen] bounds].size.height)];

for (UIView *view in videoView.subviews) {
        if ([view isKindOfClass:[UIButton class]] ) {
           if ([NSStringFromClass([view class])  isEqualToString:@"QTMButton"] ) {
               [view removeFromSuperview];
           }
        }
    }
