### ISSUE TITLE
GVR SDK Orientation issue.

### ISSUE THREAD

**Issue by Abhishek-Shukla1989** [googlevr/gvr-ios-sdk#105]
Hi,

Google VR sdk breaks the orientation rules in my app. My entire app is in portrait mode. After opening  
full view of GVRSDK , app starts rotating in all modes. Is there any way to stop this rotation in my entire application?

**Comment by sanjayc77** [comment]
If by "full view" of GVRSDK you mean non-VR (non-stereoscopic) view, then supporting all orientation is by design. I am also assuming you are talking about VR View, "full view" in this context is kGVRWidgetDisplayModeFullscreen for the displayMode property of GVRWidgetView.
