### ISSUE TITLE
why iOS SDK can't set cardboard viewer parameters like android SDK and unity SDK

### ISSUE THREAD

**Issue by AmonDeng** [googlevr/gvr-ios-sdk#106]
I want to set cardboard viewer by code   like Android  can set  by  this func(static GvrViewerParams  
createFromUri(Uri uri))
I want to know whether a similar approach iOS

**Comment by nathanmartz** [comment]
Thanks for this report. I agree that we should support this and have added it to our internal task tracker.

**Comment by sanjayc77** [comment]
Is this something you need for the GVRWidgetView API or GVRCardboardView API? For example:

`
@interface GVRWidgetView : UIView
...
+ (void)setViewerParamsFromUrl:(NSURL *)url
                withCompletion:(void (^)(BOOL success, NSError *))completion;
...
@end
`

**Comment by AmonDeng** [comment]
Yes,you get my point

**Comment by sanjayc77** [comment]
This is available in 1.10.0: https://developers.google.com/vr/ios/reference/interface_g_v_r_widget_view and https://developers.google.com/vr/ios/reference/interface_g_v_r_cardboard_view
