### ISSUE TITLE
iPhone 5 video cannot play

### ISSUE THREAD

**Issue by yalong5837** [googlevr/gvr-ios-sdk#107]
Device 
 
iPhone 5 , iOS 9.1

other device (iPhone 6 , iPhone 6s..) is ok

**Comment by nathanmartz** [comment]
Can you share a link to the problematic video? Most likely it is too high res for the older iPhone 5 to decode.

**Comment by yalong5837** [comment]
problematic video link: http://promotion.elong.com/wireless/H5/html/VR/kaiyue/videos/kaiyue_pc.mp4

Error Domain=AVFoundationErrorDomain Code=-11855 "Cannot Decode" UserInfo={NSLocalizedDescription=Cannot Decode, NSUnderlyingError=0x1559ed00 {Error Domain=NSOSStatusErrorDomain Code=-12910 "(null)"}, NSLocalizedFailureReason=The media data could not be decoded on this device.}

**Comment by nathanmartz** [comment]
I don't see anything immediately obviously wrong with your file. I am
surprised it does not play. If you download that file and play it outside
of VrView, does it play on the iPhone 5?

**Comment by sanjayc77** [comment]
We depend upon iOS to perform the decoding. The supported codecs depend upon the device.

https://developer.apple.com/library/ios/technotes/tn2224/_index.html

http://stackoverflow.com/questions/1535836/video-file-formats-supported-in-iphone
