### ISSUE TITLE
Problem in displaying panoramic photo

### ISSUE THREAD

**Issue by humingw** [googlevr/gvr-ios-sdk#109]
When displaying panoramic photo taken using iPhone Apple photo app with GVRPanoramaView, there is a big black dot at the bottom (e.g. when the phone is on the table, the black dot is at the center of view). It seems that the GVRPanoramaView is designed for viewing 360 degree spherical photo only. It'd be nice to be able to display panoramic photo (taken with popular smartphone) like facebook app does (https://facebook360.fb.com/360-photos/) where missing area is not shown as black (this also means that the phone tilt is limited to the photo area). The same issue exists for cardboard view (a black dot area is visible when the phone is tilted).  Any plan to address this issue?

**Comment by nathanmartz** [comment]
Hi. Thanks for this feedback, but the current behavior is by design. We are focused on making it easier to view immersive 360 media, not on making a generic pano image viewer.
