### ISSUE TITLE
getHeadView in iOS

### ISSUE THREAD

**Issue by shehzadq** [googlevr/gvr-ios-sdk#110]
I am integrating gvr-ios-sdk to my crossplatform application where we already integrated gvr-android-sdk in our application. 

In Android we using GetHeadView to get head transform

> public void getHeadView (float[] headView, int offset)
> 
> A matrix representing the transform from the camera to the head.
> 
> Head origin is defined as the center point between the two eyes.

Looking into iOS sdk for similar like method. 

Can you please suggest which method will give us same values like android.

**Comment by sanjayc77** [comment]
The GVRCardboardViewDelegate has methods that provide GVRHeadTransform. See https://developers.google.com/vr/ios/reference/protocol_g_v_r_cardboard_view_delegate-p
