### ISSUE TITLE
Video pausing, control and observation of progress

### ISSUE THREAD

**Issue by CraigMason** [googlevr/gvr-ios-sdk#113]
Sometimes videos we play buffer, even on slow connections. In some cases, they just pause completely, so we have to trigger `resume` in a timer loop (hacky).

It would be great to expose, either via delegate or KVO, the current playback interval and also notify when the buffering state of a video changes.

Some of our videos would also benefit from a progress bar to scrub through the video, but this isn't easy to implement without knowing the current playback state and time.

**Comment by joeyjoejoejr** [comment]
Current time is available: https://developers.google.com/vr/ios/reference/protocol_g_v_r_video_view_delegate-p#accacefe26471a57fd645c04df0fbb3d3

Current state is a different story, that I'm currently stuck on.

**Comment by sanjayc77** [comment]
We fire didLoadContent the moment AVPlayerItem's status changes to AVPlayerItemStatusReadyToPlay. So from the moment the loadVideo method is called to the moment didLoadContent is called, video is buffering. 

Does that help? If not what is missing?

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRVideoView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. Take a look at the updated VideoWidgetDemo sample app.
