### ISSUE TITLE
Read Cardboard Profile QR Code and update Distortion 

### ISSUE THREAD

**Issue by shehzadq** [googlevr/gvr-ios-sdk#114]
Hi,

Would be pleased if you can let me know how can I read QR code profile and update my custom distortion.

I want to read QR code. When I read QR code using cardboard official app it is not reflected in my app. But similarly it is working fine in Android side of my application.

**Comment by nathanmartz** [comment]
Hi, I'm sorry but we can't share the details of that system.

**Comment by shehzadq** [comment]
Hi, I am not asking about details . I am asking how can I use google VR iOS SDK to read QR profiles in my application . I using google VR SDK for head tracking etc. 

I am looking for to integrate new cardboard profiles in my application using Google VR iOS SDK. 

I checked sample applications but no integration help for profile reading provided neither API references has any information.

Please suggest!

**Comment by nathanmartz** [comment]
Oh, I see. The GVR library is not designed to be a generic QR code scanner
library. There are a number of options available, and we don't endorse any
one in particular.

**Comment by shehzadq** [comment]
Hi, 

Thanks for your response.

Can you please guide how can I use GVR library to switch user cardboard profiles in our application. 

Like the samples bundled with repo like TreasureHunt has gear button (settings) at middle of screen from where I can switch profiles. When I tap gear button it opens up Camera and scans and then update that profile.

I am looking to trigger this gear button functionality from my Custom button and from my application. Is this possible ?

As in Google VR Android SDK we can use HeadMountedDisplay and can access these params.
https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/GvrViewerParams
In Android Google Cardboard Application when we change cardboard profile and then when we launch our application it is able to return updated profile and return params.

 
So We are looking for similar stuff in our iOS Application. Hopefully now use case is clear.

**Comment by nathanmartz** [comment]
I'm sorry but right now it's not possible to trigger scanning flow programatically. You can set the default viewer, but that's only the default and has no effect if the user has paired a viewer.

**Comment by Azlun** [comment]
Is there any update for CardboardDevice.proto at https://github.com/google/wwgc/issues/3 I think Daydream View Profile have more data tails for Controllers and keyboard configuration
