### ISSUE TITLE
Black Screen with GVRVideoView(sdk0.9.0)

### ISSUE THREAD

**Issue by easyui** [googlevr/gvr-ios-sdk#117]
step:
1 new GVRVideoView
2 to cardboard mode
3 release ：
        self.videoView?.delegate = nil
        self.videoView?.loadFromUrl(nil)
        self.videoView = nil
4 new  GVRVideoView again
5  to cardboard mode
6 Black Screen（this is bug）
sdk0.8.5 is right ，sdk0.9.0 not work

**Comment by uranpro** [comment]
Same: https://github.com/googlevr/gvr-ios-sdk/issues/115

**Comment by sanjayc77** [comment]
Can you test with GVRSDK 1.0.1? Thanks.

**Comment by mstana** [comment]
hey, with 1.0.1 my videoView is black, after some time green on 0.8.* video was showed but freezes after second or two. 

Thanks

**Comment by sanjayc77** [comment]
We have identified an issue, introduced in 1.0.1, where pausing the video also pauses the head tracking (motion tracking). This fix will be in the next release.

Can you verify that this issue does not happen as long as the video is playing?

Thanks

**Comment by mstana** [comment]
@sanjayc77  sorry but I can still reproduce the issue. For Image the GVR is working correctly, video still the same -> Green Video after couple seconds. 

I have double checked my video and the way how I am calling views, URL etc. - I found nothing wrong.

Just one more thing - I am loading video from internet as external URL (not local file). 

Thanks for your time
Marek

**Comment by desmondmcnamee** [comment]
This is working for me now that i've updated to 1.20.0. Thanks guys.
