### ISSUE TITLE
GreenScreen when GCSVideoView loads HLS streaming

### ISSUE THREAD

**Issue by phasedarray** [googlevr/gvr-ios-sdk#118]
I want to load HLS streaming(***.m3u8) with GCSVideoView, but it always shows a green screen. 
However, the audio works fine. 

BTW, AVPlayer works fine with this HLS

iphone6, ios 9.3.5

**Comment by nathanmartz** [comment]
Can you share the URL of the problematic link?

**Comment by sanjayc77** [comment]
Please try the latest GVRSDK 1.0.1.

https://github.com/CocoaPods/Specs/blob/master/Specs/GVRSDK/1.0.1/GVRSDK.podspec.json

**Comment by mstana** [comment]
Hi, this is isssue also in 1.0.1 I have just tested it, with 0.8.5 the video was at least loaded on first frame and started playing, after couple seconds video stop playing.

**Comment by sanjayc77** [comment]
I am bit confused, you mention loading a video but the log shows a "panorama image". Does your log for the video have that string or are you using the PanoramaApp from the sample?

**Comment by sanjayc77** [comment]
We do have an issue where "didLoadContent" gets called multiple times. This will be fixed in the next release.

**Comment by mstana** [comment]
sorry my fault - but problem is still here - for video and image too

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRVideoView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. Take a look at the updated VideoWidgetDemo sample app. The new API requires you to provide your own instance of AVPlayer. Thus you can program the support for HLS directly in AVPlayer.
