### ISSUE TITLE
SceneKit with SpriteKit Material Support

### ISSUE THREAD

**Issue by allanweir** [googlevr/gvr-ios-sdk#119]
Hi, I've been experimenting with a project bringing together the GVR SDK and SceneKit (with help from [GVR-SceneKit](https://github.com/AndrianBdn/GVR-SceneKit) ). One of the major limitations however is being able to use SpriteKit scenes as materials on SceneKit objects.

My particular use is making a custom 3D Scene with a SpriteKit video node mapped to a SceneKit sphere (emulating the GVRVideoView which doesn't offer a flexible UI).

This seems to be an issue on devices and OS's which use Metal over OpenGL. Is it possible to provide a GVRView which inherits from SCNView and allows us to force 'renderingAPI' to be .OpenGLES2 as well as make it simpler to combine SceneKit with GVR.

Thanks,
Allan

**Comment by nathanmartz** [comment]
Hi, Allan. Thanks for the suggestion but integrating the GVR SDK with SceneKit is not a priority for us right now and I don't see that changing for the forseeable future.
