### ISSUE TITLE
Changing the Head Position

### ISSUE THREAD

**Issue by tomday** [googlevr/gvr-ios-sdk#12]
I am trying to create a VR application that uses Indoor Location based on your TreasureHunt Demo.

I have the VR and Indoor Location working separately within the one project and can access the position (X and Y) within the `TreasureHuntRenderer.m` file. 

I am aware that in Normal OpenGL, the View Matrix would be the one to be changed. Would that be the case for the view matrix `eyeFromHeadMatrix` in this project? 

Thanks,
Tom

**Comment by dav-cz** [comment]
You need to modify the `head_from_start_matrix` matrix.
