### ISSUE TITLE
Support both landscape orientations in FullscreenVR

### ISSUE THREAD

**Issue by allanweir** [googlevr/gvr-ios-sdk#120]
Hey,
Thanks for making switching to cardboard mode so easy. I have an issue when I press the cardboard button and get the rotate phone tip, it only goes away if I rotate to landscape with home button on the right, it won't hide if I move to landscape left.

I think this worked fine in 0.8.5, so may be a 0.9 issue.

Thanks,
Allan

**Comment by nathanmartz** [comment]
That is by design. Currently the phone must be in landscape right.

**Comment by allanweir** [comment]
Why is that? I don't think the rotate animation makes it clear only one rotation direction is supported, so it looks like it isn't working if you rotate the other direction. Is it not unnecessarily restrictive?

**Comment by nathanmartz** [comment]
The restriction originally comes out of the magnet trigger. We removed support for that in the last release, and will hopefully remove this restriction in one of our next few releases.
