### ISSUE TITLE
GVRVideoView memory leak on iOS10

### ISSUE THREAD

**Issue by acme147** [googlevr/gvr-ios-sdk#122]
I have memory leak issue while using GVRVideoView on iOS10.
It simply reproduces by running VideoWidgetDemo on iOS10 device.
Used memory grows every second when rendering starts. At the same time everything is ok on iOS9.3.5.

<img width="451" alt="2016-09-15 5 17 39 pm" src="https://cloud.githubusercontent.com/assets/2932670/18553375/e47e0c06-7b68-11e6-88f7-2bb490ecf219.png">

**Comment by sanjayc77** [comment]
Was this on the simulator or real device? I see this on my iOS 10 device:

<img width="731" alt="screen shot 2016-09-16 at 1 41 27 pm" src="https://cloud.githubusercontent.com/assets/434592/18600671/cba80bae-7c13-11e6-84ab-b5874d72fcdd.png">

**Comment by acme147** [comment]
This is from real device. This issue reproduces on my iPhone 6s (iOS 10.0.1) with VideoWidgetDemo project from this repo and GVRSDK v0.9.0.

**Comment by acme147** [comment]
Still have this issue with latest VideoWidgetDemo example, GVRSDK v1.0.0 and my iPhone 6s and iPhone 6s Plus (iOS 10.0.1 both).

**Comment by acme147** [comment]
I tried to reproduce this with Xcode 8.1 beta and iOS 10.1 beta and problem has gone. Is there any temporary workarounds for iOS 10.0?

**Comment by sanjayc77** [comment]
Can you try the latest GVRSDK 1.0.1? This should be fixed now.

https://github.com/CocoaPods/Specs/blob/master/Specs/GVRSDK/1.0.1/GVRSDK.podspec.json
