### ISSUE TITLE
GVRVideoView memory leak

### ISSUE THREAD

**Issue by acme147** [googlevr/gvr-ios-sdk#123]
I found that AVPlayer probably not releases added periodic time observers that causes memory leak both iOS9 and iOS10 devices.

<img width="602" alt="2016-09-15 5 40 35 pm" src="https://cloud.githubusercontent.com/assets/2932670/18554030/8c8252c0-7b6b-11e6-9be6-c62ab79a9d51.png">

I found this by creating a AVPlayer category that replaces `addPeriodicTimeObserverForInterval:queue:usingBlock:` with empty implementation and memory leak disappears.

```
@implementation AVPlayer (TimeObserver)

+ (void)load
{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        Class class = [self class];
        
        SEL originalAddObserverSelector = @selector(addPeriodicTimeObserverForInterval:queue:usingBlock:);
        SEL swizzledAddObserverSelector = @selector(swizzled_addPeriodicTimeObserverForInterval:queue:usingBlock:);
        Method originalAddObserverMethod = class_getInstanceMethod(class, originalAddObserverSelector);
        Method swizzledAddObserverMethod = class_getInstanceMethod(class, swizzledAddObserverSelector);
        method_exchangeImplementations(originalAddObserverMethod, swizzledAddObserverMethod);
    });
}

- (id)swizzled_addPeriodicTimeObserverForInterval:(CMTime)interval queue:(nullable dispatch_queue_t)queue usingBlock:(void (^)(CMTime time))block
{
    return nil;
}

@end
```

So removing added periodic time observers before dealloc AVPlayer may help.

**Comment by sanjayc77** [comment]
This was fixed in the GVRSDK 1.0 release. Please verify and re-open if not.
