### ISSUE TITLE
iOS GVRAudioEngine::preloadSoundFile  always fails w/ 'File Does Not Exist'

### ISSUE THREAD

**Issue by CacheLine** [googlevr/gvr-ios-sdk#126]
I'm trying to use the GVRAudioEngine in an iOS app, but the engine fails loading both .wav and .mp3 audio files out of the app bundle and the app documents directories. The iOS File Manager says the files exist at the path, the audio engine disagrees. Attempting to play the files without preloading fails silently, as it were.
I put this code into the VideoWidget  sample just before the video is loaded to verify that it wasn't something in my app, and get the same results:

`   

```
GVRAudioEngine *_audioEngine = [[GVRAudioEngine alloc] initWithRenderingMode: kRenderingModeBinauralLowQuality];

NSString *file = [[NSBundle mainBundle] pathForResource:@"JCD" ofType:@"mp3"];

NSFileManager *fman = [NSFileManager defaultManager];

NSLog(@"File Exists: %@ \n%@",[fman fileExistsAtPath:file] ? @"YES" : @"NO", file);
if ([_audioEngine preloadSoundFile:file])
{
        int ssid = [_audioEngine createSoundObject:file];
        [_audioEngine playSound:ssid loopingEnabled:NO];
}
```

`
The log output shows the file exists, the audio engine log output shows the same path but claims it doesn't exist.

Help?

**Comment by anokta** [comment]
This seems to be a bug on our side, should be fixed in the next update. In the meantime, you can still use preloading as a temporary workaround. Thanks for reporting the issue!

**Comment by CacheLine** [comment]
Wow, thanks for the quick response. The preloading also fails for me, so I haven't been able to get any sounds out of the audio engine. Looking forward to the next update. Thanks again!

**Comment by sanjayc77** [comment]
Is this still happening with GVRSDK 1.0.1?

**Comment by CacheLine** [comment]
I'm afraid it is still happening with 1.01. I have tried giving the full path to .wav and .mp3 files in the app's Documents directory and in the app bundle and get the following:

VideoWidgetDemo[1554:1185516] File Exists: YES 
/var/containers/Bundle/Application/F9C13C8F-D036-4100-8B19-6628CA0ACC2E/VideoWidgetDemo.app/JCD.mp3
2016-10-14 10:01:21.063409 VideoWidgetDemo[1554:1185516] File does not exist: /var/containers/Bundle/Application/F9C13C8F-D036-4100-8B19-6628CA0ACC2E/VideoWidgetDemo.app/JCD.mp3

If I try supplying the filename without any path, for a file that is in the app resources (i.e. located in the bundle), then preload returns true, without an error, but a subsequent call to createSoundObject: returns -1, which doesn't work with  playSound:loopingEnabled:

Thanks for your help.

**Comment by anokta** [comment]
Unfortunately, the corresponding fix did not get in, since gvr-ios-sdk was not part of the v1.0.1 update. It will be available in the next release.

**Comment by CacheLine** [comment]
Any idea when 1.02 or a version including this fix will be available?
