### ISSUE TITLE
VR mode pause inconsistency

### ISSUE THREAD

**Issue by seankovacs** [googlevr/gvr-ios-sdk#129]
When going into VR mode for the first time the video will pause until the directions are cleared. This is good.
Going out of VR mode and back in to VR mode doesn't pause the video yet still shows the directions. It should either always pause while showing directions OR not show the directions on the 2nd go-round.

**Comment by nathanmartz** [comment]
Looks like a legit bug. Thanks for the report!

**Comment by sanjayc77** [comment]
In my testing, the video is paused while the transition view is shown (every time I enter VR mode). But if you enter VR mode, while the phone is in landscape orientation, the transition view is shown briefly and the video is not paused.

So, the video is paused if the device orientation is portrait and transition view is visible.
