### ISSUE TITLE
This application is modifying the autolayout engine from a background thread

### ISSUE THREAD

**Issue by yogevbar** [googlevr/gvr-ios-sdk#130]
When loading the panorama image to the view i'm getting this error "This application is modifying the autolayout engine from a background thread..."

I'm using storyboard to place the view with class GVRPanoramaView.
I'm calling to the loadImage function from the viewDidLoad.

`UIImage *panoramaImage = [UIImage imageNamed:@"360Panorama"];
[self.panoramaViewContainer loadImage:panoramaImage ofType:kGVRPanoramaImageTypeMono];`

I tried to call it from 
`dispatch_async(dispatch_get_main_queue(), ^{
});`
Didn't help.

**Comment by justsomeguy-google-com** [comment]
I've looked at how the code works and our example and I think I see why what you are doing isn't working.  We are going to do the load on the renderer thread, which is absolutely required.  It appears that can resize the view.

In our example we put it in a UIScrollView.  That seems to prevent the autolayout from getting hit.  Can you try that?

**Comment by yogevbar** [comment]
I have tried this, and it still didn't work.
I saw the example, it doesn't use autolayout.

**Comment by justsomeguy-google-com** [comment]
You shouldn't have autolayout inside the scrollview.

I have the bug assigned to me, but if there is a workaround I'd rather you
didn't have to wait for a release cycle.

**Comment by yogevbar** [comment]
Great, thank you.

**Comment by iraritchiemeek** [comment]
Hey I have this issue too.
Was working fine until yesterday, now GVRPanoramaView and GVRVideoView don't work in cardboard view.

Any work arounds? I tried using a UiScroll but didn't change anything.
Thanks

**Comment by krambs** [comment]
Bumping to see if any workarounds found... Thanks!

**Comment by jkallunki** [comment]
I got this error fixed for now by putting my panorama view inside an UIScrollView and then locking the dimensions of the panorama view like this in my view controller:

```
    override func viewDidLayoutSubviews() {
        panoramaView.translatesAutoresizingMaskIntoConstraints = true
        let w = panoramaView.superview!.frame.width
        let h = panoramaView.superview!.frame.height
        panoramaView.frame = CGRect(x: 0, y: 0, width: w, height: h)
    }
```

**Comment by sanjayc77** [comment]
Closing this old thread since there is a workaround. We have deprecated VRView widgets (Panorama and VideoView) in favor of [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit).
