### ISSUE TITLE
Positioning of bottom icons with extended status bar

### ISSUE THREAD

**Issue by allanweir** [googlevr/gvr-ios-sdk#132]
When the status bar is extended (such as when using personal hotspot) the enter cardboard button is partly off the bottom of the screen.

**Comment by nathanmartz** [comment]
Thanks for the bug report!

**Comment by nathanmartz** [comment]
Actually, in what context/app are you seeing this? Can you post a screenshot?

**Comment by allanweir** [comment]
Sure. I have a GVRVideoView which is sized to the full width and height of the view (not screen) and it looks like the attachment. Strangely it doesn't happen every time. Sometimes I enter the view in landscape, sometimes in portrait but that doesn't seem to affect it.

![screen shot 2016-09-30 at 11 17 27](https://cloud.githubusercontent.com/assets/2892400/18988819/52c5d822-8700-11e6-9161-dad8f4ed5bd1.png)
