### ISSUE TITLE
Swift import

### ISSUE THREAD

**Issue by waltermvp** [googlevr/gvr-ios-sdk#133]
I attempted to import themodule into swift with no success.

``` swift
import GVRSDK
```

I get `no such module found`

Perhaps im using the incorrect name or is there a specific way to import into swift (maybe using a bridging header)?

**Comment by waltermvp** [comment]
Managed to get it working using a objective-c bridging header. IF this is the recommended way i can do a PR to include in the readme.

**Comment by iraritchiemeek** [comment]
Struggled with this for a long time too.
Some more swift tutorials would be useful.

This is the article that helped me in the end.
https://www.raywenderlich.com/136692/introduction-google-cardboard-ios

**Comment by lirunfengnotAlone** [comment]
might be you just build it..seems alright. display bugs?
