### ISSUE TITLE
Vertical Touch Tracking in pano video mode

### ISSUE THREAD

**Issue by RyanBertrand** [googlevr/gvr-ios-sdk#134]
Thanks for this library - we are very excited to use it on iOS!

I was wondering if there is a way to enabled vertical touch tracking?  The horizontal tracking works great but we would need vertical tracking as well. 

Please let me know.  Thanks for all the great work!

**Comment by nathanmartz** [comment]
There is not currently, but it's high on our backlog of features to add.

**Comment by ryannichols** [comment]
+1 on this. My users have been asking for this a lot. Would be great if we could get it on iOS.

**Comment by RyanBertrand** [comment]
Great to hear - thanks @nathanmartz!

**Comment by caiobzen** [comment]
+1 on this as well. I really need this feature :)

**Comment by yogevbar** [comment]
+1

**Comment by stuk88** [comment]
+1

**Comment by moshest** [comment]
+1

**Comment by uranpro** [comment]
+1

**Comment by huiwenTT** [comment]
+1

**Comment by deltatre-team-mobile** [comment]
+1

**Comment by ecristerna** [comment]
+1

**Comment by judithtaylor95** [comment]
+1

**Comment by icianedwards** [comment]
+1

**Comment by J-Mills** [comment]
+1

**Comment by sanjayc77** [comment]
Check out GVRKit: https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit (also available as a Cocoapod). It provides vertical touch tracking. The Panorama app showcases this.

**Comment by salil0505** [comment]
Hey @sanjayc77, does this work for GVRVideoView as well? The Panorama sample app is using GVRRendererView. Im setting the enableTouchTracking Bool to true for my GVRVideoView instance. Am I missing something?
