### ISSUE TITLE
Green screen after update to iOS SDK version 1.0.0

### ISSUE THREAD

**Issue by anubha-kiwitech** [googlevr/gvr-ios-sdk#135]
When loading video in GVRVideoView, the screen appears green until the video is loaded.
![att00001](https://cloud.githubusercontent.com/assets/1144695/19150652/95cf0a64-8be5-11e6-9557-d537c4ff48eb.png)

**Comment by kansujiya** [comment]
same here is there way to change green colour to black colour.

**Comment by nathanmartz** [comment]
Are you loading video via a URL or is it bundled with the app? What format is the video in question?

**Comment by justsomeguy-google-com** [comment]
I believe what you are seeing is the default background of our internal view.  Until the video loads we don't have anything else to show.  I don't think we expose any way to get that view.  There is a memory leak we fixed that would also show it, but downloading a video taking time will likely keep showing that.

I'll enter a task for us to let you set a load image.  That sounds like a good idea.

**Comment by kansujiya** [comment]
@nathanmartz , thanks for reply. When I am loading video  through URL the player shows green screen till player get first frame. And when we pass video locally from bundle then it's show blink only before playing. Formate of video is .mp4. please suggest any way to stop seeing green color or any way to change green color with black color. Thanks !

**Comment by kansujiya** [comment]
@justsomeguy-google-com. Yes please provide a way in SDK to set custom image while loading video time. If you have any other way to replace green color with any other color then please suggest.
Thanks

**Comment by sanjayc77** [comment]
Can you update to the new 1.0.1 GVRSDK and verify that the issue has been fixed? Thanks.

https://github.com/CocoaPods/Specs/blob/master/Specs/GVRSDK/1.0.1/GVRSDK.podspec.json

**Comment by sureshkansujiya** [comment]
@sanjayc77 Now Green issue (Memory Leak)has been resolved, But now we are facing weird hanging issue while playing Video.

**Comment by sanjayc77** [comment]
Can you provide more details? Is the GVRVideoView unresponsive to touch?

**Comment by sanjayc77** [comment]
Please open another Github issue for the hanging while playing Video problem. Thanks.

**Comment by anubha-kiwitech** [comment]
Issue added : https://github.com/googlevr/gvr-ios-sdk/issues/140
