### ISSUE TITLE
App freezes when switching viewer.

### ISSUE THREAD

**Issue by iraritchiemeek** [googlevr/gvr-ios-sdk#136]
`TCC__CRASHING_DUE_TO_PRIVACY_VIOLATION__:`

I believe this is because it never asks for camera permission, works fine in simulators.

**Comment by iraritchiemeek** [comment]
![](http://i.imgur.com/9pbND1F.jpg)
![](http://i.imgur.com/cfNI581.png)

**Comment by nathanmartz** [comment]
This is a change in iOS policy. To fix it you need to add the
NSCameraUsageDescription key to the app’s Info.plist as we've done in our
sample.

**Comment by iraritchiemeek** [comment]
Oh oops thanks!
