### ISSUE TITLE
Can not play video after download to NSDocument

### ISSUE THREAD

**Issue by minhtoantm** [googlevr/gvr-ios-sdk#137]
Hi team.
Thanks for your SDK, but I have a problem:
- Play video from http url: OK
- Download video to document folder inside app, play get "unknown error". I checked downloaded video, it's OK. Can you check and fix for me?
Best gard.

**Comment by sanjayc77** [comment]
We use AVPlayer class to load and play video. Make sure the video content is playable by AVPlayer. http://stackoverflow.com/questions/35651224/what-video-resolution-and-format-is-most-suitable-for-ios-apps

**Comment by minhtoantm** [comment]
When I add this video to Resource -> play OK.
Play this video from url -> OK
Download video to "Document" folder ->error unknown.

Do you check case: download video to local, and play that video?

Thank for reply.
