### ISSUE TITLE
Not able to add subview in video view in gvr iOS sdk

### ISSUE THREAD

**Issue by ashokvadivelu** [googlevr/gvr-ios-sdk#139]
How to add some dot view over the video view in gvr iOS sdk . I tried to add subview to videoview its working fine. But when i change the display mode to "kGVRWidgetDisplayModeFullscreenVR" its not working.
Please help me. i need to show two dot over the video view in vr mode.

**Comment by sanjayc77** [comment]
The VRView classes are not designed to host other subviews. Especially in VR mode. We only render OpenGL content in those.

**Comment by ashokvadivelu** [comment]
@sanjayc77 - 
Hi sanjay,
Thanks for your explanation. I am just doing sample app in VR using GVR iOS sdk .Below is my requirement please let me know how can i achieve this in GVR iOS idk.

Requirement:
I need to add two dot over the vr view(left eye and right eye). If the user locate certain position using that dot(Google Cardboard), i need to play a 360 video using video view .I tried this is "kGVRWidgetDisplayModeEmbedded" mode i can able to add dot over the video view .But when i change the mode to "kGVRWidgetDisplayModeFullscreenVR" i can't able to see the dot over the Vr view. Please let me know how can i append the dot over the videoview (both left and right eye view)

**Comment by sanjayc77** [comment]
That is not possible with the design of GVRVideoView. In VR mode, we can only render OpenGL content, which in this case is the video stream. What you are asking is to draw dots in OpenGL.

Take a look at GVRCardboardView class that is designed for displaying OpenGL content in VR/non-VR. But then you have to figure out how to show spherical video in it, which might be a higher hurdle.

**Comment by krishnakanthjb** [comment]
@ashokvadivelu : Did this solved your problem. I too have similar kind of requirement, I am trying to add buttons for Play/Pause and a seek Bar. Please let us know if your inputs.

Thanks
