### ISSUE TITLE
Add setting to reduce accelerometer frequency?

### ISSUE THREAD

**Issue by seanadkinson** [googlevr/gvr-ios-sdk#14]
Using this SDK for watching 360 videos, the experience is pretty jumpy.  Movements in the video happen with the slightest uncontrollable hand movements.

We had this problem in another application, and the experience was greatly improved just be reducing the accelerometer frequency from 60 Hz down to 15 Hz.

Can this library expose the frequency as a setting?  I guess in the latest IOS, this is the `CMMotionManager.accelerometerUpdateInterval`.

**Comment by nathanmartz** [comment]
Hi. What device were you seeing this jerkiness on?

**Comment by seanadkinson** [comment]
iPhone 6s.

**Comment by RikHeijdens** [comment]
We are also seeing this issue on the iPhone 6S. Compared to the Google VR Android SDK it's very jumpy. A fix, or a parameter that we can tune ourself would be appreciated.

**Comment by dav-cz** [comment]
In v0.9.0 we removed any head tracking prediction which should help. So I'm tentatively closing this.

Please feel free to re-open if you think that's not good enough :)

**Comment by RikHeijdens** [comment]
@dav-cz 

When rendering in monocular mode with v0.9.0 we're still experiencing very sensitive/jumpy head tracking compared to Android. Is there any chance this could be improved?
