### ISSUE TITLE
Is there any Buffering API available in GVR-iOS SDK

### ISSUE THREAD

**Issue by krishnakanthjb** [googlevr/gvr-ios-sdk#142]
Is there an api to access the buffering time of the video? This is essential for us to play the videos after certain buffer time. This is similar to PlayableDuration and Duration in MPMoviePlayer(Apple iOS player)

**Comment by sanjayc77** [comment]
Will didUpdatePosition delegate method help you provide the same functionality?

**Comment by abhi2015** [comment]
It'll be helpful to have something like ExoPlayer.getBufferedPosition for the VR view.

**Comment by sanjayc77** [comment]
We added playableDuration to GVRVideoView in 1.10.0.
