### ISSUE TITLE
Interface layout

### ISSUE THREAD

**Issue by ShaoShuaiiOS** [googlevr/gvr-ios-sdk#143]
Hello! I now use GVRPanoramaView Class, I want to ask whether our project can again a little bit open source.I want to a custom layout, for example, back button, the full screen button, and carboard button, position of him I was free.What can I do? Thank you!

**Comment by nathanmartz** [comment]
As mentioned in other threads, we won't be open sourcing the SDK and intentionally do not allow developers to customize core parts of the UX as they are all essential elements of how users interact with the cardboard ecosystem.
