### ISSUE TITLE
GVRVideoView for loadFromUrl is horribly slow/stucked

### ISSUE THREAD

**Issue by mstana** [googlevr/gvr-ios-sdk#144]
Hi, 

on compter it takes up to 5 seconds to download .mp4 video but in device with method loadFromUrl it takes up to 50 seconds, 10 times more than I was expecting. Even if part of video is downloaded the video stuck on some place and is not resuming at all. 

I am using version 0.8.*

Thanks for investigation

**Comment by sanjayc77** [comment]
Please try version 1.0.1.

Also the video has to be optimized for streaming. Check qtfaststart: https://pypi.python.org/pypi/qtfaststart

**Comment by mstana** [comment]
My video has just 26mb and its 17 seconds long, I am not sure if the video is issue in this case or something elese. 

But I will try this thanks

**Comment by nynohu** [comment]
I have same problem as @mstana . I am streaming a .m3u8 for playing video with GVRVideoView but it took more 1 minute for loading 1:24s HLS video.
