### ISSUE TITLE
BlackScreen when GVRVideoView play a local file

### ISSUE THREAD

**Issue by prudveekrishna** [googlevr/gvr-ios-sdk#145]
Hello team,

When I'm playing local video, I'm getting black screen (able to here audio) in 'kGVRWidgetDisplayModeFullscreenVR', but in 'kGVRWidgetDisplayModeFullscreen' video is displaying. Pod version 1.0.1.

Could you let me the issue? Am I missing anything?

Best,
Prudvee.
![img_0010](https://cloud.githubusercontent.com/assets/15937557/19567577/d361e406-970b-11e6-9b5f-3529ac3e55cc.PNG)

**Comment by sanjayc77** [comment]
Does this happen with the congo video in the sample app?

**Comment by prudveekrishna** [comment]
No, it happening in my app, with congo video.

**Comment by sanjayc77** [comment]
We have identified an issue, introduced in 1.0.1, where pausing the video also pauses the head tracking (motion tracking). This fix will be in the next release.

Can you verify that this issue does not happen as long as the video is playing?

Thanks

**Comment by prudveekrishna** [comment]
This issue exists at the starting of the video for the second time, even after playing the complete video for the first time without any pause.

**Comment by sanjayc77** [comment]
Is this in your own app or VideoWidgetDemo sample app?

**Comment by prudveekrishna** [comment]
my own app

**Comment by sanjayc77** [comment]
Hmmm, I cannot help you much with your own app. Can you reproduce the issue with the Sample app and provide a forked example on GitHub?

Reopen the issue if you can.
