### ISSUE TITLE
Hotspots support

### ISSUE THREAD

**Issue by Johndpmacdonald** [googlevr/gvr-ios-sdk#147]
How can I add hotspots to a panorama or video view ? I would like to implement the ability to look at a hotspot to trigger an action or render a different image/video. Any pointers are much appreciated :)

**Comment by sanjayc77** [comment]
VRView's are not designed for that kind of interaction. Your best option is to use the GVRCardboardAPI and OpenGL to render a pano and a hotspot. Unity is also another option to build for iOS.

**Comment by Johndpmacdonald** [comment]
Thanks - can you provide some pointers about how I can use the API and OpenGL to create hotspots? I would like to implement something similar to treasure hunt where you can look at something for a specific amount of time to trigger some action.
