### ISSUE TITLE
Crash due to memory issue on GVRPanoramaView.load()

### ISSUE THREAD

**Issue by iraritchiemeek** [googlevr/gvr-ios-sdk#148]
Around 90% of the time I try load an [11828 × 5914 360 panorama](http://texturify.com/content/10615/Sunset%20at%20pier.jpg) my app crashes. 
Other panoramas work fine _most_ of the time, however they still sometimes crash due to memory issues.
Is there anyway to debug this or a work around or is the image simply too big?

`2016-10-27 10:22:15.965574 tagvr[4970:1130485] This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.
 Stack:(
	0   CoreFoundation                      0x000000018cd101d8 <redacted> + 148
	1   libobjc.A.dylib                     0x000000018b74855c objc_exception_throw + 56
	2   CoreFoundation                      0x000000018cd10108 <redacted> + 0
	3   Foundation                          0x000000018d8f3f0c <redacted> + 192
	4   Foundation                          0x000000018d8f3c4c <redacted> + 76
	5   Foundation                          0x000000018d73f5dc <redacted> + 112
	6   Foundation                          0x000000018d8f28e8 <redacted> + 112
	7   UIKit                               0x0000000192ae6e64 <redacted> + 1688
	8   QuartzCore                          0x000000018ffaf40c <redacted> + 148
	9   QuartzCore                          0x000000018ffa40e8 <redacted> + 292
	10  QuartzCore                          0x000000018ffa3fa8 <redacted> + 32
	11  QuartzCore                          0x000000018ff20c64 <redacted> + 252
	12  QuartzCore                          0x000000018ff480d0 <redacted> + 512
	13  QuartzCor
Message from debugger: Terminated due to memory issue
`

Heres a screenshot of one of the rare times this particular panorama loads.
![screen shot 2016-10-27 at 10 15 14 am](https://cloud.githubusercontent.com/assets/10109509/19745706/566cbaba-9c2f-11e6-9572-2c4176d177bd.png)

**Comment by sanjayc77** [comment]
This is our supported image resolutions for VRViews: https://developers.google.com/vr/concepts/vrview

From the page:

Image specifications

VR view images can be stored as png, jpeg, or gif. We recommend you use jpeg for improved compression.
For maximum compatibility and performance, image dimensions should be powers of two (e.g., 2048 or 4096).
Mono images should be 2:1 aspect ratio (e.g. 4096 x 2048).
Stereo images should be 1:1 aspect ratio (e.g. 4096 x 4096).
