### ISSUE TITLE
Could the GVRAudioEngine support  audio of the AAC streaming  ?

### ISSUE THREAD

**Issue by lianguowu** [googlevr/gvr-ios-sdk#149]
Could the GVRAudioEngine support  audio of the AAC streaming  ?

**Comment by jkammerl** [comment]
The GVRAudioEngine uses the iOS Media stack to decode (and stream) sound files. 
AAC decoding [should be supported](http://stackoverflow.com/questions/1761460/supported-audio-file-formats-in-iphone?
answertab=oldest#tab-top) on iOS. However, many phones provide limited multi-channel decoding support. Are you trying to stream an ambisonic soundfield?
