### ISSUE TITLE
After load video in VR mode, screen is in wrong size

### ISSUE THREAD

**Issue by wsdfz** [googlevr/gvr-ios-sdk#15]
After a video is running in kGCSWidgetDisplayModeFullscreenVR mode, reload it by:
```
    NSString *videoPath = [[NSBundle mainBundle] pathForResource:@"congo" ofType:@"mp4"];
    [_videoView loadFromUrl:[[NSURL alloc] initFileURLWithPath:videoPath]];
```

and the screen will be in wrong size with a black block on the top. 

![thumb_img_4281_1024](https://cloud.githubusercontent.com/assets/8577467/14906464/5145cdf8-0dee-11e6-8a0f-c476d8376395.png)

**Comment by sanjayc77** [comment]
This is fixed in GVRSDK 0.8.0.
