### ISSUE TITLE
green screen

### ISSUE THREAD

**Issue by ghenzhimura** [googlevr/gvr-ios-sdk#150]
I got green screen in gvr video view after updating to v1.0.1. it happened after the first video played, the second video and the next video will be green screen but the sound its fine. any idea why its happened?

**Comment by sanjayc77** [comment]
How are you loading the second and next video's? Are you using didUpdatePosition to detect when the previous video has finished?

**Comment by ghenzhimura** [comment]
i made native ui component gvr video for react native.

here is my sample code.
`
RCT_CUSTOM_VIEW_PROPERTY(videoUrl, NSString, GVRVideoView)
{
  [_videoView loadFromUrl:[NSURL URLWithString: videoUrl]
                   ofType:kGVRVideoTypeMono];
}


- (UIView *)view
{
  _videoView = [[GVRVideoView alloc] init];
  _videoView.delegate = self;
  _videoView.enableFullscreenButton = YES;
  _videoView.enableCardboardButton = YES;
  _videoView.enableTouchTracking = YES;
  
  _isPaused = NO;
  return _videoView;
}

#pragma mark - GVRVideoViewDelegate

- (void)widgetViewDidTap:(GVRWidgetView *)widgetView {
  if (_isPaused) {
    [_videoView resume];
  } else {
    [_videoView pause];
  }
  _isPaused = !_isPaused;
}

- (void)widgetView:(GVRWidgetView *)widgetView didLoadContent:(id)content {
  NSLog(@"Finished loading video");
}

- (void)widgetView:(GVRWidgetView *)widgetView
didFailToLoadContent:(id)content
  withErrorMessage:(NSString *)errorMessage {
  NSLog(@"Failed to load video: %@", errorMessage);
}

- (void)videoView:(GVRVideoView*)videoView didUpdatePosition:(NSTimeInterval)position {
  // Loop the video when it reaches the end.
  if (position == videoView.duration) {
    [_videoView seekTo:0];
    [_videoView resume];
  }
}`

**Comment by haihoang88** [comment]
Does anyone have an update about this. I got this issue too.

**Comment by mstana** [comment]
Same issue for me. Video played well with 0.8.* but with 1.0.1 I got first black screen then (when video si loaded by framework) green screen. App is not stuck, just view is green.

**Comment by sanjayc77** [comment]
Can you please test on 1.10.0 release?

**Comment by SeanLintern** [comment]
Also seem to be experiencing this, only when streaming a source file. Observing the 'playableDuration' shows that on this particular video, goes from 0-10s then gets stuck for some time and then seems to bounce +- 2s back and forth.

**Comment by desmondmcnamee** [comment]
If this helps at all, it seems to only happen to me when the GVRVideoView gets added to a view that isn't currently on screen (for example in a collectionViewCell that gets loaded from a .xib before being scrolled to).

I was able to fix the issue by programmatically adding the GVRVideoView when the cell is visible.

**Comment by Premal-Khetani** [comment]
Same here i got the green screen every time with local video file or with URL file.

**Comment by sanjayc77** [comment]
You should switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). Check out the updated VideoWidgetDemo sample which uses proper color conversion.
