### ISSUE TITLE
How to enable/implement controls (like play, pause and seeker) on the GVRVideoView - iOS SDK

### ISSUE THREAD

**Issue by krishnakanthjb** [googlevr/gvr-ios-sdk#152]
Could you please let us know, if is there any standard API available with GVR-iOS-SDK to enable the controls on the player.
- Play option
- Pause option
- Seek bar and etc.

Also let us know if cardboard app has any special configurations or controls, so that we can apply the same for my customised app.

Any help appreciated..Thanks

**Comment by freddm** [comment]
Use the GVRVideoView class and Implement GVRVideoViewDelegate. I myself have built my own custom video controls on top of the video view (not the cardboard view). https://developers.google.com/vr/ios/reference/interface_g_v_r_video_view

**Comment by krishnakanthjb** [comment]
Can I have that customised code, it helps me and also saves time.

**Comment by krishnakanthjb** [comment]
We have observed the following code snippet is used to Play or Pause:
- (void)widgetViewDidTap:(GVRWidgetView *)widgetView {
    if (_isPaused) {
        [_videoView resume];
    } else {
        [_videoView pause];
    }
    _isPaused = !_isPaused;
}


Like wise is there any delegate method to implement the SEEK functionality.
