### ISSUE TITLE
Enable bitcode? 

### ISSUE THREAD

**Issue by mbanasiewicz** [googlevr/gvr-ios-sdk#154]
Hello,
first of all thank you for this great library!
There seems to be a problem with GVRAudioEngine missing bitcode, is it possible for you to compile that file including bitcode?
```libGoogleCardboardSDK.a(GVRAudioEngine_91e63440cd39d6269dadebd554789f11.o) does not contain bitcode```

**Comment by sanjayc77** [comment]
This is available in 1.10.0 release.
