### ISSUE TITLE
How to get/set audio current time with GVRAudioEngine?

### ISSUE THREAD

**Issue by pedroferreira1** [googlevr/gvr-ios-sdk#155]
I am using GVRAudioEngine to play an ambisonic audio with a 360º video. Is it possible to change the audio time using it? 
When I change the video time I need to change the audio time also.

**Comment by jkammerl** [comment]
GvrAudioEngine currently doesn't provide methods to synchronize audio and video playback. Also A/V synchronization should happen by the video player and cannot be guaranteed by just simultaneously triggering audio and video playback. We are currently investigating how to extend our API to support ambisonic decoding for 360 videos. Stay tuned for updates!
