### ISSUE TITLE
GVRAudioEngine load remote file

### ISSUE THREAD

**Issue by pedroferreira1** [googlevr/gvr-ios-sdk#159]
I am having trouble loading audio files that are not in the main budle. I tried loading from a remote URL or a file saved in the app documents directory without success.

Is it possible to do this somehow?

**Comment by jkammerl** [comment]
GVRAudioEngine can load sound files from the SD card. Network based loading of sound assets is not currently supported.

**Comment by andreabadesso** [comment]
How do I connect a SD card on an iphone?
