### ISSUE TITLE
Suppress insert Cardboard transition screen via Unity

### ISSUE THREAD

**Issue by paulgailey** [googlevr/gvr-ios-sdk#161]
How can this display of the transition screen be suppressed via Unity?

 [https://youtu.be/4P0msp3Dw8o](https://youtu.be/4P0msp3Dw8o)

I've read previous threads that discuss issues: https://github.com/googlevr/gvr-ios-sdk/issues/9

I think it's Android equivalent is https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/GvrView#setTransitionViewEnabled(boolean) but it does not seem possible for iOS - or am i **mistaken**?

**Comment by sanjayc77** [comment]
This is being addressed in the forthcoming release.

**Comment by paulgailey** [comment]
The last iOS update was 22nd Sep,  does your answer @sanjayc77 suggest that an iOS update is imminent? (days not weeks?)

**Comment by sanjayc77** [comment]
Without being more specific: soon.  :-)

**Comment by sanjayc77** [comment]
This is out in 1.10.0.
