### ISSUE TITLE
Undefined symbols for architecture x86_64:  "_OBJC_CLASS_$_GVRPanoramaView", referenced from:       objc-class-ref in PanoramaViewController.o ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by martint028** [googlevr/gvr-ios-sdk#162]
Showing Recent Messages
  "_OBJC_CLASS_$_GVRPanoramaView", referenced from:

**Comment by mbanasiewicz** [comment]
Are you linking the library correctly ? http://stackoverflow.com/questions/2906147/what-does-the-all-load-linker-flag-do

**Comment by martint028** [comment]
in my project add another .xcconfig , i want use cocoapods at the same time,so i add 
>#include "Pods/Target Support Files/Pods-QiGuangVR/Pods-QiGuangVR.debug.xcconfig"
>#include "Pods/Target Support Files/Pods-QiGuangVR/Pods-QiGuangVR.release.xcconfig"

before my .xcconfig.
other pods is ok, only GVRSDK can't work.
I have tried to move GVRSDK file into my program, but many error appeared.
– _ –

**Comment by sanjayc77** [comment]
Does this happen with the Sample/Panorama project?

**Comment by JRJian** [comment]
i have the same issue

**Comment by RichardLindhout** [comment]
+1 for a fix

**Comment by sanjayc77** [comment]
You should switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). Check out the updated Panorama sample.
