### ISSUE TITLE
Support 'place your phone into the viewer' message in Landscape orientation

### ISSUE THREAD

**Issue by allanweir** [googlevr/gvr-ios-sdk#164]
Hi,
I have an application using the GVR SDK which is working great except when the user goes to switch to VR mode whilst already in Landscape mode. The result is:
- User is viewing video as 360 in landscape
- User presses VR button on bottom right
- A message appears in portrait orientation so user begins to rotate phone to read it
- Then they either see they need to put their phone back in landscape, or the message disappears before they have time and it looks like a glitch.

I think the SDK should either not show the message, or since it seems like an important instruction - the UIView containing the message should work in landscape mode too, with a short delay to allow the user to place their phone in their headset.

It's easier to replicate if your app is fixed to Landscape orientation as the message only shows for a second. A slightly smaller issue is the delay in loading the animation on the view - is it possible to get a placeholder image (the first frame) in whilst the animation loads?

Sorry if this has been mentioned before, I had a look at existing issues but couldn't find anything.

Thanks,
Allan

**Comment by sanjayc77** [comment]
Fair observation and a good use case of the user being in landscape mode when entering VR. We are looking into turning off the transition screen in the next release. And we have a tracking bug for a landscape version of the transition screen.

Thanks
