### ISSUE TITLE
What is the maximum resolution/size of the image that GVRPanoramaView and GVRVideoView support?

### ISSUE THREAD

**Issue by haihoang88** [googlevr/gvr-ios-sdk#165]
I tried to load an image with resolution 6912x3456 to GVRPanoramaView running on an iPod 5 iOS 9.3.5 and it crashed instantly.

**Comment by nathanmartz** [comment]
4096x4096 is the max res.

**Comment by haihoang88** [comment]
I don't think that is true for all devices. When I try to run the above image on an iPhone 6s device, it works fine.

**Comment by nathanmartz** [comment]
That is the size that works for all devices. If you want image sizes that
only work on some phones then you can consult the documentation for each
device.

**Comment by haihoang88** [comment]
Hi, can you show me such documents for each devices?
