### ISSUE TITLE
Custom Controls in GVRVideoView - GVRWidgetDisplayModeFullscreenVR

### ISSUE THREAD

**Issue by prudveekrishna** [googlevr/gvr-ios-sdk#166]
Team,

Can we implement/display custom controls in GVRWidgetDisplayModeFullscreenVR?(Find attached screenshot) We're playing video using GVRVideoView.

In console we're able to see customised view, GVRGlView, UIButton, QTMButton as subviews. But subviews are not visible in GVRWidgetDisplayModeFullscreenVR

![img-20161116-wa0004](https://cloud.githubusercontent.com/assets/15937557/20428825/31381d6e-adb1-11e6-87ca-c5eab33006bc.jpg)

 
Thanks in advance
Prudvee

**Comment by nathanmartz** [comment]
If you want to add custom controls you should use the lower level GVRView and build it up yourself. VR View is meant to be simpler and more turnkey.

**Comment by prudveekrishna** [comment]
@nathanmartz Thank you. Is GVRView available in iOS?

**Comment by nathanmartz** [comment]
Sorry, on iOS It's CardboardView. Same idea.
