### ISSUE TITLE
Can't release memory using loadImage:nil for GVRPanoramaView

### ISSUE THREAD

**Issue by tk820723** [googlevr/gvr-ios-sdk#169]
I need to release all the memory for GVRPanoramaView when panoView disappears. I tried to call loadImage:nil but the memory was not released, so I had to remove the whole panoView from subview and released it to release the memory and I would create another when it appeared. However, this will sometimes cause crash on gfx::Renderer::VertexArrayResource::UpdateAndCheckBuffers: when users swipe too fast. Any solution that I can release the memory without remove the whole panoView?

**Comment by EthanChouTW** [comment]
+1

**Comment by QEllis** [comment]
+1

**Comment by sanjayc77** [comment]
Please move to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit) since PanoramaView is now deprecated. You should check out the updated PanoramaView sample based on GVRKit. It gives you more control over images you load into it.
