### ISSUE TITLE
configuring GVRCardboardView without sound kills existing audio playback

### ISSUE THREAD

**Issue by deeje** [googlevr/gvr-ios-sdk#170]
I have a 3D VR app that plays music using the MPMusicPlayerController.  When I configure and display a GVRCardboardView and enableVR, sound from the MPMusicPlayerController stops.  I am NOT instantiating a GVRAudioEngine object.  Is there a way to tell GVR to not do this?

**Comment by deeje** [comment]
just updated to v1.10.0, and am hiding the transition view (thank you!), but the problem persists.  Thanks for your attention!

**Comment by sanjayc77** [comment]
Would this help: http://stackoverflow.com/questions/12455082/play-silent-videos-alongwith-the-music-app-playing-songs

**Comment by deeje** [comment]
Yes, that seems like a promising solution.

Fwiw, my app uses the system music player to queue up and play songs from the user’s music library.  You can probably test a fix by simply playing a song in the Music app, then launching a test app that loads the Cardboard view.

**Comment by deeje** [comment]
Can we keep this open?

I have soft-launched v10.0 of tappr.tv on the App Store, with Cardboard support…  

https://itunes.apple.com/us/app/tappr.tv-community-created/id400751858?mt=8

You can see/hear that the experience of switching to VR mode is a bit jolting, as the code must pause the audio/visual, initialize and display the Cardboard view, then resume the audio/visual playback.  It would be so much better for the user if the code didn't have to make the audio stutter like this.
