### ISSUE TITLE
GVRVideoView ignores YCbCr matrix information

### ISSUE THREAD

**Issue by junpluse** [googlevr/gvr-ios-sdk#172]
From v1.10.0, GVRVideoView renders video with wrong colors when YCbCr matrix information is included in the file.

For example, our video (in [Rec. 709](https://developer.apple.com/reference/coremedia/kcmformatdescriptioncolorprimaries_itu_r_709_2) format) looks like below with v1.0.1:
![1_0_1](https://cloud.githubusercontent.com/assets/312595/21093598/065a9ad4-c096-11e6-827a-811bffcf9406.jpg)

but with v1.10.0:
![1_10_0](https://cloud.githubusercontent.com/assets/312595/21093600/07db9d9a-c096-11e6-938a-62f0892f1e86.jpg)

Perhaps GVRVideoView uses a hard-coded color space?

**Comment by sanjayc77** [comment]
Is there an example video you can point us to? Maybe convert the congo.mp4 video to 709 space?

To answer your question, we choose between two color space:
_colorConversionMatrix = CFEqual(colorAttachments, kCVImageBufferYCbCrMatrix_ITU_R_601_4)
                                   ? kColorConversionMatrix601
                                   : kColorConversionMatrix709;

The two matrices are defined as:

// BT.601 colorspace, studio swing.
GLKMatrix4 kColorConversionMatrix601 = {
  1.164, 0.0, 1.596, -0.87075,
  1.164, -0.392, -0.813, 0.52925,
  1.164, 2.017, 0.0, -1.08175,
  0.0, 0.0, 0.0, 1.0
};

// BT.709 colorspace, studio swing.
GLKMatrix4 kColorConversionMatrix709 = {
  1.164, 0.0, 1.793, -0.87075,
  1.164, -0.213, -0.533, 0.52925,
  1.164, 2.112, 0.0, -1.08175,
  0.0, 0.0, 0.0, 1.0
};

**Comment by junpluse** [comment]
Thanks for your quick response.

I converted `congo.mp4` to 709 space (using QuickTime Player on macOS Sierra w/ File → Export → iPad, iPhone, iPod touch or Apple TV)
https://d17oy1vhnax1f7.cloudfront.net/items/061f3N2A1Q0W0p0b420D/congo.m4v

**Comment by sanjayc77** [comment]
Added to internal tracker. Thanks for reporting.

**Comment by chansencc** [comment]
I am having the same issue.

**Comment by allanweir** [comment]
Also seeing this issue, can provide a video snippet to help if needed

**Comment by deltatre-team-mobile** [comment]
+1

**Comment by MarkDKoslow** [comment]
+1

**Comment by jacobfnl** [comment]
In the mean time, it may be a bit of a hassle, but you can encode your videos using ffmpeg to remove the bt.709 color space. https://ffmpeg.org

**Comment by junpluse** [comment]
The issue seems to have been fixed in v1.20. Thanks!
https://developers.google.com/vr/ios/release-notes#gvr_sdk_and_ndk_for_ios_v1200

**Comment by abhi2015** [comment]
@jacobfnl Could you please share the ffmpeg script that you used for the conversion?

**Comment by jacobfnl** [comment]
@abhi2015, sure thing.
`ffmpeg -i input.mov -c:v libx264 -b:v 20M -pix_fmt yuv420p -c:a copy output.mp4`
`-i` your input video (or image sequence)
`-c` is codec, further specified by `-c:v` for video, and `-c:a` for audio
`-b:v` video bitrate alternative would be `-crf` and a value typically between 18-25
`-pix_fmt` still using yuv420p but it will no longer be yuv420p(tv, bt709)
Note, for audio codec, I am simply copying without re-encoding in this example.

**Comment by sanjayc77** [comment]
You should switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). Check out the updated VideoWidgetDemo sample which does the proper color conversion.
