### ISSUE TITLE
Playing a second video on different controller doesn't work?

### ISSUE THREAD

**Issue by andrewfashion** [googlevr/gvr-ios-sdk#173]
If I play a GVRVideoView on the first screen, and then stop it. And then I proceed to a new controller to load a new GVRVideoView I just get a green screen...

But if don't play the first video on the first screen, the 2nd controller works fine...

I can't seem to figure out what's going on.

Thanks!

**Comment by sanjayc77** [comment]
Is this on the latest version of the SDK (1.10.1)?

**Comment by andrewfashion** [comment]
Yes @sanjayc77

**Comment by sanjayc77** [comment]
Looking into it. Will post when I have an update.

Thanks for reporting.

**Comment by sanjayc77** [comment]
This is not happening with the VideoWidgetDemo sample app.

I added a UIBarButtonItem to the navigation bar and an action to VideoPlayerViewController (also add the identifier "videoViewController" to the view controller in storyboard):

```
- (IBAction)next:(id)sender {
  [_videoView stop];
  VideoPlayerViewController *viewController = [self.storyboard instantiateViewControllerWithIdentifier:@"videoViewController"];
  [self.navigationController pushViewController:viewController animated:YES];
}
```

There video plays fine in either view controller instance.

**Comment by SeanLintern** [comment]
I did the experiment above, using the demo with the streamed video, on the second VC the cardboard is just black.

**Comment by andrewfashion** [comment]
Thank you. I think I got it figured out, it was my wrapper I made.
