### ISSUE TITLE
Streaming stutter / stopping + green screen

### ISSUE THREAD

**Issue by SeanLintern** [googlevr/gvr-ios-sdk#175]
Using the video widget demo.

Using the player with a large mono file, through streaming, usually loads the first 10± seconds then stops, theres not updates given through any delegates methods to show that its stopped but the current position is reported. Most files I have are showing green through both local and stream. Downloading the source file through browser and opening in Quicktime shows no green.

EDIT:

Rolled back to 1.0.1 and videos are no longer green, but still have some issues streaming large files with no method of reacting through delegate methods, a willBuffer method and startedPlaying would be great and the chance to manipulate the update timer interval.

**Comment by sanjayc77** [comment]
The green video and stuttering is a bug in 1.10.1. This will be fixed in the next release.
