### ISSUE TITLE
Loading / Buffering Indicator

### ISSUE THREAD

**Issue by allanweir** [googlevr/gvr-ios-sdk#176]
Hi Guys,
Thanks for responding to my issues on here in the past, the SDK is looking sweet. 

I was wondering if there are any plans to add an indicator UI to the GVRVideoView to show buffering of video content? It doesn't seem to be possible to dynamically add UI elements to the VR stereo display from what I can tell. It would be more trivial outside of stereo mode but within it the code is a lot more complex to display UI I'm assuming (OpenGL etc.)

I've seen an old issue at https://github.com/googlevr/gvr-ios-sdk/issues/152 which talks about more than this but I feel like a loading indicator as a minimum should be included in a video playing control like the GVRVideoView for usability / helpful feedback in a VR space.

Cheers,
Allan

**Comment by nathanmartz** [comment]
We don't have any plans to add this currently, but you never know :)

**Comment by keakalamudo** [comment]
+1

**Comment by MohammadrezaZamanieh** [comment]
hi @allanweir  how you play video streamly?

**Comment by sanjayc77** [comment]
You should switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). You provide the AVPlayer to GVRVideoRenderer and thus are in full control of its loading/buffering state. Check out the updated VideoWidgetDemo sample.
