### ISSUE TITLE
Enable bitcode part 2

### ISSUE THREAD

**Issue by mbanasiewicz** [googlevr/gvr-ios-sdk#178]
Hey! 
my previous issue was closed however the problem remains:

```ld: 'xxx/vr/libGVRView.a(pano_renderer.o)' does not contain bitcode.```

**Comment by apan06** [comment]
I'm bumping this request, do you have any ETA? Thanks in advance!

**Comment by sanjayc77** [comment]
Bitcode has been enabled for the past few versions.
