### ISSUE TITLE
Head Tracking sensitivity when rendering in 'magic window' mode

### ISSUE THREAD

**Issue by RikHeijdens** [googlevr/gvr-ios-sdk#181]
We observed that head tracking sensitivity when rendering in magic window mode on iOS (iPhone 6S) is much more sensitive than head tracking on an Android phone (Nexus 5X) when using the GVR SDK.

We would like to have the ability to tune this sensitivity, in order to make both platforms behave similarly.

I think we should be able to do this on our end by implementing some kind of low-pass filter and applying that to the head rotation returned by the GVR SDK, but this sounds rather hacky and inefficient.

Is this a parameter that could be implemented within the SDK?

See also the previous discussion here: https://github.com/googlevr/gvr-ios-sdk/issues/14#issuecomment-238337086

**Comment by paulgailey** [comment]
Rik, this is how we mitigated it on Android. 

https://github.com/googlevr/gvr-unity-sdk/issues/170#issuecomment-253976810

Perhaps similar would work on iOS. Perhaps not.

**Comment by sanjayc77** [comment]
Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). You have access to the source and can mitigate the issue that fits your needs.
