### ISSUE TITLE
Green screen when allocating/deallocating a video view at the same time.

### ISSUE THREAD

**Issue by jclou** [googlevr/gvr-ios-sdk#183]
In my code I am playing a video with a GVRVideoView and at a certain time I want to stop and play a different video. The second video always shows a green screen, but the audio plays properly.

In this contrived example, the first video view doesn't need even need to be loaded with a video or added to any view to break the second video. If I wait until -dealloc is called on the first video view before creating the second, then everything works as expected.
```
- (void)viewDidLoad {
    [super viewDidLoad];
    
    // Commenting out this line fixes the video
    self.videoView = [GVRVideoView new];
    
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        self.videoView = [[GVRVideoView alloc] initWithFrame:CGRectMake(0, 100, 192, 108)];
        [self.videoView loadFromUrl:[NSURL URLWithString:@"https://pannellum.org/images/video/jfk.mp4"]];
        self.videoView.delegate = self;
        [self.view addSubview:self.videoView];
    });
}

- (void)widgetView:(GVRWidgetView *)widgetView didLoadContent:(id)content {
    [(GVRVideoView *)widgetView play];
}
```

I am getting this behavior on both 1.0.1 and 1.10.0. Versions 0.8.x and 0.9.x seem to work as expected.

**Comment by nynohu** [comment]
In version 1.20.0 I got the same problem although it seem to be fixed by version description. Please check the issue.
> Could not create Texture, err = -6683


![screen shot 2017-02-06 at 1 46 21 pm](https://cloud.githubusercontent.com/assets/2919898/22635062/3ae73b78-ec73-11e6-8231-46765005a28b.png)

**Comment by jclou** [comment]
I am also still getting this issue on version 1.20.

**Comment by sanjayc77** [comment]
Does this happen even when you don't reuse the same GVRVideoView instance (don't use a singleton)?

**Comment by jclou** [comment]
In my case, I have a ClassA instance that has a GVRVideoView. At some point, I get rid of my instance of ClassA and replace it with a new instance that has its own different GVRVideoView. The new GVR player gets stuck with a green screen. You can reproduce it with the code blow:
```
- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.videoView = [[GVRVideoView alloc] initWithFrame:CGRectMake(0, 100, 192, 108)];
    self.videoView.delegate = self;
    [self.videoView loadFromUrl:[NSURL URLWithString:@"https://pannellum.org/images/video/jfk.mp4"]];
    [self.view addSubview:self.videoView];
    
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [self.videoView pause];
        [self.videoView removeFromSuperview];
        self.videoView = nil;
        
        self.videoView2 = [[GVRVideoView alloc] initWithFrame:CGRectMake(0, 300, 192, 108)];
        self.videoView2.delegate = self;
        [self.videoView2 loadFromUrl:[NSURL URLWithString:@"https://pannellum.org/images/video/jfk.mp4"]];
        [self.view addSubview:self.videoView2];
    });

- (void)widgetView:(GVRWidgetView *)widgetView didLoadContent:(id)content {
    [(GVRVideoView *)widgetView play];
}
```

Also when creating two GVRVideoViews at the same time, the first one gets stuck with a green screen.

```
- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.videoView = [[GVRVideoView alloc] initWithFrame:CGRectMake(0, 100, 192, 108)];
    self.videoView.delegate = self;
    [self.videoView loadFromUrl:[NSURL URLWithString:@"http://d8d913s460fub.cloudfront.net/krpanocloud/video/airpano/video-1920x960a.mp4"]];
    [self.view addSubview:self.videoView];
    
    self.videoView2 = [[GVRVideoView alloc] initWithFrame:CGRectMake(0, 300, 192, 108)];
    self.videoView2.delegate = self;
    [self.videoView2 loadFromUrl:[NSURL URLWithString:@"https://pannellum.org/images/video/jfk.mp4"]];
    [self.view addSubview:self.videoView2];
}
```

**Comment by Sourcebits-Ravik** [comment]
I am facing black screen instead of green screen after updating from 1.10 to 1.20.0. 
<img width="624" alt="screen shot 2017-02-11 at 10 43 25 pm" src="https://cloud.githubusercontent.com/assets/19218813/22855784/935b8ab6-f0ab-11e6-934d-d3ff361de4a5.png">

**Comment by nynohu** [comment]
@sanjayc77 It's ok if I create new instance  instead of using singleton.

**Comment by tibewww** [comment]
Anybody managed to sold that ?

**Comment by nynohu** [comment]
@tibewww  It was still show green screen if you use the same GVRVideoView instance for loading videos in many times.

**Comment by tibewww** [comment]
ok, so we don't have any solution ?

**Comment by deltatre-team-mobile** [comment]
issue still present on 1.30.0 despite the release note claims to have fixed it

**Comment by tibewww** [comment]
is there a way to load a new GVRVideoView eachtime you trigger the video by click button do you think ?

**Comment by sanjayc77** [comment]
This issue was, inadvertently, not fixed in 1.30. Sorry about the confusion. We will have this fix in the next release.

**Comment by markusekblad** [comment]
@sanjayc77 When might that be available?

**Comment by tibewww** [comment]
any news about the next release date of the next version :( ?

**Comment by sanjayc77** [comment]
GVRVideoView is now deprecated. Switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). GVRKit provides fine grained control over AVPlayer playback and its rendering. See the updated VideoWidgetDemo sample.
