### ISSUE TITLE
if using Firebase/Messaging, i got error

### ISSUE THREAD

**Issue by mycisco** [googlevr/gvr-ios-sdk#186]
GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
duplicate symbol _OBJC_IVAR_$_GTMLogger.filter_ in:
    /Users/marbean/Desktop/test/Pods/GVRSDK/SDK/Libraries/libGVRSDK_arm.a(GTMLogger_064d3b4808a58a3b99e253e55cd34186.o)
    /Users/marbean/Library/Developer/Xcode/DerivedData/test-cljaotsrvxrqcfarajvlghvtsgtz/Build/Products/Debug-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
duplicate symbol _OBJC_IVAR_$_GTMLogger.writer_ in:
    /Users/marbean/Desktop/test/Pods/GVRSDK/SDK/Libraries/libGVRSDK_arm.a(GTMLogger_064d3b4808a58a3b99e253e55cd34186.o)
    /Users/marbean/Library/Developer/Xcode/DerivedData/test-cljaotsrvxrqcfarajvlghvtsgtz/Build/Products/Debug-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
duplicate symbol _OBJC_IVAR_$_GTMLogStandardFormatter.pname_ in:
    /Users/marbean/Desktop/test/Pods/GVRSDK/SDK/Libraries/libGVRSDK_arm.a(GTMLogger_064d3b4808a58a3b99e253e55cd34186.o)
    /Users/marbean/Library/Developer/Xcode/DerivedData/test-cljaotsrvxrqcfarajvlghvtsgtz/Build/Products/Debug-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
duplicate symbol _OBJC_IVAR_$_GTMLogStandardFormatter.pid_ in:
    /Users/marbean/Desktop/test/Pods/GVRSDK/SDK/Libraries/libGVRSDK_arm.a(GTMLogger_064d3b4808a58a3b99e253e55cd34186.o)
    /Users/marbean/Library/Developer/Xcode/DerivedData/test-cljaotsrvxrqcfarajvlghvtsgtz/Build/Products/Debug-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
duplicate symbol _OBJC_IVAR_$_GTMLogLevelFilter.verboseLoggingEnabled_ in:
    /Users/marbean/Desktop/test/Pods/GVRSDK/SDK/Libraries/libGVRSDK_arm.a(GTMLogger_064d3b4808a58a3b99e253e55cd34186.o)
    /Users/marbean/Library/Developer/Xcode/DerivedData/test-cljaotsrvxrqcfarajvlghvtsgtz/Build/Products/Debug-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
ld: 25 duplicate symbols for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Anilkumarkotur** [comment]
having same issue

**Comment by sanjayc77** [comment]
This is similar to #163. Thanks for reporting.
