### ISSUE TITLE
Error when trying to include two libraries in one application

### ISSUE THREAD

**Issue by jtyson** [googlevr/gvr-ios-sdk#187]
We have an application which includes both Panorama View and Cardboard View and as such we have added two entries in the Podfile as follows.
pod 'GVRSDK/SDK'
pod 'GVRSDK/GVRView'

When doing this we end up with linker conflicts such as follows.

Is there a way for us to upgrade to latest version and not have this issue?

Thanks for the great work guys!

Jon

duplicate symbol _OBJC_IVAR_$_GTMSessionUploadFetcher._uploadFileURL in:
 /Pods/GVRSDK/SDK/Libraries/libGVRSDK_arm.a(GTMSessionUploadFetcher_58e8d1383eec8dda9cc9d9fddbb79d36.o)
 /Pods/GVRSDK/GVRView/Libraries/libGVRView_arm.a(GTMSessionUploadFetcher_58e8d1383eec8dda9cc9d9fddbb79d36.o)

duplicate symbol _OBJC_CLASS_$_DeviceParamsSyncHelper in:
   /Pods/GVRSDK/SDK/Libraries/libGVRSDK_arm.a(DeviceParamsSyncHelper.mm.o)
   /Pods/GVRSDK/GVRView/Libraries/libGVRView_arm.a(DeviceParamsSyncHelper.mm.o)

**Comment by sanjayc77** [comment]
Thanks for reporting. Added to our internal tracker.

**Comment by sanjayc77** [comment]
This is similar to #163.
