### ISSUE TITLE
GVR Audio on iOS can't read from temp directory

### ISSUE THREAD

**Issue by achuvm** [googlevr/gvr-ios-sdk#192]
Hi, 

We're trying to play some audio using the iOS SDK and we're running into an issue when we attempt to play some audio that we've downloaded from the web.

We know that GVR can only play local files, so we've downloaded the file to the temp directory and we're then giving the GVR Audio API the path to the file at the temp directory and it still errors out.

Here's an example of the filepath:

/private/var/mobile/Containers/Data/Application/0BE58BCC-F8C6-4DB6-9FD0-62650631B582/tmp/37BFD4A2-9484-4562-AD6F-9B7459B85F28-1979-00000846B1CE7E8A.tmp

The original file is a mp3 that works when we download + play on the Android GVR Audio SDK.

We've tried downloading the file to both Home as well as Documents directory, but still a no-go.

The code that downloads the file is below:

```
    NSURL *URL = [NSURL URLWithString:[NSString stringWithUTF8String:url.c_str()]];
    __block NSString *tempFilePath;

    downloadDataWithURLSynchronous(URL, ^(NSData *data, NSError *error) {
        if (error.code == NSURLErrorCancelled){
            return;
        }
        
        if (!error) {
            NSString *fileName = [NSString stringWithFormat:@"%@.tmp", [[NSProcessInfo processInfo] globallyUniqueString]];
            NSURL *fileURL = [NSURL fileURLWithPath:[NSTemporaryDirectory() stringByAppendingPathComponent:fileName]];
            
            [data writeToURL:fileURL atomically:NO];
            
            *temp = true;
            tempFilePath = [fileURL path];
        }
    });
```

**Comment by jkammerl** [comment]
Apologies for the delayed response. I created an internal bug for this issue and I'll let you know as soon as this is fixed.

**Comment by aclockworkkelly** [comment]
Hi, achuvm, This issue has been addressed internally and will be included in the next release of GVR Audio on iOS.

Apologies for the delay in this coming to our attention.
