### ISSUE TITLE
GVR Enable Bitcode

### ISSUE THREAD

**Issue by sahibhussain** [googlevr/gvr-ios-sdk#194]
`ld: '/Users/sahib/Desktop/Untouched/Pods/GVRSDK/Libraries/libGVRSDK.a(DeviceParamsSyncHelper.mm.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

whenever i run my app on physical device this error comes up. however, it run on simulator. Please let me know what to do.

**Comment by tibewww** [comment]
disable bitcode in your project build settings and it should work ;)

**Comment by MatejBalantic** [comment]
@tibewww I don't really want that just to include a dependency. Any chance we get bitcode into GVR project?

**Comment by sanjayc77** [comment]
Some code in the GVRSDK did not get enabled with Bitcode. This will be fixed in the next release.

**Comment by sanjayc77** [comment]
Bitcode has been enabled for the past few releases.
