### ISSUE TITLE
Post processing in GCSCardboardView

### ISSUE THREAD

**Issue by FigazzZ** [googlevr/gvr-ios-sdk#196]
I'm simply trying to add post processing to GCSCardboardView because my application is playing videos and has different modes of viewing which could be combined.

I've created two FBOs (one fbo for every eye just to see the difference), and it appears that fbo for the right eye doesn't get updated his texture whatsoever. Left eye is fine though, all post processing was applied successfully.

Here's a little part of my code just to see what's going on:

```
- (void)cardboardView:(GCSCardboardView *)cardboardView drawEye:(GCSEye)eye withHeadTransform:(GCSHeadTransform *)headTransform
{
    CGRect viewport = [headTransform viewportForEye:eye];
    glViewport(viewport.origin.x, viewport.origin.y, viewport.size.width, viewport.size.height);
    glScissor(viewport.origin.x, viewport.origin.y, viewport.size.width, viewport.size.height);
    
    GLKMatrix4 mvpMatrix = GLKMatrix4Translate(GLKMatrix4Identity, _panX, _panY, 0);
    if (eye == kGCSLeftEye)
    {
        mvpMatrix = GLKMatrix4Multiply(mvpMatrix, _leftEyeModelMatrix);
        //mvpMatrix.m20 = 0.355253f;
    }
    else
    {
        //mvpMatrix.m20 = -0.355253f;
    }
    
    if (eye == kGCSLeftEye)
    {
        mvpMatrix = leftMatrix;
        mvpMatrix = GLKMatrix4Translate(mvpMatrix, _panX, _panY, 0);
        mvpMatrix = GLKMatrix4Multiply(mvpMatrix, _leftEyeModelMatrix);
    }
    else if (eye == kGCSRightEye)
    {
        mvpMatrix = rightMatrix;
        mvpMatrix = GLKMatrix4Translate(mvpMatrix, _panX, _panY, 0);
    }
    
    //rotation
//    mvpMatrix = GLKMatrix4RotateZ(mvpMatrix, _roll);
    
    [self fillTextureForEye:eye];
    
    ZF_PostEffect *currentEffect;
    if (eye == kGCSLeftEye) {
        currentEffect = _leftEyePostEffect;
    }
    else
    {
        currentEffect = _rightEyePostEffect;
    }
    
    [currentEffect openFrameBuffer];
    
    [self renderTextureWithMVP:mvpMatrix eye:eye];
    [_background render];
    
    [currentEffect closeFrameBuffer];
    
    glBindFramebuffer(GL_FRAMEBUFFER, _cardboardViewFBO);
    [currentEffect render:eye];
    
    //glBindFramebuffer(GL_FRAMEBUFFER, 0);
}
```

As you can see I'm getting fbo of cardboard view (in willStartDrawing: method), I do all drawing in my fbos first, and then I'm applying cardboard View FBO in order to render the result.

How can I fix the issue with right eye post processing? It seems like it has something to do with glActiveTexture. By playing with that method I could render texture into right eye but it was all distorted and upside down.

Any advice? Thank you!

**Comment by sanjayc77** [comment]
Are you trying to have a different view/effect for each eye? That is not supported by GVRSDK.

**Comment by FigazzZ** [comment]
Thank you for your response! I know that it's not supported, I've developed my own solution for post processing.

Anyway I figured out the problem, so I can close this issue. Sorry for disturb!
