### ISSUE TITLE
SOS ！  videoView no image

### ISSUE THREAD

**Issue by gityoung** [googlevr/gvr-ios-sdk#20]
xcode7.3 ，SDK 0.7.2  
i create a GCSVideoView in my ViewController， everything is ok.
but when I change to VR （kGCSWidgetDisplayModeFullscreenVR） ,
the VR view donot have the image,also have the voice and control  
I cant find the error please help me

**Comment by sanjayc77** [comment]
What is the version of iOS for your device? Also are you clicking the cardboard button to change to VR mode?

**Comment by gityoung** [comment]
version :ML7K2CH/A   iOS 9.3 13E234  iphone 6S   
yes, I use the the cardboard original GCSVideoView button  change to VR  mode
but  i had  add some views in  GCSVideoView（load hud ,play progress）

**Comment by gityoung** [comment]
I dont use styleboard   ，Is this reason？

**Comment by dav-cz** [comment]
Do you still have this problem with a more recent version of the SDK (0.9.0 at time of writing)?

**Comment by sanjayc77** [comment]
Please consider switching to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit) and the updated VideoWidgetDemo app.
