### ISSUE TITLE
Header for gvr::AudioSurroundApi is missing

### ISSUE THREAD

**Issue by vogonistic** [googlevr/gvr-ios-sdk#203]
There is no declaration for the `gvr::AudioSurroundApi` in any of the header files. Looking at the library, there seems to be symbols for a C api, but not for the C++ wrapper class. Is there a problem with the API or was it left out by accident?

Documentation:
https://developers.google.com/vr/ios/ndk/reference/class/gvr/audio-surround-api

**Comment by jkammerl** [comment]
Thanks for the bug report. I can confirm that the corresponding header is missing. We'll fix it in the the next GVR iOS SDK release.
