### ISSUE TITLE
playableDuration as a property rather than a method

### ISSUE THREAD

**Issue by ghking** [googlevr/gvr-ios-sdk#205]
It would be great if playableDuration was a property rather than a method. That way it could be observed (for example in situations where you would like to provide a buffer indicator bar to the user) rather than having to explicitly call it on an interval. Thanks!

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRVideoView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. Take a look at the updated VideoWidgetDemo sample app. You provide your own instance of AVPlayer, which allows you to get the playableDuration as you want it.
