### ISSUE TITLE
videoview on pause when arrivinb

### ISSUE THREAD

**Issue by tibewww** [googlevr/gvr-ios-sdk#207]
Hi,

When arriving to the view controller, id' like my videoview to be in pause by default. 

AS I am starting to play the video via trigger of 2 buttons with a subview:

` @IBAction func videoButton(_ sender: UIButton) {
        
        if let button = self.videoVRView.subviews[1] as? UIButton {

            button.sendActions(for: .touchUpInside)
        }
        
    }
    
    @IBAction func cardboardButton(_ sender: UIButton) {
        
        if let button = self.videoVRView.subviews[2] as? UIButton {
            button.sendActions(for: .touchUpInside)
            
        }
        
    }
`

How is that possible ?

Thanks !

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRVideoView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. Take a look at the updated VideoWidgetDemo sample app.
