### ISSUE TITLE
Failed to load video: Operation Stopped

### ISSUE THREAD

**Issue by MohammadrezaZamanieh** [googlevr/gvr-ios-sdk#208]
why i get this error? 
i am playing video from url such below
self.OnlinePlayer.load(from: NSURL(string: path) as URL!)

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRVideoView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. Take a look at the updated VideoWidgetDemo sample app.
