### ISSUE TITLE
How to Show panorama images from URL 

### ISSUE THREAD

**Issue by parvesh3093** [googlevr/gvr-ios-sdk#209]
I have load panorama images from my server.

**Comment by sanjayc77** [comment]
Take a look at GVRKit's GVRImageRenderer: https://github.com/googlevr/gvr-ios-sdk/blob/master/Samples/GVRKit/GVRImageRenderer.h

You can easily add a function to initialize from a URL, using textureWithContentsOfURL: https://github.com/googlevr/gvr-ios-sdk/blob/master/Samples/GVRKit/GVRImageRenderer.mm#L30
