### ISSUE TITLE
loadfromUrl very slow - how to download, then play ?

### ISSUE THREAD

**Issue by tibewww** [googlevr/gvr-ios-sdk#210]
Hi All,

The player si amazing, works great on wifi. Otherwise, I have few video being call from Firebase which are around 150mb. It's impossible to play them on a 4G Connexion - it take ages to start it to play, and get very very slow.

IS there any trick to make if faster ?

Potentially, I know the App 'Within' has a "Download' Option - is there any possibility to achieve something similar ? ( Example, ON click of a button, start to 'download or buffer the video' and play start to play the video only when it's all 'download' or '100% buffered'), what is the best option you guys would recommend for that ?

Thanks for all the opinion :)

**Comment by sanjayc77** [comment]
Take a look at GVRKit (and the updated VideoWidgetDemo example). The video renderer is initialized with AVPlayer. This allows you to set it up however you wish and does not specify how to load the video: https://github.com/googlevr/gvr-ios-sdk/blob/master/Samples/GVRKit/GVRVideoRenderer.h#L25
