### ISSUE TITLE
ion::gfx::Renderer::GetGraphicsManager

### ISSUE THREAD

**Issue by sumanroy-sb** [googlevr/gvr-ios-sdk#211]
I have an app with content loaded into page view controllers. There are html, audio, video and VR pages separately. When a user is on a page with the VR player and they partially swipe to an adjacent page without moving to the other page ( as in the below image), the VR SDK is causing the app to crash on transitioning to full VR mode.

![Partial_Swipe](https://cloud.githubusercontent.com/assets/14902035/23219911/57d29ca2-f946-11e6-9e4c-bca174a097e1.PNG)

The crash debug trace is as below

![crash debug trace](https://cloud.githubusercontent.com/assets/14902035/23219947/76c3152e-f946-11e6-94d0-fb456015a8ce.png)

What is going on and how do I stop it from happening?

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRVideoView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. Take a look at the updated VideoWidgetDemo sample app.
