### ISSUE TITLE
Enable Bitcode

### ISSUE THREAD

**Issue by ecristerna** [googlevr/gvr-ios-sdk#212]
Is there a chance of getting the sdk with bitcode enabled, so we won't need to disable it from our project?

**Comment by apan06** [comment]
https://github.com/googlevr/gvr-ios-sdk/issues/8
https://github.com/googlevr/gvr-ios-sdk/issues/178
https://github.com/googlevr/gvr-ios-sdk/issues/194
@ecristerna - maybe in next release

**Comment by ecristerna** [comment]
yeah, that's what I read, but still no sign of it…

**Comment by sanjayc77** [comment]
Try again. 1.30 was launched a couple of days ago.

**Comment by ecristerna** [comment]
@sanjayc77 i'm only seeing 1.20.0 which was released on feb 1

**Comment by sanjayc77** [comment]
https://github.com/CocoaPods/Specs/blob/master/Specs/3/7/9/GVRSDK/1.30.0/GVRSDK.podspec.json#L134
