### ISSUE TITLE
Adding unity gaze pointer along with play, pause controls over GVRVideoView in iOS project?

### ISSUE THREAD

**Issue by balakrishnaJarugubelli** [googlevr/gvr-ios-sdk#218]
- I already have a working project, which is using GVRVideoView to play the VR Videos
- I would like to add controls() over the GVRVideoView with Gaze pointer and custom play, pause, seek bar options.

So, is it allowed to do any of the customisations on the GVRVideoView??

Please let us know your inputs on this???

**Comment by tibewww** [comment]
any luck with that ?

**Comment by balakrishnaJarugubelli** [comment]
Nope

**Comment by sanjayc77** [comment]
Take a look at GVRKit: https://github.com/googlevr/gvr-ios-sdk/blob/master/Samples/GVRKit (also available as a Cocoapod). The VideoWidgetDemo shows adding a gaze (reticle) and play/pause video in VR: https://github.com/googlevr/gvr-ios-sdk/blob/master/Samples/VideoWidgetDemo/VideoPlayerViewController.m#L67
