### ISSUE TITLE
Loading GVRSDK images from URL

### ISSUE THREAD

**Issue by imagineeringio** [googlevr/gvr-ios-sdk#219]
Hi all,
Appreciate this is not really and issue, but more of a question to see if its possible. 
Using the Ray Wenderlich GVRSDK example, is it possible load the image from a URL?

```
@IBOutlet weak var imageVRView: GVRPanoramaView!
    @IBOutlet weak var videoVRView: GVRVideoView!
    @IBOutlet weak var videoLabel: UILabel!
    
    enum Media {
        static var photoArray = ["image1.jpg", "image2.png", "image3.png"]
        static let videoURL = "https://s3.amazonaws.com/ray.wenderlich/elephant_safari.mp4"
    }
    var currentView: UIView?
    var currentDisplayMode = GVRWidgetDisplayMode.embedded
    
  override func viewDidLoad() {
    super.viewDidLoad()
    imageVRView.isHidden = true
    imageVRView.load(UIImage(named: Media.photoArray.first!),
                     of: GVRPanoramaImageType.mono)
```

Thanks so much for any help.

**Comment by tibewww** [comment]
Hi imegineeringio, did you find a way to call image from URL ?

Doesn't seem to work on my side :)

**Comment by imagineeringio** [comment]
Hey, I think I might have done.
Let me check my past project and see if I can find the solution.

Thanks for reaching out.
Cheers

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRPanoramaView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. Take a look at the updated Panorama sample app.
