### ISSUE TITLE
Expose a method [- recenterHeadTracker] in GVRCardboardView

### ISSUE THREAD

**Issue by stephanecopin** [googlevr/gvr-ios-sdk#220]
This method is available in the NDK as [gvr_recenter_tracking(gvr_context *gvr)](https://developers.google.com/vr/ios/ndk/reference/group/headtracking#group___headtracking_1gac2313522b1dc5dc66bff87b9b2fcd070) and in the Android SDK in `GvrView` as [public void recenterHeadTracker()](https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/GvrView.html#recenterHeadTracker()), but is not available in the iOS SDK.
Could it be exposed so we could call it without having to resort to using the NDK?

**Comment by achuvm** [comment]
+1 here

As a workaround, is there any way to get the gvr_context from a GVRCardboardView so we can access the NDK methods? (I'm fine using Objective-C++).

**Comment by sanjayc77** [comment]
Thanks. We are trying to address this in an upcoming release. Stay tuned.

**Comment by stephanecopin** [comment]
@sanjayc77 Thanks! Can't wait for the new release :)

**Comment by sanjayc77** [comment]
Take a look at GVRKit: https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit (also available as a cocoapod). It's GVRRenderer class provides resetting the head pose: https://github.com/googlevr/gvr-ios-sdk/blob/master/Samples/GVRKit/GVRRenderer.h#L85
