### ISSUE TITLE
GVRVideoView.duration = NaN

### ISSUE THREAD

**Issue by deltatre-team-mobile** [googlevr/gvr-ios-sdk#222]
Hi,
videoView.duration is NaN in the didUpdatePosition callback when i try to play a 360 HLS live stream. If i try to play the same stream directly with AVPlayer i get the right duration that increases during live progress. 
Using the same approach in Android Vr sdk works just fine: when I call the
VrVideoView.getDuration() function i get the right duration that increases correctly.
I need to support both VOD and Live 360 videos with DVR. Since I cannot access directly to the current AVPlayerItem that is playing, I cannot know if the player is currently at live point. 
Where are you getting that duration value from? 

Thanks in advance.

**Comment by sanjayc77** [comment]
Is there a publicly available sample 360 HLS stream we can use to test against? Thanks.

**Comment by deltatre-team-mobile** [comment]
Hi,
you can easily test it by modifying 2 lines from the inner playlist of any HLS video  (change the playlist if you have access to it or use some kind of autoresponder and a proxy e.g. Fiddler or Charles).
To make AVPlayer read the stream as a live stream you can change the 
`#EXT-X-PLAYLIST-TYPE:VOD` line from the start of the playlist to 
`#EXT-X-PLAYLIST-TYPE:EVENT` (or remove it completely)
and remove the `#EXT-X-ENDLIST` line from the end of it.
Alternatively I can send you a private email with a link to a live 360 test stream if you provide me a private address.

In the meantime i made some tests to reverse engineer the cause of the bug and i think i found a possible solution:
I think you are reading the property 
`[AVPlayer currentItem].asset.duration`
this property will return "NaN" in case of a not closed playlist (live case)
instead you could use the seekableTimeRanges property that will always return the correct value for both VOD and live streams. 
Something like this:
`NSArray *skr = [[[AVPlayer currentItem] seekableTimeRanges] copy];`
`CMTime correctDuration = [[skr lastObject] CMTimeRangeValue].duration;`
should always return the correct value.

**Comment by sanjayc77** [comment]
Can you give GVRKit video renderer a try: https://github.com/googlevr/gvr-ios-sdk/blob/master/Samples/GVRKit/GVRVideoRenderer.h ? It allows you to pass in an instance of AVPlayer.

Closing the issue. Feel free to re-open if you need to.
