### ISSUE TITLE
crash when calling [GVRVideoView duration] inside didUpdatePosition callback

### ISSUE THREAD

**Issue by deltatre-team-mobile** [googlevr/gvr-ios-sdk#223]
Hi,
if i try to call the duration or the playableDuration methods inside the callback
`- (void)videoView:(GVRVideoView *)videoView didUpdatePosition:(NSTimeInterval)position;`
i get a lot of SIGABRT crash. 
It can be reproduced easily using an HLS live stream (360 or not).
I partially solved this using an async task but it's not an elegant solution and lead to many concurrent issues in my player. Can you look into this issue?
Thanks in advance

**Comment by sanjayc77** [comment]
Can you give GVRKit video renderer a try: https://github.com/googlevr/gvr-ios-sdk/blob/master/Samples/GVRKit/GVRVideoRenderer.h ? It is provided as sample code, so you can easily debug the issue.

This is also released as GVRKit cocoapod. See the updated VideoWidgetDemo sample. GVRVideoView will be deprecated in a future release.

Closing the issue. Feel free to re-open if you need to.
