### ISSUE TITLE
com.google.cardboard.RenderThread (22) EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by Sadoge** [googlevr/gvr-ios-sdk#224]
I have been having this crash a few times already. I use the gvr for rendering out 360 images inside a swipable card. Any ideas what this might be caused by?

**Comment by sanjayc77** [comment]
Can you attach the stack trace?

**Comment by keakalamudo** [comment]
@sanjayc77 

Crashed: com.google.cardboard.RenderThread
0  AGXGLDriver                    0x19d3c4c98 (null)
1  AGXGLDriver                    0x19d35d440 (null)
2  AGXGLDriver                    0x19d37afe4 gldUpdateDispatch
3  GLEngine                       0x19db612b8 gleDoDrawDispatchCoreES2
4  GLEngine                       0x19db38124 gleDrawArraysOrElements_Entries_Body
5  GLEngine                       0x19db3667c glDrawElements_ES2Exec
6  project-vr                     0x100201e80 ion::gfx::Renderer::ResourceBinder::DrawIndexedShape(ion::gfx::Shape const&, ion::gfx::IndexBuffer const&, ion::gfx::GraphicsManager*) + 51240
7  project-vr                     0x100201644 ion::gfx::Renderer::ResourceBinder::DrawNode(ion::gfx::Node const&, ion::gfx::GraphicsManager*) + 49132
8  project-vr                     0x10020168c ion::gfx::Renderer::ResourceBinder::DrawNode(ion::gfx::Node const&, ion::gfx::GraphicsManager*) + 49204
9  project-vr                     0x10020168c ion::gfx::Renderer::ResourceBinder::DrawNode(ion::gfx::Node const&, ion::gfx::GraphicsManager*) + 49204
10 project-vr                     0x10020168c ion::gfx::Renderer::ResourceBinder::DrawNode(ion::gfx::Node const&, ion::gfx::GraphicsManager*) + 49204
11 project-vr                     0x100200d20 ion::gfx::Renderer::ResourceBinder::DrawScene(ion::base::SharedPtr<ion::gfx::Node> const&, std::__1::bitset<35ul> const&, ion::gfx::ShaderProgram*) + 46792
12 project-vr                     0x100200b3c ion::gfx::Renderer::DrawScene(ion::base::SharedPtr<ion::gfx::Node> const&) + 46308
13 project-vr                     0x100150960 vr::WidgetRenderer::RenderFrame() + 162788
14 project-vr                     0x10005b8f0 -[GVRWidgetView nativeRenderFrame] + 4295899376
15 project-vr                     0x10005d174 -[GVRWidgetView render:] + 4295905652
16 project-vr                     0x100053b44 -[GVRWeakRenderTarget render:] + 4295867204
17 project-vr                     0x100054c14 -[GVRRenderLoop updateWithDisplayLink:] + 4295871508
18 QuartzCore                     0x18b9a6600 CA::Display::DisplayLinkItem::dispatch(unsigned long long) + 44
19 QuartzCore                     0x18b9a64b0 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 436
20 IOKit                          0x188a03dd4 IODispatchCalloutFromCFMessage + 372
21 CoreFoundation                 0x18872d958 __CFMachPortPerform + 180
22 CoreFoundation                 0x188745adc __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
23 CoreFoundation                 0x18874527c __CFRunLoopDoSource1 + 436
24 CoreFoundation                 0x188742d90 __CFRunLoopRun + 1752
25 CoreFoundation                 0x188672d94 CFRunLoopRunSpecific + 424
26 CoreFoundation                 0x1886bf9a0 CFRunLoopRun + 112
27 Foundation                     0x18928a2c8 __NSThread__start__ + 996
28 libsystem_pthread.dylib        0x18785975c _pthread_body + 240
29 libsystem_pthread.dylib        0x18785966c _pthread_body + 282
30 libsystem_pthread.dylib        0x187856d84 thread_start + 4

**Comment by keakalamudo** [comment]
Hey any updates? @sanjayc77

**Comment by sanjayc77** [comment]
This should be addressed in the next release. Stay tuned.

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRPanoramaView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod.
