### ISSUE TITLE
ld: library not found for -lCardboardSDK_arm64

### ISSUE THREAD

**Issue by willian-sisinfo** [googlevr/gvr-ios-sdk#226]
Hi, I'm starting a new project using the Panorama Viewer. Added the GVRSDK in my Pod file, opened the workspace file and when I try to build the project, I get this error. Already tried to execute a pod deintegrate and pod install.

```
ld: warning: directory not found for option '-L/Users/willian/Documents/XCode Projects/iP-360/Pods/build/Debug-iphoneos'
ld: library not found for -lCardboardSDK_arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by asimparvez** [comment]
Hi, did you find a solution for this? I am having the same issue.
