### ISSUE TITLE
In Xcode Version 8.3 (8E162) clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by boluobanana** [googlevr/gvr-ios-sdk#229]
Hi,
I clone the project and run `pod update` in terminal  to add the CardboardSDK CocoaPod in VideoWidgetDemo project.
Then I try to run the VideoWidgetDemo project in Xcode, I get an issues 

> ld: warning: directory not found for option '-L/Users/username/Library/Developer/Xcode/DerivedData/VideoWidgetDemo-afiqijliusxrirdgqpltgejdxhwp/Build/Products/Debug-iphoneos/GTMSessionFetcher'

> ld: warning: directory not found for option '-L/Users/username/Library/Developer/Xcode/DerivedData/VideoWidgetDemo-afiqijliusxrirdgqpltgejdxhwp/Build/Products/Debug-iphoneos/GoogleToolboxForMac'

> Apple Mach-O Linker (ld) Error Group
             clang: error: linker command failed with exit code 1 (use -v to see invocation)
  
But last time I opened the project in Version 7.x(i forget the version) Xcode. I didn't get this issues.
Can anybody help me?

Thank you !

**Comment by jonflanders** [comment]
you have to run "pod install" to install the SDK - but then you will get another compiler error that I have already reported.

**Comment by boluobanana** [comment]
Hi @jonflanders, I solved my issue from [stackoverflow](http://stackoverflow.com/questions/40358719/framework-not-found-googletoolboxformac.)
I didn't notice the line

> [!] Please close any current Xcode sessions and use `VideoWidgetDemo.xcworkspace` for this project from now on

I still opened the **VideoWidgetDemo.xcodeproj** by mistake.

So, I opened the **VideoWidgetDemo.xcworkspace** and it worked fine.
