### ISSUE TITLE
Add way to exit GVRCardboardView stereo programmatically

### ISSUE THREAD

**Issue by vogonistic** [googlevr/gvr-ios-sdk#230]
When showing content in stereo, dismissing the UIViewController that contains the GVRCardboardView doesn't exit the experience. The SDK seems to have created a new window and when I stop calling render it just freezes on the last frame.

**Comment by sanjayc77** [comment]
Set vrModeEnabled property to false. https://developers.google.com/vr/ios/reference/interface_g_v_r_cardboard_view#a9d184749c1056438ed60c94b938c725c
