### ISSUE TITLE
Call Panorama image from URL ??

### ISSUE THREAD

**Issue by tibewww** [googlevr/gvr-ios-sdk#233]
Hi All,

I'm trying to call the image in the PanoarmaViewer frmo an URL but it's not working . . .

I'm using this: 

` imageVRView.loadImage(URL(string: "\(postslogin[selectedIndexPath].link)"), ofType: GVRPanoramaImageType.mono)
`

But I get a "Cannot subscripe a value of type 'inout[Post]' aka 'inout Array<Posts>') error on that line . .. . 

to play video i am using:

`        videoVRView.load(from: URL(string: "\(postslogin[selectedIndexPath].link)"))`

which works perfectly ! Anyone able to help me ? It will be wonderfull

thank you

**Comment by sanjayc77** [comment]
GVRPanoramaView is deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod.
