### ISSUE TITLE
GVRVideoView with AirPlay

### ISSUE THREAD

**Issue by deltatre-team-mobile** [googlevr/gvr-ios-sdk#237]
It's impossible to avoid casting 360 video if a user enable AirPlay screen casting.
I would like to keep the 360 video in the smarphone, even if the user change the AirPlay setting from the device.
Since it's not possible to access to the AVPlayer instance of GVRVideoView I cannot change the `allowsExternalPlayback` property of AVPlayer to avoid the screen casting.
[Here](https://developer.apple.com/reference/avfoundation/avplayer/1387441-allowsexternalplayback) the official documentation to disable the external playback. 
Alternately you could expose a property to change that property.

Thanks

**Comment by sanjayc77** [comment]
Take a look at GVRKit cocoapod, also released as source code in GVRSDK samples. It allows passing in AVPlayer instance to render video. You have full control over AVPlayer instance.
