### ISSUE TITLE
GVRSDK - above 0.8.0, unable to play specific hls stream, while it plays fine with safari

### ISSUE THREAD

**Issue by ashishbitcot** [googlevr/gvr-ios-sdk#238]
https://storage.googleapis.com/encode-experiments/hls_exp/hls/indoor_2M.m3u8
This plays with 0.8.5 version, though looks very choppy.
@nathanmartz 
@sanjayc77

**Comment by sanjayc77** [comment]
Just updated to 1.80. This includes GVRKit cocoapod, which is also provided as sample code: See: https://github.com/googlevr/gvr-ios-sdk/blob/master/Samples/GVRKit/GVRVideoRenderer.h and the updated https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/VideoWidgetDemo sample.

GVRVideoRenderer lets you provide your own AVPlayer, which you can control yourself.

You should migrate away from GVRVideoView, as that would be deprecated in a future release.
