### ISSUE TITLE
Load VR video multiple times

### ISSUE THREAD

**Issue by lavorato** [googlevr/gvr-ios-sdk#239]
Hello all. I've some implementation of GoogleVR for iOS using Swift and it working well except from the fact that when I play the video multiple times the Transition View shows only the first time. How could I force to always show this transition view?

**Comment by pbendersky** [comment]
@lavorato if you don't mind sharing... I can't seem to play the same video again. I transition to the view controller where I create the `GVRVideoView` and create everything on `viewWillAppear`, but the second time I enter that VC, I get a black screen.

**Comment by sanjayc77** [comment]
Just updated to 1.80. This includes updated GVROverlayView , which controls the transition view. Now it also allows you to hide/show the transition view.
