### ISSUE TITLE
Unknown class GVRVideoView in Interface Builder file.

### ISSUE THREAD

**Issue by micsur** [googlevr/gvr-ios-sdk#24]
A few hours ago SDK for iOS has been changed. I have tried to move forward with this new version and this error appears once I've tried to run the app.
Thanks!

**Comment by GraphicSound** [comment]
I got the same problem. Tried every method I've found, no luck.

**Comment by GraphicSound** [comment]
![b633388b-a453-4ef0-b658-7ec80c7cd6af](https://cloud.githubusercontent.com/assets/6771105/15422433/25013368-1eab-11e6-80cb-8555671689ee.png)

**Comment by sanjayc77** [comment]
The pod got renamed to GVRSDK from CardboardSDK. You will have to recreate the project. Something like 'pod deintegrate' followed by 'pod update' might do the trick.
