### ISSUE TITLE
GVR SDK  include standard  zlib 

### ISSUE THREAD

**Issue by poetryfar** [googlevr/gvr-ios-sdk#240]
As you see, GVR SDK  include  zlib(https://github.com/madler/zlib) ,  and did not change  functions name. I  find that  many link error likes "duplicate symbol _inflate_copyright in:blablabla/xx.a/inftrees.o  blablabal/libGVRSDK.a/inftrees.o"。

It's could be better  change  functions name (symbol) before release your  SDK.

**Comment by sanjayc77** [comment]
We specify Zlib as a Cocoapod dependency now: https://github.com/CocoaPods/Specs/blob/master/Specs/3/7/9/GVRSDK/1.100.0/GVRSDK.podspec.json#L25

Using Cocoapods to managing zlib inclusion in your app should address this issue.
