### ISSUE TITLE
Can't Observe Player Events

### ISSUE THREAD

**Issue by ElizaSapir** [googlevr/gvr-ios-sdk#241]
Hey,

Wanted to use your SDK then found that I can't observe relevant events and know when player is playable, playing, paused, failed.

Are you using AVPlayer? and is there an option to set my own avplayer via your API?

Thanks,

Eliza

**Comment by OrenMe** [comment]
I think this is a valid use case.
How can analytics pick up on QoS? how can custom UI be fitted when there's no indication for playback metrics.
Would love to hear if someone has an idea.

Thanks.

**Comment by sanjayc77** [comment]
Just updated to 1.80. This includes GVRKit cocoapod, which is also provided as sample code: See: https://github.com/googlevr/gvr-ios-sdk/blob/master/Samples/GVRKit/GVRVideoRenderer.h and the updated https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/VideoWidgetDemo sample.

GVRVideoRenderer lets you provide your own AVPlayer, which you can control yourself.

You should migrate away from GVRVideoView, as that would be deprecated in a future release.

**Comment by ElizaSapir** [comment]
Thanks! @sanjayc77 the sample works for me BUT there is an issue when trying to import GVRKit into swift project.

Do you have a sample that combines GVRKit and Swift?

Thanks!

**Comment by sanjayc77** [comment]
Unfortunately, our samples are still ObjC.

GVRKit is also released as sample code, which you can drop in your project directly:
https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit
