### ISSUE TITLE
Stream a video to the SDK from YouTube

### ISSUE THREAD

**Issue by DanBurkhardt** [googlevr/gvr-ios-sdk#246]
Hello, 

This framework does not allow for a content stream from YouTube. I find this really surprising both because Google owns YouTube, and also because YouTube is probably the biggest repositories of free, public VR content on the internet. 

When is this SDK going to support YouTube content streams?

**Comment by nathanmartz** [comment]
We have no plans to support white-label streaming of YT content outside of the YT app.

**Comment by DanBurkhardt** [comment]
That is a really surprising and unfortunate situation to be in. Google is a company that has clearly gotten so big that there is infighting between VR folks and the literal largest source of VR content on the internet, their own platform, YouTube. This is a clearly lacking feature and honestly pure common sense. It's a shame.
