### ISSUE TITLE
How to switch to default viewer?

### ISSUE THREAD

**Issue by iron93** [googlevr/gvr-ios-sdk#247]
i cant reset my app even reinstall it

**Comment by sanjayc77** [comment]
Not sure I understand what you are asking here. Are you trying to reset (un-pair) the Cardboard viewer programmatically? We don't support that, but we do allow setting a default viewer IF one was not paired before. See the documentation for [GVRCardboardView setViewerParamsFromUrl:]: 
https://developers.google.com/vr/ios/reference/interface_g_v_r_cardboard_view.html#a053783e64400204a31340fe1a1da6303
