### ISSUE TITLE
GVRVideoView, seekTo has too low timescale

### ISSUE THREAD

**Issue by markusekblad** [googlevr/gvr-ios-sdk#252]
When trying to seek to a time with milliseconds, CMTimeMake shows a warning for using too low timescale

CMTimeMakeWithSeconds(30.229 seconds, timescale 1): warning: error of -0.229 introduced due to very low timescale

It makes it difficult to try to sync the video to an external audio player.

**Comment by sanjayc77** [comment]
Just updated to 1.80. This includes GVRKit cocoapod, which is also provided as sample code: See: https://github.com/googlevr/gvr-ios-sdk/blob/master/Samples/GVRKit/GVRVideoRenderer.h and the updated https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/VideoWidgetDemo sample.

GVRVideoRenderer lets you provide your own AVPlayer, which you can control yourself.

You should migrate away from GVRVideoView, as that would be deprecated in a future release.
