### ISSUE TITLE
Adding multisampling support for GVR

### ISSUE THREAD

**Issue by drinkius** [googlevr/gvr-ios-sdk#255]
Hello,

In our app we'd like to add multisampling support, but unfortunately GVR iOS SDK currently doesn't provide this setting by default. Is it possible to add a MSAA flag to the next release of SDK?

**Comment by sanjayc77** [comment]
Thanks for your comment. We will take it into account for future releases of GVR SDK.

**Comment by sanjayc77** [comment]
You should switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). VR View and Cardboard View API are now deprecated.

Look at Panorama sample app on how to use it. You also have GVRTextureRenderer and GVRImageRenderer to implement MSAA (including rolling out your own renderer).

**Comment by drinkius** [comment]
Thanks a lot, will take a look at GVRKit, seems to be a great update
