### ISSUE TITLE
Expose EAGLContext context to use in a sharegroup

### ISSUE THREAD

**Issue by drinkius** [googlevr/gvr-ios-sdk#256]
In our application we need to process graphics from different threads and to do so without rendering lags we'd need to create a context sharegroup for which we'd need GVR context to be exposed outside the library. Is it possible to do so in the upcoming releases? 

What we are trying to do is basically described here:

https://developer.apple.com/library/content/qa/qa1612/_index.html

**Comment by sanjayc77** [comment]
This is something we are looking into. Stay tuned.
