### ISSUE TITLE
Any way to change orientation of GVRCardboardView?

### ISSUE THREAD

**Issue by KhomenokV** [googlevr/gvr-ios-sdk#260]
Currently GVRCardboardView is forced to work in Landscape Right orientation when our application is working in Landscape Left for specific reasons. Is there a way to make GVRCardboardView work in Landscape Left?

**Comment by sanjayc77** [comment]
Sorry, this is hard coded for various reasons in our SDK. Hopefully, this is something we can consider for a future release. Stay tuned.
