### ISSUE TITLE
[CR] A possibility to set default cardboard profile

### ISSUE THREAD

**Issue by KhomenokV** [googlevr/gvr-ios-sdk#262]
It would be nice to have a possibility to set default cardboard profile for application which will be available from the box, so the user is not forced to go to cardboard settings and capture QR code for it. Is this possible or in plans? Or it will not be implemented at all?

**Comment by sanjayc77** [comment]
Yes: https://developers.google.com/vr/ios/reference/interface_g_v_r_cardboard_view.html#a053783e64400204a31340fe1a1da6303
