### ISSUE TITLE
HLS seek then black screen

### ISSUE THREAD

**Issue by levi0424** [googlevr/gvr-ios-sdk#265]
Playback HLS url when i seek, the screen will be the whole black out, 
but still have sound playback.

This library has not been updated for some time. When will it be updated?
Thanks

**Comment by sanjayc77** [comment]
Just updated to 1.80. This includes GVRKit cocoapod, which is also provided as sample code: See: https://github.com/googlevr/gvr-ios-sdk/blob/master/Samples/GVRKit/GVRVideoRenderer.h and the updated https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/VideoWidgetDemo sample.

You should migrate away from GVRVideoView, as that would be deprecated in a future release.
