### ISSUE TITLE
Pod GVRKit fail

### ISSUE THREAD

**Issue by jiazhengwang** [googlevr/gvr-ios-sdk#266]
hello ,i am poding GVRKit , but it reminder me of Unable to find a specification for `GVRKit`

**Comment by sanjayc77** [comment]
https://github.com/CocoaPods/Specs/tree/master/Specs/7/3/e/GVRKit/1.80.0

**Comment by sanjayc77** [comment]
Also, if you want to drop the source code directly into your project: https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit

**Comment by parveshmishra** [comment]
I was tried the same but its not accessible the GVRKit folder
