### ISSUE TITLE
`hidesTransitionView = true` has no effect on GVRVideoView

### ISSUE THREAD

**Issue by jamezilla** [googlevr/gvr-ios-sdk#270]
GVRVideoView still shows the transition view even when `hidesTransitionView = true`.

Versions:
```
PODS:
  - GoogleToolboxForMac/Defines (2.1.0)
  - GoogleToolboxForMac/Logger (2.1.0):
    - GoogleToolboxForMac/Defines (= 2.1.0)
  - GTMSessionFetcher/Core (1.1.6)
  - GVRSDK (1.80.0):
    - GoogleToolboxForMac/Logger (= 2.1.0)
    - GTMSessionFetcher/Core (= 1.1.6)
```

Also broken in 1.70

Repro project:
https://github.com/jamezilla/SimpleVR

**Comment by sanjayc77** [comment]
GVRVideoView will be deprecated in the near future. You should move to GVRKit instead: https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit
