### ISSUE TITLE
ion::gfx::Renderer::ShaderInputRegistryResource::UniformStack::Pop() - Crash

### ISSUE THREAD

**Issue by keakalamudo** [googlevr/gvr-ios-sdk#276]
Hi @sanjayc77, team, 

ion::gfx::Renderer::ShaderInputRegistryResource::UniformStack::Pop() /
com.google.cardboard.RenderThread. We are not too sure what is causing this.

#8. Crashed: com.google.cardboard.RenderThread
0  project-vr                     0x10041ca98 ion::gfx::Renderer::ShaderInputRegistryResource::UniformStack::Pop() + 88700
1  project-vr                     0x10041558c ion::gfx::Renderer::ResourceBinder::PopUniforms(ion::base::AllocVector<ion::gfx::Uniform> const&) + 58736
2  project-vr                     0x10041558c ion::gfx::Renderer::ResourceBinder::PopUniforms(ion::base::AllocVector<ion::gfx::Uniform> const&) + 58736
3  project-vr                     0x100414720 ion::gfx::Renderer::ResourceBinder::DrawNode(ion::gfx::Node const&, ion::gfx::GraphicsManager*) + 55044
4  project-vr                     0x1004146b8 ion::gfx::Renderer::ResourceBinder::DrawNode(ion::gfx::Node const&, ion::gfx::GraphicsManager*) + 54940
5  project-vr                     0x1004146b8 ion::gfx::Renderer::ResourceBinder::DrawNode(ion::gfx::Node const&, ion::gfx::GraphicsManager*) + 54940
6  project-vr                     0x1004146b8 ion::gfx::Renderer::ResourceBinder::DrawNode(ion::gfx::Node const&, ion::gfx::GraphicsManager*) + 54940
7  project-vr                     0x100413d54 ion::gfx::Renderer::ResourceBinder::DrawScene(ion::base::SharedPtr<ion::gfx::Node> const&, std::__1::bitset<35ul> const&, ion::gfx::ShaderProgram*) + 52536
8  project-vr                     0x100413b70 ion::gfx::Renderer::DrawScene(ion::base::SharedPtr<ion::gfx::Node> const&) + 52052
9  project-vr                     0x1002edee8 vr::WidgetRenderer::RenderFrame() + 45560
10 project-vr                     0x100112cd0 -[GVRWidgetView nativeRenderFrame] + 4309920976
11 project-vr                     0x100114554 -[GVRWidgetView render:] + 4309927252
12 project-vr                     0x10010a848 -[GVRWeakRenderTarget render:] + 4309887048
13 project-vr                     0x10010b918 -[GVRRenderLoop updateWithDisplayLink:] + 4309891352
14 QuartzCore                     0x187cdefd4 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 672
15 IOKit                          0x18407e30c IODispatchCalloutFromCFMessage + 392
16 CoreFoundation                 0x183da2080 __CFMachPortPerform + 188
17 CoreFoundation                 0x183dbc9dc __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
18 CoreFoundation                 0x183dbc0e0 __CFRunLoopDoSource1 + 440
19 CoreFoundation                 0x183db9bb4 __CFRunLoopRun + 2196
20 CoreFoundation                 0x183cda2d8 CFRunLoopRunSpecific + 436
21 CoreFoundation                 0x183d2912c CFRunLoopRun + 116
22 Foundation                     0x184803860 __NSThread__start__ + 996
23 libsystem_pthread.dylib        0x183a4032c _pthread_body + 308
24 libsystem_pthread.dylib        0x183a401f8 _pthread_body + 310
25 libsystem_pthread.dylib        0x183a3ec38 thread_start + 4

--

#0. com.apple.main-thread
0  CoreUI                         0x18b218658 CUIFillCARKeyArrayForRenditionKey + 144
1  CoreUI                         0x18b218c34 CUICopyKeySignatureWithPrefix + 124
2  CoreUI                         0x18b260740 -[CUIStructuredThemeStore copyKeySignatureForKey:withBytesNoCopy:length:] + 60
3  CoreUI                         0x18b249178 -[CUIMutableStructuredThemeStore renditionWithKey:] + 64
4  CoreUI                         0x18b24911c -[CUIMutableStructuredThemeStore canGetRenditionWithKey:] + 20
5  CoreUI                         0x18b28c40c -[CUICatalog _resolvedRenditionKeyFromThemeRef:withBaseKey:scaleFactor:deviceIdiom:deviceSubtype:displayGamut:layoutDirection:sizeClassHorizontal:sizeClassVertical:memoryClass:graphicsClass:graphicsFallBackOrder:iconSizeIndex:] + 2192
6  CoreUI                         0x18b28bb78 -[CUICatalog _resolvedRenditionKeyForName:scaleFactor:deviceIdiom:deviceSubtype:displayGamut:layoutDirection:sizeClassHorizontal:sizeClassVertical:memoryClass:graphicsClass:graphicsFallBackOrder:withBaseKeySelector:] + 308
7  CoreUI                         0x18b287a2c -[CUICatalog _imageWithName:scaleFactor:deviceIdiom:deviceSubtype:displayGamut:layoutDirection:sizeClassHorizontal:sizeClassVertical:memoryClass:graphicsClass:graphicsFallBackOrder:] + 184
8  CoreUI                         0x18b287b8c -[CUICatalog imageWithName:scaleFactor:deviceIdiom:deviceSubtype:displayGamut:layoutDirection:sizeClassHorizontal:sizeClassVertical:memoryClass:graphicsClass:graphicsFallBackOrder:] + 156
9  CoreUI                         0x18b287868 -[CUICatalog imageWithName:scaleFactor:deviceIdiom:deviceSubtype:displayGamut:layoutDirection:sizeClassHorizontal:sizeClassVertical:] + 160
10 UIKit                          0x18dec7ab0 -[UIImageAsset imageWithTraitCollection:] + 628
11 UIKit                          0x18dec8d98 -[_UIPathLazyImageAsset imageWithTraitCollection:] + 400
12 UIKit                          0x18d5d7b50 -[UIImageView _resolveImageForTrait:] + 684
13 UIKit                          0x18d5d782c -[UIImageView traitCollectionDidChange:] + 84
14 UIKit                          0x18d4f6c80 -[UIView _wrappedProcessTraitCollectionDidChange:forceNotification:] + 136
15 UIKit                          0x18d4f6d40 -[UIView _wrappedProcessTraitCollectionDidChange:forceNotification:] + 328
16 UIKit                          0x18d4f6d40 -[UIView _wrappedProcessTraitCollectionDidChange:forceNotification:] + 328
17 UIKit                          0x18d4f6d40 -[UIView _wrappedProcessTraitCollectionDidChange:forceNotification:] + 328
18 UIKit                          0x18dd0ed28 -[UIView(AdditionalLayoutSupport) _withUnsatisfiableConstraintsLoggingSuspendedIfEngineDelegateExists:] + 116
19 UIKit                          0x18d4f6ff0 -[UIView _processDidChangeRecursivelyFromOldTraits:toCurrentTraits:forceNotification:] + 140
20 UIKit                          0x18d21ff84 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1132
21 QuartzCore                     0x187df10b4 -[CALayer layoutSublayers] + 184
22 QuartzCore                     0x187df5194 CA::Layer::layout_if_needed(CA::Transaction*) + 332
23 QuartzCore                     0x187df0fd0 -[CALayer layoutIfNeeded] + 228
24 UIKit                          0x18d59f320 -[UIViewController window:willAnimateRotationToInterfaceOrientation:duration:newSize:] + 436
25 UIKit                          0x18d5a3d48 __95-[UIViewController(AdaptiveSizing) _window:viewWillTransitionToSize:withTransitionCoordinator:]_block_invoke.3587 + 44
26 UIKit                          0x18d30b530 -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:] + 268
27 UIKit                          0x18d30b398 -[_UIViewControllerTransitionContext __runAlongsideAnimations] + 188
28 UIKit                          0x18d9e2760 __58-[_UIWindowRotationAnimationController animateTransition:]_block_invoke_2 + 356
29 UIKit                          0x18d5088a4 +[UIView(Internal) _performBlockDelayingTriggeringResponderEvents:] + 220
30 UIKit                          0x18d9e24b8 __58-[_UIWindowRotationAnimationController animateTransition:]_block_invoke + 140
31 UIKit                          0x18d2575c0 +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:] + 620
32 UIKit                          0x18d26dd68 +[UIView(UIViewAnimationWithBlocks) animateWithDuration:delay:options:animations:completion:] + 108
33 UIKit                          0x18d9e2374 -[_UIWindowRotationAnimationController animateTransition:] + 484
34 UIKit                          0x18d4dcb28 -[UIWindow _rotateToBounds:withAnimator:transitionContext:] + 624
35 UIKit                          0x18d4de438 -[UIWindow _rotateWindowToOrientation:updateStatusBar:duration:skipCallbacks:] + 1232
36 UIKit                          0x18d29f024 -[UIWindow _setRotatableClient:toOrientation:updateStatusBar:duration:force:isRotating:] + 544
37 UIKit                          0x18d29eda0 -[UIWindow _setRotatableViewOrientation:updateStatusBar:duration:force:] + 128
38 UIKit                          0x18d295e50 __57-[UIWindow _updateToInterfaceOrientation:duration:force:]_block_invoke + 124
39 UIKit                          0x18d223e00 -[UIWindow _updateToInterfaceOrientation:duration:force:] + 484
40 CoreFoundation                 0x183da612c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
41 CoreFoundation                 0x183da56cc _CFXRegistrationPost + 420
42 CoreFoundation                 0x183da5430 ___CFXNotificationPost_block_invoke + 60
43 CoreFoundation                 0x183e229f4 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1408
44 CoreFoundation                 0x183cdc3e0 _CFXNotificationPost + 380
45 Foundation                     0x1846fc498 -[NSNotificationCenter postNotificationName:object:userInfo:] + 68
46 UIKit                          0x18d223904 -[UIDevice setOrientation:animated:] + 324
47 Foundation                     0x18471f780 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 272
48 project-vr                     0x1000cc9cc static AppUtility.lockOrientation(UIInterfaceOrientationMask, andRotateTo : UIInterfaceOrientation) -> () (AppDelegate.swift:130)
49 project-vr                     0x1000aef24 ContentDetailVC.viewWillAppear(Bool) -> () (ContentDetailVC.swift:71)
50 project-vr                     0x1000af204 @objc ContentDetailVC.viewWillAppear(Bool) -> () (ContentDetailVC.swift)
51 UIKit                          0x18d23b5bc -[UIViewController _setViewAppearState:isAnimating:] + 628
52 UIKit                          0x18d23b330 -[UIViewController __viewWillAppear:] + 156
53 UIKit                          0x18d3a7ee0 -[UINavigationController _startCustomTransition:] + 1332
54 UIKit                          0x18d2c9e04 -[UINavigationController _startDeferredTransitionIfNeeded:] + 712
55 UIKit                          0x18d2c9a34 -[UINavigationController __viewWillLayoutSubviews] + 124
56 UIKit                          0x18d2c995c -[UILayoutContainerView layoutSubviews] + 188
57 UIKit                          0x18d220000 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1256
58 QuartzCore                     0x187df10b4 -[CALayer layoutSublayers] + 184
59 QuartzCore                     0x187df5194 CA::Layer::layout_if_needed(CA::Transaction*) + 332
60 QuartzCore                     0x187d63f24 CA::Context::commit_transaction(CA::Transaction*) + 336
61 QuartzCore                     0x187d8a340 CA::Transaction::commit() + 540
62 QuartzCore                     0x187d8b180 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 92
63 CoreFoundation                 0x183dbb8b8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
64 CoreFoundation                 0x183db9270 __CFRunLoopDoObservers + 412
65 CoreFoundation                 0x183db982c __CFRunLoopRun + 1292
66 CoreFoundation                 0x183cda2d8 CFRunLoopRunSpecific + 436
67 GraphicsServices               0x185b6bf84 GSEventRunModal + 100
68 UIKit                          0x18d286880 UIApplicationMain + 208
69 project-vr                     0x1000cdac8 main (AppDelegate.swift:17)
70 libdyld.dylib                  0x1837fe56c start + 4

#1. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x18390cbc4 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18390ca3c mach_msg + 72
2  CoreFoundation                 0x183dbbce4 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x183db98b0 __CFRunLoopRun + 1424
4  CoreFoundation                 0x183cda2d8 CFRunLoopRunSpecific + 436
5  Foundation                     0x1847026e4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x184721afc -[NSRunLoop(NSRunLoop) runUntilDate:] + 96
7  UIKit                          0x18ddd202c -[UIEventFetcher threadMain] + 136
8  Foundation                     0x184803860 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x183a4032c _pthread_body + 308
10 libsystem_pthread.dylib        0x183a401f8 _pthread_body + 310
11 libsystem_pthread.dylib        0x183a3ec38 thread_start + 4

#2. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x18390cbc4 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18390ca3c mach_msg + 72
2  CoreFoundation                 0x183dbbce4 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x183db98b0 __CFRunLoopRun + 1424
4  CoreFoundation                 0x183cda2d8 CFRunLoopRunSpecific + 436
5  CFNetwork                      0x184443b40 +[NSURLConnection(Loader) _resourceLoadLoop:] + 404
6  Foundation                     0x184803860 __NSThread__start__ + 996
7  libsystem_pthread.dylib        0x183a4032c _pthread_body + 308
8  libsystem_pthread.dylib        0x183a401f8 _pthread_body + 310
9  libsystem_pthread.dylib        0x183a3ec38 thread_start + 4

#3. com.twitter.crashlytics.ios.MachExceptionServer
0  project-vr                     0x1004e726c CLSProcessRecordAllThreads + 129188
1  project-vr                     0x1004e726c CLSProcessRecordAllThreads + 129188
2  project-vr                     0x1004e7128 CLSProcessRecordAllThreads + 128864
3  project-vr                     0x1004d69e0 CLSHandler + 61464
4  project-vr                     0x1004d1690 CLSMachExceptionServer + 40136
5  libsystem_pthread.dylib        0x183a4032c _pthread_body + 308
6  libsystem_pthread.dylib        0x183a401f8 _pthread_body + 310
7  libsystem_pthread.dylib        0x183a3ec38 thread_start + 4

#4. Thread
0  libsystem_kernel.dylib         0x18392ddbc __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x183a3f144 _pthread_wqthread + 1288
2  libsystem_pthread.dylib        0x183a3ec30 start_wqthread + 4

#5. Thread
0  libsystem_kernel.dylib         0x18392ddbc __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x183a3efb0 _pthread_wqthread + 884
2  libsystem_pthread.dylib        0x183a3ec30 start_wqthread + 4

#6. AVAudioSession Notify Thread
0  libsystem_kernel.dylib         0x18390cbc4 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18390ca3c mach_msg + 72
2  CoreFoundation                 0x183dbbce4 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x183db98b0 __CFRunLoopRun + 1424
4  CoreFoundation                 0x183cda2d8 CFRunLoopRunSpecific + 436
5  AVFAudio                       0x1895a3774 GenericRunLoopThread::Entry(void*) + 164
6  AVFAudio                       0x1895ce018 CAPThread::Entry(CAPThread*) + 84
7  libsystem_pthread.dylib        0x183a4032c _pthread_body + 308
8  libsystem_pthread.dylib        0x183a401f8 _pthread_body + 310
9  libsystem_pthread.dylib        0x183a3ec38 thread_start + 4

#7. Thread
0  libsystem_kernel.dylib         0x18392ddbc __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x183a3efb0 _pthread_wqthread + 884
2  libsystem_pthread.dylib        0x183a3ec30 start_wqthread + 4

#8. Crashed: com.google.cardboard.RenderThread
0  project-vr                     0x10041ca98 ion::gfx::Renderer::ShaderInputRegistryResource::UniformStack::Pop() + 88700
1  project-vr                     0x10041558c ion::gfx::Renderer::ResourceBinder::PopUniforms(ion::base::AllocVector<ion::gfx::Uniform> const&) + 58736
2  project-vr                     0x10041558c ion::gfx::Renderer::ResourceBinder::PopUniforms(ion::base::AllocVector<ion::gfx::Uniform> const&) + 58736
3  project-vr                     0x100414720 ion::gfx::Renderer::ResourceBinder::DrawNode(ion::gfx::Node const&, ion::gfx::GraphicsManager*) + 55044
4  project-vr                     0x1004146b8 ion::gfx::Renderer::ResourceBinder::DrawNode(ion::gfx::Node const&, ion::gfx::GraphicsManager*) + 54940
5  project-vr                     0x1004146b8 ion::gfx::Renderer::ResourceBinder::DrawNode(ion::gfx::Node const&, ion::gfx::GraphicsManager*) + 54940
6  project-vr                     0x1004146b8 ion::gfx::Renderer::ResourceBinder::DrawNode(ion::gfx::Node const&, ion::gfx::GraphicsManager*) + 54940
7  project-vr                     0x100413d54 ion::gfx::Renderer::ResourceBinder::DrawScene(ion::base::SharedPtr<ion::gfx::Node> const&, std::__1::bitset<35ul> const&, ion::gfx::ShaderProgram*) + 52536
8  project-vr                     0x100413b70 ion::gfx::Renderer::DrawScene(ion::base::SharedPtr<ion::gfx::Node> const&) + 52052
9  project-vr                     0x1002edee8 vr::WidgetRenderer::RenderFrame() + 45560
10 project-vr                     0x100112cd0 -[GVRWidgetView nativeRenderFrame] + 4309920976
11 project-vr                     0x100114554 -[GVRWidgetView render:] + 4309927252
12 project-vr                     0x10010a848 -[GVRWeakRenderTarget render:] + 4309887048
13 project-vr                     0x10010b918 -[GVRRenderLoop updateWithDisplayLink:] + 4309891352
14 QuartzCore                     0x187cdefd4 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 672
15 IOKit                          0x18407e30c IODispatchCalloutFromCFMessage + 392
16 CoreFoundation                 0x183da2080 __CFMachPortPerform + 188
17 CoreFoundation                 0x183dbc9dc __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
18 CoreFoundation                 0x183dbc0e0 __CFRunLoopDoSource1 + 440
19 CoreFoundation                 0x183db9bb4 __CFRunLoopRun + 2196
20 CoreFoundation                 0x183cda2d8 CFRunLoopRunSpecific + 436
21 CoreFoundation                 0x183d2912c CFRunLoopRun + 116
22 Foundation                     0x184803860 __NSThread__start__ + 996
23 libsystem_pthread.dylib        0x183a4032c _pthread_body + 308
24 libsystem_pthread.dylib        0x183a401f8 _pthread_body + 310
25 libsystem_pthread.dylib        0x183a3ec38 thread_start + 4

#9. Thread
0  libsystem_kernel.dylib         0x18392d150 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x183a42d40 _pthread_cond_wait$VARIANT$mp + 640
2  libc++.1.dylib                 0x1832abea4 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3  project-vr                     0x10049db54 gvr::TaskLoop::Loop() + 1704
4  project-vr                     0x10049cecc gvr::PlatformThread::ThreadMain(std::__1::function<void ()>) + 2752
5  project-vr                     0x10049d534 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::__bind<void (gvr::PlatformThread::*)(std::__1::function<void ()>), gvr::PlatformThread*, std::__1::function<void ()> > > >(void*) + 136
6  libsystem_pthread.dylib        0x183a4032c _pthread_body + 308
7  libsystem_pthread.dylib        0x183a401f8 _pthread_body + 310
8  libsystem_pthread.dylib        0x183a3ec38 thread_start + 4

#10. Thread
0  libsystem_kernel.dylib         0x18392ddbc __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x183a3efb0 _pthread_wqthread + 884
2  libsystem_pthread.dylib        0x183a3ec30 start_wqthread + 4

#11. com.apple.CoreMotion.MotionThread
0  libsystem_kernel.dylib         0x18390cbc4 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18390ca3c mach_msg + 72
2  CoreFoundation                 0x183dbbce4 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x183db98b0 __CFRunLoopRun + 1424
4  CoreFoundation                 0x183cda2d8 CFRunLoopRunSpecific + 436
5  CoreFoundation                 0x183d2912c CFRunLoopRun + 116
6  CoreMotion                     0x1890be088 (null) + 227076
7  libsystem_pthread.dylib        0x183a4032c _pthread_body + 308
8  libsystem_pthread.dylib        0x183a401f8 _pthread_body + 310
9  libsystem_pthread.dylib        0x183a3ec38 thread_start + 4

#12. Thread
0  libsystem_kernel.dylib         0x18392ddbc __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x183a3efb0 _pthread_wqthread + 884
2  libsystem_pthread.dylib        0x183a3ec30 start_wqthread + 4

#13. Thread
0  libsystem_kernel.dylib         0x18392d150 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x183a42d40 _pthread_cond_wait$VARIANT$mp + 640
2  libc++.1.dylib                 0x1832abea4 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3  project-vr                     0x10049db54 gvr::TaskLoop::Loop() + 1704
4  project-vr                     0x10049cecc gvr::PlatformThread::ThreadMain(std::__1::function<void ()>) + 2752
5  project-vr                     0x10049d534 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::__bind<void (gvr::PlatformThread::*)(std::__1::function<void ()>), gvr::PlatformThread*, std::__1::function<void ()> > > >(void*) + 136
6  libsystem_pthread.dylib        0x183a4032c _pthread_body + 308
7  libsystem_pthread.dylib        0x183a401f8 _pthread_body + 310
8  libsystem_pthread.dylib        0x183a3ec38 thread_start + 4

#14. Thread
0  libsystem_kernel.dylib         0x18390cc18 semaphore_timedwait_trap + 8
1  libdispatch.dylib              0x18379b4d0 _dispatch_sema4_timedwait$VARIANT$mp + 84
2  libdispatch.dylib              0x18379bd40 _dispatch_semaphore_wait_slow + 72
3  libdispatch.dylib              0x1837a76ac _dispatch_worker_thread + 256
4  libsystem_pthread.dylib        0x183a4032c _pthread_body + 308
5  libsystem_pthread.dylib        0x183a401f8 _pthread_body + 310
6  libsystem_pthread.dylib        0x183a3ec38 thread_start + 4

**Comment by sanjayc77** [comment]
Thanks for reporting the issue and including the stack trace. Unfortunately, that is not much to help troubleshoot without knowing how your OpenGL app is setup. It might be helpful to provide a reproducible sample code, maybe by modifying the includes GVRSDK samples.

Also, GVRWidgetView is now deprecated. You should switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). See the updated VideoWidgetDemo sample app.
