### ISSUE TITLE
How to modify Panorama Sample

### ISSUE THREAD

**Issue by Juanfry88** [googlevr/gvr-ios-sdk#278]
Hello, 

I'm trying to modify the "andes.jpg" image to my own panoramic, but when I change it dosen't work!
Any idea? The type of the image is different, it is a spherical image.

**Comment by sanjayc77** [comment]
Did you try to change this line:
https://github.com/googlevr/gvr-ios-sdk/blob/a4d9c268474b7b05f573844eab4007ead1d0061c/Samples/Panorama/PanoramaViewController.m#L122

Also match the type of image here:
https://github.com/googlevr/gvr-ios-sdk/blob/a4d9c268474b7b05f573844eab4007ead1d0061c/Samples/Panorama/PanoramaViewController.m#L129

**Comment by Juanfry88** [comment]
Yes, I change that 2 lines but I don't get anything... I choose MONOType but only render a black image...

**Comment by Juanfry88** [comment]
Why did you close my thread?
