### ISSUE TITLE
Modify Panorama image not work!

### ISSUE THREAD

**Issue by Juanfry88** [googlevr/gvr-ios-sdk#280]
I modify the default image: _UIImage *image = [UIImage imageNamed:@"andes.jpg"]_
and I change this line:  _meshType:kGVRMeshTypeStereoTopBottom_ to MONOTYPE but not work.
I only have a black image...
Any ideas?

**Comment by sanjayc77** [comment]
That is because the included image for the Panorama app has left and right images at top and bottom respectively: https://github.com/googlevr/gvr-ios-sdk/blob/master/Samples/Panorama/andes.jpg
