### ISSUE TITLE
Enable/Disable gyroscope programmatically in GVRVideoView

### ISSUE THREAD

**Issue by orenk86** [googlevr/gvr-ios-sdk#281]
Hi, is there a way to programmatically enable or disable the pan/tilt in the GVRVideoView?
Thanks!!

**Comment by nathanmartz** [comment]
No, but we are actually deprecating that in favor of [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). GVRKit is open source, so you can do whatever you need to with it.
