### ISSUE TITLE
Garbage being shown when rendering views with transparency

### ISSUE THREAD

**Issue by ivanonchi** [googlevr/gvr-ios-sdk#282]
Working on an app based on the VideoWidgedDemo, I tried to add views with transparency (UILabel with clear background, image with transparency in UIImageView, etc.) but there were random colors shown in place of transparency.

I fixed it by clearing the context before using it for view rendering, but then the background was black, so I noticed alpha blending was not enabled.

I sent a pull request #274 with a fix to these issues in hopes it is of help.

**Comment by nathanmartz** [comment]
We recommend you migrate to GVRKit (in the iOS repo) as it includes the same functionality but is much more extensible than VideoWidget (which will be deprecated soon).

**Comment by ivanonchi** [comment]
Thanks @nathanmartz but please note the provided VideoWidgetDemo I refer to is actually using GVRKit (GVRVideoRenderer etc.), not the deprecated VideoWidget. The project name is a bit misleading 😅 
Could you consider taking a look as this is a bug in GVRKit?

**Comment by sanjayc77** [comment]
Thanks for the PR. We will address this in the next release.
