### ISSUE TITLE
not load content HLS

### ISSUE THREAD

**Issue by erickfox** [googlevr/gvr-ios-sdk#284]
Hello, I'm working on a project that aims to show a feed HLS, when I add the feed, enters the delegate didFailToLoadContent with this error: The operation could not be completed, you think it will happen for something specific?

**Comment by sanjayc77** [comment]
Please switch to using [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit), which gives you control over AVPlayer. See the updated VideoWidgetDemo app.
