### ISSUE TITLE
Present view controller

### ISSUE THREAD

**Issue by erickfox** [googlevr/gvr-ios-sdk#285]
Hello, for what reason, when you make a present to the view controller of the container view, starts in full screen, with the Back button

**Comment by sanjayc77** [comment]
To allow the user to dismiss the view controller. That is the primary mechanism to exit VR mode.

But, we do expose "hidesBackButton" property on the GVROverlayView class, which you can use to not show the back button. But you will have to fork [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit) and add that [here](https://github.com/googlevr/gvr-ios-sdk/blob/master/Samples/GVRKit/GVRRendererView.mm#L200):

`
_overlayView.hidesBackButton = YES;
`

You would still need some way to dismiss the view controller programmatically though.

**Comment by erickfox** [comment]
I did not explain correctly, attached screenshots to understand the process
1.-
![captura de pantalla 2017-10-30 a la s 2 03 20 p m](https://user-images.githubusercontent.com/31451840/32192945-57b1a34a-bd7b-11e7-90a3-c7d01d53a530.png)

2.- 
![captura de pantalla 2017-10-30 a la s 2 03 41 p m](https://user-images.githubusercontent.com/31451840/32192953-5db34d84-bd7b-11e7-959d-2c6df72b9ba4.png)

3.-
![captura de pantalla 2017-10-30 a la s 2 04 10 p m](https://user-images.githubusercontent.com/31451840/32192965-6655ee60-bd7b-11e7-9c92-0cafd36549da.png)

You can see that in the display mode enbeded starts with the button back
