### ISSUE TITLE
No Xcode Workspace

### ISSUE THREAD

**Issue by scmcom** [googlevr/gvr-ios-sdk#286]
#3 here: https://developers.google.com/vr/ios/get-started clearly says workspace. 

I do not see a workspace in the repo. I am therefore unable to run the Samples with Pod dependencies.

**Comment by sanjayc77** [comment]
Running `pod update` creates the project.xcworkspace file.

**Comment by scmcom** [comment]
Ok it did not do that on my system:
![screen shot 2017-11-03 at 4 37 48 pm](https://user-images.githubusercontent.com/5971133/32394976-7b050fa2-c0b5-11e7-8ed5-7db01a900100.png)
Have you seen this before or know how to fix?

**Comment by sanjayc77** [comment]
Make sure you have Cocoapods installed and run `pod update` in the folder containing the Podfile. The output of `pod update` command is the <projectname>.xcworkspace file. Then you open the workspace file in Xcode.

If that is not working, paste the output of `pod update` here.

**Comment by scmcom** [comment]
Not working; no workspace:
```
Update all pods
Updating local specs repositories

CocoaPods 1.4.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.4.0.beta.2

Analyzing dependencies
Downloading dependencies
Installing GTMSessionFetcher (1.1.6)
Installing GVRAudioSDK (1.100.0)
Installing GVRKit (1.100.0)
Installing GVRSDK (1.100.0)
Installing GoogleToolboxForMac (2.1.0)
Generating Pods project
Abort trap: 6
```
