### ISSUE TITLE
Crash app

### ISSUE THREAD

**Issue by erickfox** [googlevr/gvr-ios-sdk#287]
Hello,

my app crashed on line 1479 of the header file GVR. h, my device is an IPhone 5c
```
 /// For more information, see gvr_initialize_gl().
void InitializeGl() { gvr_initialize_gl(context_); }
```

someone can help me

**Comment by sanjayc77** [comment]
Do you have a stack trace? Any additional context regarding what you are trying to achieve will also help.

**Comment by erickfox** [comment]
[example.txt](https://github.com/googlevr/gvr-ios-sdk/files/1458683/example.txt)
Hi, attachment Crash file

**Comment by sanjayc77** [comment]
Hmm, that's not much to go by. This issue was similar: https://github.com/googlevr/gvr-ios-sdk/issues/288

iPhone 5c does not support OpenGLES 3. Can you try changing EAGLContext initialization to OpenGLES2 here and report back?

**Comment by erickfox** [comment]
It is, just the same problem. I will follow the #288 thread to work the solution, thank you very much
