### ISSUE TITLE
Does GVRVideoView work with YouTube 360-degree live streaming?

### ISSUE THREAD

**Issue by rokamo** [googlevr/gvr-ios-sdk#29]
Been hoping to get an answer (http://stackoverflow.com/questions/36707121/does-gcsvideoview-work-with-youtube-360-degree-live-streaming) for a while. This doesn't work...

    NSString *videoPath =@"https://youtu.be/Db-uq08ydI4";
    NSURL *nsurl =  [NSURL URLWithString: videoPath];    
    [_videoView loadFromUrl: nsurl];

It says 

2016-05-20 13:35:32.797 VideoWidgetDemo[1161:904914] Failed to load video: Operation Stopped

Any ideas?

**Comment by sanjayc77** [comment]
No it does not. It will only play videos that the iOS's AVPlayer can play (https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVPlayer_Class/).

**Comment by anks62** [comment]
@rokamo 
use HCYoutubeParser to play 360 you tube video.
