### ISSUE TITLE
Is there a way to remove the instruction screen when transitioning?

### ISSUE THREAD

**Issue by pineapplejoe** [googlevr/gvr-ios-sdk#292]
I read through [this](https://github.com/googlevr/gvr-ios-sdk/issues/9) and it looks like the thing that was changed was being able to toggle the info button?

What about the transition screen?  
The gear?
The square button?
The back arrow?

**Comment by sanjayc77** [comment]
The _GVROverlayView_ property _overlayView_ of _GVRRendererView_ allows you to control those UI elements. See https://github.com/googlevr/gvr-ios-sdk/blob/f0d9c1985ef67139825a1ec2f77c687a70c61f7b/Samples/GVRKit/GVRRendererViewController.m#L74
