### ISSUE TITLE
Crash in [GVRWidgetView gestureRecognizerShouldBegin:]

### ISSUE THREAD

**Issue by ghking** [googlevr/gvr-ios-sdk#293]
I frequently get this crash originating in `[GVRWidgetView gestureRecognizerShouldBegin:]`:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UITapGestureRecognizer velocityInView:]: unrecognized selector sent to instance 0x1d43e8c00'
```

`velocityInView` is a method on UIPanGestureRecognizer, not on UITapGestureRecognizer. It seems like there's some incorrect casting or something happening there.

Thanks!

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRWidgetView) is deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. The samples are also updated and include support for panning (and tapping).
