### ISSUE TITLE
GVR Audio Keeps Changing AVAudioSession Category to AVAudioSessionCategorySoloAmbient

### ISSUE THREAD

**Issue by achuvm** [googlevr/gvr-ios-sdk#295]
Hi,

We're using the iOS GVR SDK with the Audio API for playback but we also want to enable audio recording which we're doing through AVAudioRecorder. To do this, we need to set the AVAudioSession's category to AVAudioSessionCategoryRecord or AVAudioSessionCategoryRecordAndPlayback. 

However, it seems like the GVR AudioApi object (https://developers.google.com/vr/android/ndk/reference/class/gvr/audio-api) is constantly changing the category back to AVAudioSessionCategoryAmbientSolo which is causing my AVAudioRecorder to stop recording audio.

We're using the following pod versions:

    pod 'GVRKit', '1.100.0'
    pod 'GVRAudioSDK', '1.100.0'

**Comment by jkammerl** [comment]
Thanks for the report. This issue has been already addressed in our code and it should be fixed in the next upcoming release.

**Comment by achuvm** [comment]
Hi @jkammerl,

Is there an ETA on the next release?

Thanks!
