### ISSUE TITLE
Best Practice : Replace Youtube Player with GVR Player

### ISSUE THREAD

**Issue by effincleveland** [googlevr/gvr-ios-sdk#296]
Hi, 

I have found some examples out there that take advantage of the Youtube API, pulling videos/playlists/channel info, then enabling the Youtube player for playback. Pretty cool, except that Youtube doesn't seem to support 360 ios embeds. This is where I imagine GVR to kick in. 

I would like to be able to pull Youtube channel info and Playlist videos, sort them into a tableview, and playback via the GVR player (to get 360 support).

Sort of like this:
https://github.com/pierreco/ReactNativeYoutube 
but with the GVR player instead of Youtube Player

I'm more of a content creator than a programmer, and most of my experience is with web languages, not swift/obj-c so I'm a bit lost/stuck. Wondering if any of you kind people could help me out, or point me in the right direction, as far as properly importing the Youtube/GVR modules, and calling them properly?

**Comment by sanjayc77** [comment]
This SDK is intended for ObjC programmers who are also comfortable with OpenGL. Also, YouTube videos cannot play outside of YouTube player. So, unfortunately, this SDK is not going to help you here.

You may be able to deeplink a video URL to the YT app installed on the phone. That way, when the user clicks on a video in your table view, you would send them to the YT app. There they can play 360 videos.
