### ISSUE TITLE
Timed gaze input interaction

### ISSUE THREAD

**Issue by sujay46** [googlevr/gvr-ios-sdk#297]
Have anyone tried implementing timed gaze interaction like we can do in Unity? 
 I want to implement gaze interaction in my VideoPlayer. The play and pause actions need to be triggered by timed gaze interaction.

**Comment by sanjayc77** [comment]
Look at the TreasureHunt sample. It highlights the cube when the user is looking at it. You can easily put a timer based code to perform a selection if the user is looking at it for some time.
