### ISSUE TITLE
hidesTransitionView property behavior

### ISSUE THREAD

**Issue by tongo** [googlevr/gvr-ios-sdk#298]
Hi, I'm using the 1.120.0 version of SDK, my goal is to hide the cardboard instruction for the user.
Setting the *hidesTransitionView* property to *false* or *true* produces the same behavior:
the instruction view is shown only the first time that the user set the cardboard view mode

What is the right behavior of the *hidesTransitionView* property?
How can I hide the instructions view?

**Comment by sanjayc77** [comment]
Is this the _hidesTransistionView_ property of GVRWidgetView? We have deprecated GVRWidgetView based apps and want developers to switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit), also available as Cocoapod.
