### ISSUE TITLE
GVRRendererViewControllerDelegate's didTapTriggerButton not being called

### ISSUE THREAD

**Issue by ikester** [googlevr/gvr-ios-sdk#299]
I'm building VideoWidgetDemo from the Samples and can't figure out why the `didTapTriggerButton` method of the `GVRRendererViewControllerDelegate` is not being called.

I can pause and play the video by tapping when the reticle is on the progress bar button. But if I remove the progress bar view from the `GVRSceneRenderer` and tap around I can never get the `didTapTriggerButton` to get called.

According to the code, this should be pretty straightforward:
```
- (void)didTapTriggerButton {
  // In embedded mode, pass the trigger tap to our delegate.
  if (self.isModal && [self.delegate respondsToSelector:@selector(didTapTriggerButton)]) {
    [self.delegate didTapTriggerButton];
  }
}
```

Am I not understanding something basic about how this is supposed to work?

**Comment by sanjayc77** [comment]
Hmmm, I did not have that issue. I commented out the code which adds the toolbar view (containing the progress bar):

//[sceneRenderer.renderList addRenderObject:viewRenderer];

I can always get didTapTriggerButton to get called.
