### ISSUE TITLE
Is there a way to get Head Position in GVRVideoView?

### ISSUE THREAD

**Issue by wsdfz** [googlevr/gvr-ios-sdk#30]
When use GVRVideoView to play a video, we sometime want to know the Head Position to know which part is playing. 
Is there a way to get a value like GVRHeadTransform ? Or something like a simple theta, phi ?

**Comment by lianguowu** [comment]
I also get the same problem of the GVRVideoView,

**Comment by DanEdgarILM** [comment]
Is there any way to add this as a feature? 

I have tried adding my own CoreMotion based tracking, but cannot get a calibrated match to use roll / pitch / yaw to identify what the user may be looking at within the video.

The other issue with 'rolling my own' is that I need to do it twice: Once for Android and once for iOS.

It seems like there should be a way to expose the GVRHeadTransform via a callback on the GVRWidgetViewDelegate as I bet that GVRVideoView is really just a per-video frame texture push into the GVRCardboardView and/or GVRPanoramaView.

**Comment by nathanmartz** [comment]
Yeah, we have gotten this request several times and are looking into adding it to the API.

**Comment by GrahamLea** [comment]
Can we get this for the Panorama View as well please? The GVRAudioEngine looks awesome, but without being able to get the head position/rotation out of the panorama view, there's no way to set the same in the audio engine. :(

**Comment by dav-cz** [comment]
This was added in v0.9.0, thanks for your feedback and patience!
https://developers.google.com/vr/ios/release-notes
