### ISSUE TITLE
GVRKit.h file not found

### ISSUE THREAD

**Issue by parveshmishra** [googlevr/gvr-ios-sdk#308]
As per your Guideline I had pod 'GVRSDK' in pod file and install and also update the pod. but there is GVRKit file is missing. I have already tried many times but its not resolving the error. I was perviously added the same code and its worked properly.

**Comment by Performador** [comment]
Hi, you should see something like this in the editor:

<img width="260" alt="screen shot 2018-03-22 at 4 51 21 pm" src="https://user-images.githubusercontent.com/22187349/37804409-5710cb46-2df1-11e8-95cd-5806af0d75fc.png">

Which should allow you to 
`#import <GVRKit/GVRKit.h>`

**Comment by jdduke** [comment]
Feel free to re-open if the suggested steps still aren't working.
