### ISSUE TITLE
when i used the VideoWidgetDemo 

### ISSUE THREAD

**Issue by lianguowu** [googlevr/gvr-ios-sdk#32]
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by nathanmartz** [comment]
We're not aware of any issues with the pod. Please make sure to follow the install instructions.

**Comment by SirWellington** [comment]
Follow the answer [here](http://stackoverflow.com/questions/26287103/cocoapods-warning-cocoapods-did-not-set-the-base-configuration-of-your-project) to get it to work.
I just removed the the configuration files and ran `pod install` again.
