### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by jjfster** [googlevr/gvr-ios-sdk#328]
xCode 9.2

Add the pod:

```
platform :ios, '10.0'

 target 'MyApp' do
  use_frameworks!

  pod 'Alamofire'
  pod 'google-cast-sdk'
  pod 'SwiftyJSON'
  pod 'SDWebImage'
  pod 'GoogleAPIClientForREST/YouTube', '~> 1.2.1'
  pod 'youtube-ios-player-helper', '~> 0.1.6'
  pod 'MarqueeLabel'
  pod 'GVRKit'
end
```

Crashes immediately on launch of the project in simulators and device:

#0	0x0000000104c42a25 in std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) ()
#1	0x0000000103bfd3b6 in std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) at /Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ostream:723
#2	0x00000001039e9e76 in (anonymous namespace)::AddFlagValidator(void const*, bool (*)()) ()
#3	0x00000001039f83d0 in _GLOBAL__sub_I_vlog_is_on.cc ()
#4	0x000000010495cc16 in ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) ()
#5	0x000000010495ce46 in ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) ()
#6	0x00000001049586da in ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) ()
#7	0x0000000104957898 in ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) ()
#8	0x000000010495792c in ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) ()
#9	0x000000010494c17b in dyld::initializeMainExecutable() ()
#10	0x000000010494fc98 in dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) ()
#11	0x000000010494b3d4 in start_sim ()
#12	0x000000010955f510 in dyld::useSimulatorDyld(int, macho_header const*, char const*, int, char const**, char const**, char const**, unsigned long*, unsigned long*) ()
#13	0x000000010955da39 in dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) ()
#14	0x0000000109559249 in dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*) ()
#15	0x0000000109559036 in _dyld_start ()

  0x10aade3b1 <+33>:  callq  0x10abb895c               ; symbol stub for: std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)
    **0x10aade3b6 <+38>:  cmpb   $0x0, -0x50(%rbp)**
    0x10aade3ba <+42>:  je     0x10aade46e               ; <+222> at ios
    0x10aade3c0 <+48>:  movq   (%rbx), %rax
  
  Thread 1: EXC_BAD_ACCESS (code=1, address=0xffffffffffffffe8)

Cannot trace.  Zombies don't help, etc.  Just hosed. 

Tried on several simulators (iPhone 8, 8 Plus, 7) and iPhone 7 device.

Tried switching to objective-c++ compile source files just as a guess.
 
Tried moving the pod lines around.

I can build and run the old objective C sample project though.

Is there some weird conflict in the pod?  As soon as I remove the GVRKit pod, everything is fine in this project again.

Not sure how to troubleshoot.

**Comment by jjfster** [comment]
Should've mentioned this is a Swift 4 project.

**Comment by jjfster** [comment]
It turned out to be the Google Cast SDK pod had a dependency that was conflicting with GVRKit.

**Comment by danielgindi** [comment]
@jjfster what conflict exactly was that?
