### ISSUE TITLE
What is the best way to release the GVRVideoView

### ISSUE THREAD

**Issue by myflashlab** [googlevr/gvr-ios-sdk#33]
Everything works great except for the fact that if I open the ```GVRVideoView``` view and then close it and then open it again for a couple of times, my app will receive a ```didReceiveMemoryWarning``` and then the jetsam will force close my app!

I wonder if there is a way to make sure when we are closing the VR view, the view is completely released? currently I am doing this:

```objective-c
-(void)viewWillDisappear:(BOOL)animated
{
    [_videoView stop];
    [_videoView removeFromSuperview];
    _videoView = nil;
}
```
should I do something else too?

**Comment by nathanmartz** [comment]
This is a bug and we are tracking it in this thread: https://github.com/googlevr/gvr-ios-sdk/issues/16#issuecomment-220921393
