### ISSUE TITLE
manually controlling the sphere view?

### ISSUE THREAD

**Issue by myflashlab** [googlevr/gvr-ios-sdk#34]
I wonder if it is possible to control the initial location of the GVRVideoView video? the sphere? so when the video starts, it can be started from another perspective than the default current one? Thanks.

**Comment by myflashlab** [comment]
We would appreciate a comment on this. :) we are kinda in a hurry. Even if it's something to be added in future versions of the SDK, that would be great to know if you are considering it. Thanks a lot.

**Comment by nathanmartz** [comment]
Setting the initial orientation is on our list, definitely.

**Comment by myflashlab** [comment]
Awesome, looking forward to it.

On Tuesday, May 24, 2016, nathanmartz <notifications@github.com> wrote:

> Setting the initial orientation is on our list, definitely.
>
> On Tue, May 24, 2016 at 4:23 AM, myflashlab <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > We would appreciate a comment on this. :) we are kinda in a hurry. Even
> if
> > it's something to be added in future versions of the SDK, that would be
> > great to know if you are considering it. Thanks a lot.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/googlevr/gvr-ios-sdk/issues/34#issuecomment-221240160>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/googlevr/gvr-ios-sdk/issues/34#issuecomment-221273899>
>


-- 
Sent from iPhone

**Comment by stefanomondino** [comment]
thanks @nathanmartz , we're looking forward to it too. Strangely, some videos start "facing backwards"

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRVideoView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. Take a look at the updated VideoWidgetDemo sample app and GVRTextureRenderer, which maps the video texture to a sphere.
