### ISSUE TITLE
Disable fullscreen button in Cardboard mode when enableFullscreenButton is false

### ISSUE THREAD

**Issue by ozzy91** [googlevr/gvr-ios-sdk#35]
When I setup my GVRWidgetView (applies to both Panorama and Video) I set enableFullscreenButton to false, because my WidgetView already fills the entire screen.
When I now go into Cardboard mode, a different fullscreen button appears in the top right, that just disables the VR rendering mode. This button does the exact same thing as pressing the back button and going to my GVRWidgetView that fills the screen.

This is very confusing from a user perspective, because I need to put some Views on top of my GVRWidgetView. So when the user disables Cardboard mode by pressing the back button, they see the Views but now they can also disable that mode by pressing the fullscreen button, but without seeing other Views since it is a GLView.

The fullscreen button in Cardboard mode should respect the enableFullscreenButton property or please give as separate property to toggle its visibility.

**Comment by nishilshah17** [comment]
Seconded.

**Comment by sanjayc77** [comment]
Its a known bug.

**Comment by dav-cz** [comment]
Fixed in v0.8.5
