### ISSUE TITLE
Can the SDK install manual as pop update fail.

### ISSUE THREAD

**Issue by PhymurByrd** [googlevr/gvr-ios-sdk#36]
For some reasons, the "pop update" fail. 
I can get the GVRSDK-0.8.0.tar.gz by the other way, but how can I install it manual? 
Thanks.

**Comment by sanjayc77** [comment]
You have to add the headers, libraries and resources manually added to your Xcode project. They are in the respective folders after you unzip GVRSDK-0.8.0.tar.gz.

**Comment by ChokWah** [comment]
Try VPN .
