### ISSUE TITLE
how to hide the tipView?

### ISSUE THREAD

**Issue by gityoung** [googlevr/gvr-ios-sdk#37]
the SDK tip view  when i change displaymodeVR .
everytime touch the button.the tip view is show.
how to hide the tipView?
it’s boring.  How do I set let him show only once？

**Comment by WorkerAmo** [comment]
Please check the  closed issues.

**Comment by WorkerAmo** [comment]
https://github.com/googlevr/gvr-ios-sdk/issues/26

**Comment by haydarKarkin** [comment]
I think you should set 'hidesTransitionView' as false.

You can see detailed information under that [link](https://developers.google.com/vr/ios/reference/interface_g_v_r_widget_view.html#a4caa081eedcb807d5b5555d8b4f7b777).

**Comment by nathanmartz** [comment]
That's correct.
