### ISSUE TITLE
Can't change to Cardboard play 

### ISSUE THREAD

**Issue by ChokWah** [googlevr/gvr-ios-sdk#38]
I got  the .h , .a , .bundle from the DemoProject,  then import in my project , it can play video .But , when I click the cardboard button . It crashed.

my uiviewcontroller haven't xib. So, I use NSLayoutConstraint;
Code : 
@interface PlayerVC ()<GVRVideoViewDelegate>{BOOL _isPaused;}
@property (nonatomic)         GVRVideoView *videoView;
@end

- (void)viewDidload{
     _videoView = [[GVRVideoView alloc]initWithFrame:self.view.frame];
    [self.view addSubview:_videoView];
    [_videoView setTranslatesAutoresizingMaskIntoConstraints:NO];
    
    NSLayoutConstraint *constraint1 = [NSLayoutConstraint constraintWithItem:_videoView attribute:NSLayoutAttributeTop relatedBy:NSLayoutRelationEqual toItem:self.view attribute:NSLayoutAttributeTop multiplier:1.0 constant:1];
    NSLayoutConstraint *constraint2 = [NSLayoutConstraint constraintWithItem:_videoView attribute:NSLayoutAttributeLeft relatedBy:NSLayoutRelationEqual toItem:self.view attribute:NSLayoutAttributeLeft multiplier:1.0 constant:1];
    NSLayoutConstraint *constraint3 = [NSLayoutConstraint constraintWithItem:_videoView attribute:NSLayoutAttributeBottom relatedBy:NSLayoutRelationEqual toItem:self.view attribute:NSLayoutAttributeBottom multiplier:1.0 constant:-1];
    NSLayoutConstraint *constraint4 = [NSLayoutConstraint constraintWithItem:_videoView attribute:NSLayoutAttributeRight relatedBy:NSLayoutRelationEqual toItem:self.view attribute:NSLayoutAttributeRight multiplier:1.0 constant:-1];
    NSArray *array = [NSArray arrayWithObjects:constraint1, constraint2, constraint3, constraint4 ,nil];
    [self.view addConstraints:array];
    
    _videoView.delegate = self;
    _videoView.enableFullscreenButton = NO;
    _videoView.enableCardboardButton  = YES;
    _isPaused = NO;

   NSString *path = [[NSBundle mainBundle] pathForResource:videoName ofType:@""];
    NSURL *urlR = [[NSURL alloc] initFileURLWithPath:path];
    [_videoView loadFromUrl:urlR];
}

Log : 

+[GOOTypography robotoMediumWithSize:]: unrecognized selector sent to class 0x1002aa660

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[GOOTypography robotoMediumWithSize:]: unrecognized selector sent to class 0x1002aa660'
*** First throw call stack:
(0x18174edb0 0x180db3f80 0x181755b44 0x181752bec 0x181650c5c 0x100113f2c 0x1001137e4 0x10010c430 0x100119238 0x1868e4be8 0x1868e4b64 0x1868cc870 0x1868e4454 0x18689cc0c 0x181704728 0x1817024cc 0x1817028fc 0x18162cc50 0x182f14088 0x186916088 0x1001029c8 0x1811ca8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

I can't see what happen , how to fix this .

**Comment by gityoung** [comment]
file only support MP4

**Comment by ChokWah** [comment]
@gityoung The file is MP4 . You don't get it . The Video is playing , when you click the cardboard button , it crashed. Before you clicked the cardboard button , it is playing well.

**Comment by ChokWah** [comment]
I didn't use CocoaPod  to install CardboardSDK , I thought import the .h , .a , .Bundle in my project  with almost CocoaPod CardboardSDK. Is that wrong ? But it can play.

**Comment by sanjayc77** [comment]
Use -ObjC linker flag. The [GOOTypography robotoMediumWithSize:] method is part of a category on GOOTypography

**Comment by ChokWah** [comment]
@sanjayc77 Thanks a lot . It works.
