### ISSUE TITLE
Touch support?

### ISSUE THREAD

**Issue by seankovacs** [googlevr/gvr-ios-sdk#40]
I understand this is more a VR SDK meant for Cardboard and the likes, but it would be nice to offer touch support. My use case is for showing equirect panos on screen which can be spun/controlled via touch.

**Comment by nathanmartz** [comment]
The VR view classes both support touch controls in magic window mode, just
not in stereo.

-Nathan

**Comment by seankovacs** [comment]
I've tried kGVRPanoramaImageTypeMono (vs kGVRPanoramaImageTypeStereoOverUnder) and still no dice, though I don't think that is what you're referring to as 'magic window mode'. The object I'm using is from the example, GVRPanoramaView.
Perhaps I'm missing something? Thanks

**Comment by osalazarvirtualef** [comment]
i have the same problem, someone knows if we can activate touch and zoom in GVRPanoramaView?

**Comment by dav-cz** [comment]
Touch support (panning) was added in v0.9.0
https://developers.google.com/vr/ios/release-notes
