### ISSUE TITLE
GVRVideoView Full size

### ISSUE THREAD

**Issue by MFSZ007** [googlevr/gvr-ios-sdk#42]
Is there any way to call a view controller and the VideoView object inits in a full screen mode?
Thanks! (for iOS)

**Comment by ChokWah** [comment]
@MFSZ007 Try to add  videoview  subview in a view controller ,  videoView have to set constraint.

**Comment by sanjayc77** [comment]
GVRVideoView supplies its own fullscreen implementation, when the user clicks the fullscreen button. It was primarily designed to be embedded (and not fullscreen) next to other content.

But if you make it fullscreen, you will run into a bug. See this for a workaround: https://github.com/googlevr/gvr-ios-sdk/issues/28
