### ISSUE TITLE
GVRPanoramaView should not disappear and reappear when a new image is loaded.

### ISSUE THREAD

**Issue by GrahamLea** [googlevr/gvr-ios-sdk#44]
This is especially jarring when the view is in full-screen or cardboard mode and it reveals the view controller that loaded it momentarily.

A better solution would be to slowly fade the first image out to show the view's background colour and then fade the new image in once loaded.

Alternatively, if control over alpha is provided (see #43) the image could simply swap over once loaded and the app could take control of whether fading occurs or not, but the full screen view should still not disappear.

The first option seems better to me, this being a very high-level component.

**Comment by sanjayc77** [comment]
The fade-out to fade-in when a new image is loaded is by design. Also, the widgets were not designed to be used fullscreen. You will run into this issue: #28.

Put GVRPanoramaView in another view with an opaque background. This will fix the background reveal and gives you control over the alpha.

**Comment by GrahamLea** [comment]
> The fade-out to fade-in when a new image is loaded is by design.

Fade-out to fade-in would be great. What I see is the view instantly disappears when loadImage:ofType: is called, revealing what was behind it, then fades back in. Perhaps what I really want is just for the fade out to be fixed? 

> Also, the widgets were not designed to be used fullscreen.

I think you might have misunderstood me. The widgets have buttons on them to put them in "Fullscreen" or "Cardboard" modes. That's what I meant by fullscreen.

> Put GVRPanoramaView in another view with an opaque background. This will fix the background reveal and gives you control over the alpha.

Thanks. I've tried that, and it works when the view is displaying normally inside another view, but when it is put into fullscreen or cardboard mode, changing the alpha of the containing view does nothing.
