### ISSUE TITLE
Please give a concise version of GVR，I just use the GVRVideoView to play the video. 

### ISSUE THREAD

**Issue by lianguowu** [googlevr/gvr-ios-sdk#48]
Please give a concise version of GVR，I just use the GVRVideoView to play the video. if I integrated the GVRSDK in my app,the volume of APP is too large.thanks

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRVideoView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. Take a look at the updated VideoWidgetDemo sample app.
