### ISSUE TITLE
audio callback or strict timing in GVRCardboardAudioEngine?

### ISSUE THREAD

**Issue by colinsullivan** [googlevr/gvr-ios-sdk#49]
Hello!

Can you share any thoughts on adding an audio callback to the audio engine? This would allow for many interesting procedural audio techniques.  Unity has released a [Native Audio Plugin SDK](http://docs.unity3d.com/Manual/AudioMixerNativeAudioPlugin.html) which accomplishes this.

Also, what about scheduling of audio events within your existing framework?  For example, `playSound` could take an additional argument which is a timestamp in the future when this sound should start playing.  Check out the [Web Audio API](https://webaudio.github.io/web-audio-api/#widl-AudioBufferSourceNode-start-void-double-when-double-offset-double-duration) for an example of this.

These kinds of concepts are very useful for musical experiences which involve a strict sense of timing and allow for a wider variety of sounds then is reasonable to accomplish with purely sample-based playback.

**Comment by jkammerl** [comment]
The GVR SDK spatializer audio plugin is already based on Unity's Native Audio Plugin SDK:
https://github.com/googlevr/gvr-unity-sdk

I agree that adding functionality to schedule sounds is a useful feature to add. I created an internal ticket and we'll consider adding this feature in future updates.
