### ISSUE TITLE
GVRVideoView Forcing display mode

### ISSUE THREAD

**Issue by sudoloic** [googlevr/gvr-ios-sdk#50]
Hi ! 

It would be great to be able to force Fullscreen VR display mode for GVRVideoView. I know there is a way to enable the Cardboard Button which switch to Fullscreen VR display mode but there is no way to switch programmatically ?

Thanks

**Comment by nathanmartz** [comment]
This is not currently supported. Can you describe your use case in more detail?

**Comment by sudoloic** [comment]
I want my app to play a 360 video in a Google Cardboard only. For instance, the user taps a button and is directly shown the GVRVideoView in Fullscreen VR display mode. It would be cool to be able to bypass that intermediate step where the user needs to interact with the cardboard button.

**Comment by marcvanolmen** [comment]
I'm hoping this feature is available in the future too, in the mean time: 

I was able to  ***Hack*** (terrible I know...) this features by doing this: here some pseudo code in swift.

I'm sure I hide the VR View 

Then I do something like this, subview (1) is the Fullscreen button.

    ////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////
    override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
        dispatch_after_seconds(0.01) {
            if let button = self.videoView.subviews[1] as? UIButton {
                
                button.sendActionsForControlEvents(.TouchUpInside)
            }
        }
    }

Then when VR is loaded, I unhide the VRView: 

    /** Called when the content is successfully loaded. */
    func widgetView(widgetView: GVRWidgetView!, didLoadContent content: AnyObject!) {
        self.videoView.hidden = false
    }

dispatch_after_seconds: was required otherwise there was a crash.

**Comment by dav-cz** [comment]
Thanks for the feedback! 
We're adding an API to programmatically set the display mode in our upcoming release, stay tuned.

**Comment by tibewww** [comment]
Hi, Does the API have been added ? How can we call from a button the video starting in fullscreen ? and starting in Cardboard enabled  ??

Thanks guys :)

**Comment by sudoloic** [comment]
Yes, more infos here https://developers.google.com/vr/ios/reference/interface_g_v_r_video_view#af2a94ee82edd85ae22e8c3ffa70cd8e8

**Comment by tibewww** [comment]
Thanks,

I have now a button starting the video in full screen by:

 @IBAction func videoButton(_ sender: UIButton) {

    if let button = self.videoVRView.subviews[1] as? UIButton {
        button.sendActions(for: .touchUpInside)

    }
        
    }
      func widgetView(widgetView: GVRWidgetView!, didLoadContent content: AnyObject!) {
        self.videoVRView.isHidden = false;

     }

I'd like to have it starting in cardboard mode by default, do you know how is that possible ??

Thanks :) :)
