### ISSUE TITLE
VIDEOView  SDK affected by UINavigationController?

### ISSUE THREAD

**Issue by gityoung** [googlevr/gvr-ios-sdk#51]
![wechat_1465975012](https://cloud.githubusercontent.com/assets/9583031/16071147/55217b32-330c-11e6-883d-b17269dedc1c.jpeg)
 but  self.navigationBarHidden = YES;

**Comment by ChokWah** [comment]
Try to  add code " self.navigationBarHidden = YES; " in two method  : viewWillDisappear ,  and    viewWillDisappear

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRVideoView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. Take a look at the updated VideoWidgetDemo sample app.
