### ISSUE TITLE
kGVRPanoramaImageTypeStereoOverUnder MissAligned

### ISSUE THREAD

**Issue by pierrejeanferbos** [googlevr/gvr-ios-sdk#53]
Is there any know issues with the kGVRPanoramaImageTypeStereoOverUnder properties ?
Looking at the current the Panorama sample , the stereoscopic mode doesn't provide a clear display on Iphone 6 and Iphone 5. Looking at the web version , there is very clear difference in alignement and clarity between the two.

**Comment by dav-cz** [comment]
Could you elaborate on what you mean "by the stereoscopic mode doesn't provide a clear display" ?
Do you mean it's hard for your brain to fuse the left and right images? Or that the images look low resolution?

**Comment by arjessup** [comment]
Thanks for getting back to us on this! 

Short answer: 
Using the iOS sdk, it's hard to fuse the left/right images.  Using VR View this is not a problem.

More detail: 
We've found a very noticeable difference between the Google Cardboard experience on web in a VR View vs using the iOS sdk (both viewed on an iPhone).  Though this problem exists with the images we're using in our own projects, it can easily be seen with the image of Machu Picchu that is included in the iOS sdk demo (the "Panorama" project).

When we look at that image in a VR View in a website on an iPhone, using Cardboard looks great.  Using the exact same image in the Panorama project, viewed with Cardboard on the same iPhone, results in what looks like a misaligned image. It seems like the two images are *almost* where they need to be, but it feels "off" - as you suggested, it's hard to fuse the left and right images.  Using the iOS sdk, the general reaction we get from our testers is "holy headache!". Unfortunately, this experience is uncomfortable enough for users that we are not currently supporting Cardboard in our native apps.

As some basic (really basic) troubleshooting on our end, we've tried adjusting the position of the cardboard unit (though that isn't necessary in the web demo, the actual framing of the two images is slightly different for each platform), and passing around to various coworkers - no one is able to get the proper depth view using the iOS sdk. We've also tried different images (from the Panorama demo and our own), and are always able to reproduce the high quality in VR View, and low quality in iOS.

**Comment by tomtomtong** [comment]
I support your idea. I find that the problem becomes worse after updating to 0.85

**Comment by dav-cz** [comment]
Sorry to get back this late on this. I tried on an iPhone 6+ and an official Cardboard V2 and I didn't have problems converging. 

On what iPhone + cardboard headset models do you see this? 
Could you try on a different model and report back?

If you use a custom cardboard headset, did you pair it to your phone using the QR code scanning flow?

**Comment by smdol** [comment]
A couple of screenshots to compare will be very helpful!

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRPanoramaView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. Take a look at the updated Panorama sample app.
