### ISSUE TITLE
Is GVRSDK supportting IPv6?

### ISSUE THREAD

**Issue by Anchlate** [googlevr/gvr-ios-sdk#54]
My app was refused, the information is ‘As we discussed, please address this loading issue, and ensure that your app supports IPv6 networks, as IPv6 compatibility is required.’.  So, is GVRSDK supportting IPv6? Thanks！

**Comment by Anchlate** [comment]
- (void)setVideoUrlStr:(NSString *)videoUrlStr {
    
    _videoUrlStr = videoUrlStr;
    
    [self.videoView loadFromUrl:[NSURL URLWithString:videoUrlStr]];
}

This is my code and videoUrlStr is remote.

**Comment by sanjayc77** [comment]
We use NSURLConnection to stream/load the video from the URL and don't deal directly with IPv4/IPv6.
