### ISSUE TITLE
Could I jump to VR mode directly when I using GCSWidgetViewDelegate?

### ISSUE THREAD

**Issue by tomtomtong** [googlevr/gvr-ios-sdk#55]
Could I let user get into fullscreen VR directly in spite of clicking the VR button?
Thank for any reply.

**Comment by nathanmartz** [comment]
Sorry, but this is not currently supported. Can you describe your use case in more detail?

**Comment by tomtomtong** [comment]
I have created a panorama app and would like to let user enter VR mode once after they succeed to capture 360 panorama. 

If I use the stars VR example, then I need to make the sphere and texture by openGL. Are there any existing codes for me to make reference? Thank you.

**Comment by nathanmartz** [comment]
Thank you for the context. We have several other requests like this and are working on a sample similar to what you describe. In the mean time, there are plenty of references on the internet for how to render a textured sphere.
