### ISSUE TITLE
cann't find the GVRSDK 

### ISSUE THREAD

**Issue by 1320800521** [googlevr/gvr-ios-sdk#56]
After download, pod update, can not find GVRSDK, the problem is that, [!]Unable to find a specification for GVRSDKAnd when the search is tip: [!]Unable to find a pod with the name matching ` GVRSDK ', I want to ask, for the iOS SDK, can normal use, have the GVRSDK?

下载以后，pod update 时，找不到 GVRSDK，报的问题是这个，[!] Unable to find a specification for `GVRSDK`

而且在搜索的时候也提示：[!] Unable to find a pod with name matching `GVRSDK'  ,我想问问，对于这个iOS的sdk，都正常能用吗，都有这个GVRSDK吗？

![65c0da00-0fed-4c4e-afbf-5788e226569e](https://cloud.githubusercontent.com/assets/7401848/16335413/033fde4c-3a39-11e6-9a38-7d89552a3914.png)

**Comment by 1320800521** [comment]
Who can help me help me to have a look

**Comment by nathanmartz** [comment]
The full getting started is in our [online documentation](https://developers.google.com/vr/ios/get-started). If you are doing this from China, you may need to use a VPN to get the cocopod.

**Comment by ChokWah** [comment]
能正常使用，国内是用不了的，要翻墙。

**Comment by dav-cz** [comment]
Closing this. Reopen with more details if needed.

**Comment by 1320800521** [comment]
Can I use the VPN, over the wall, the normal use of the Google search or other software, but the check on the git the GVRSDK is empty, why

**Comment by summertian4** [comment]
@ChokWah even though I use VPN, I can not install it. It always time out.
