### ISSUE TITLE
not play automatically, reset device params

### ISSUE THREAD

**Issue by anks62** [googlevr/gvr-ios-sdk#57]
Hi,
->I have successfully integrated gvr ios sdk but when i launched my app, video is not played automatically (I have set _isPaused = NO). 
(I think i felt this problem after scanning VIEWER PROFILE GENERATOR Scan code. I do not know perfectly)
->When i seek to 30 or X seconds of video,video does not start play automatically. I forcefully touched screen to resume video  
->Can you tell me how can i reset updating device params (VIEWER PROFILE GENERATOR Scan code) for device and un configured my device to particular VIEWER PROFILE?
->how i can open app by default in cardboard viewer.

Thanks

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRVideoView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. Take a look at the updated VideoWidgetDemo sample app.
