### ISSUE TITLE
Remove "Tip" icon when no network available

### ISSUE THREAD

**Issue by arjessup** [googlevr/gvr-ios-sdk#58]
The reasoning given in the docs for requiring the tip icon makes sense in general. However, the apps that I develop are meant to work in environments with unreliable/nonexistent network access.  This often results in a poor user experience if one of our users taps on that icon - they are taken out of the app to Safari/their browser, only to be shown the 'no internet' warning.

If making the tip icon configurable is not an option, could it be tied to the users network access? This would provide the needed information to users when it is available to them, while preserving the user experience when it is not.

**Comment by nathanmartz** [comment]
Good idea. I've added this as a bug to our local tracker. We'll update here when it's live.

**Comment by seankovacs** [comment]
It's a hack and won't work if they change certain things, but this code hides it:

```
    // Hide the damn info button that drops you out of the app...
    for(UIView *view in self.videoView.subviews) {
        if([view isKindOfClass:NSClassFromString(@"QTMButton")]) {
            view.hidden = YES;
        }
    }
```

**Comment by Craimasjien** [comment]
The Android version of the SDK, however seemingly undocumented, has a method to hide this particular button whenever you please. It's part of the VrWidgetView. I'd rather have that too than let the network decide whether or not to show this option.

**Comment by ShaoShuaiiOS** [comment]
How to remove "Tip"  icon When Full Screen.

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRVideoView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod.

GVRKit does not display the "tip" button any more.
