### ISSUE TITLE
Cardboard View

### ISSUE THREAD

**Issue by TechM-Ankur** [googlevr/gvr-ios-sdk#59]
How to play video by default in cardboard Default Viewer Profile because i have to every time scan code to enter in cardboard view?

when i click on cardboard button and do not do anything just wait for few seconds after that video automatically plays in 2d cardboard view (Viewer Profile)

**Comment by nathanmartz** [comment]
You should only need to scan the QR code once per app install on iOS. You
can also skip this flow if you like.

**Comment by TechM-Ankur** [comment]
@nathanmartz thanks for your response

**Comment by jNoxx** [comment]
Hey @nathanmartz , any timeline on this? Would be awesome :)
