### ISSUE TITLE
"Terminated due to memory issue"

### ISSUE THREAD

**Issue by zrxq** [googlevr/gvr-ios-sdk#60]
I'm using a `GVRVideoView` from GVRSDK (0.8.1) to play remote video.
- When I play [this](https://m.cdnmk.net/site_media/media/OE.mp4) video, the app runs out of memory and gets terminated during the first ~10 seconds of playback. 
- [This one](http://yahooios2-i.akamaihd.net/hls/live/224964/iosstream/adinsert_test/master.m3u8) repeats 5-6 time before crashing with the same log output:

```
Message from debugger: Terminated due to memory issue
```

**Comment by zrxq** [comment]
In fact, the app ends up "Terminated due to memory issue" even when the video (the large one, 1st link) is stored locally.

**Comment by nathanmartz** [comment]
Yes. This is because it tries to load the entire file into memory. If you want a streaming solution, encode your content using HLS.

**Comment by zrxq** [comment]
@nathanmartz: Sorry, I failed to mention that the first address is supposed to be HLS. 

I just tried to stream this – http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8 – video, also HLS, and the result is exactly the same: eventually I get `Message from debugger: Terminated due to memory issue`. Could you please reopen the issue?

**Comment by zrxq** [comment]
Just to clarify, I use `[VRVideo loadFromUrl:[NSURL URLWithString:@"http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8"]]`. Android SDK has `Options.FORMAT_HLS` option, perhaps iOS needs something similar for HLS to work as intended?

**Comment by zrxq** [comment]
Wasn't able to reproduce the issue in simulator, but on a device (iPhone 6) it reproduces every time.

**Comment by zrxq** [comment]
Okay, turns out `GVRVideoView` isn't the culprit, `GVRPanoramaView` is (I use one for the preview). It seems to leak memory and eventually crash the app. Loading a large video in `GVRVideoView` just speeds things up, but is not the root cause. Removing `GVRPanoramaView` results in the app playing the video without any issues. Sorry for the misinformation.

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRVideoView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. Take a look at the updated VideoWidgetDemo sample app.
