### ISSUE TITLE
Feature Request: Allow touch tracking on GVRVideoView

### ISSUE THREAD

**Issue by SteveM10151** [googlevr/gvr-ios-sdk#61]
When playing a 360 video in a `GVRVideoView`, it would be great if we could enable touch tracking, so that the user may pan the video by touching and dragging the screen, as well as via the gyroscope.

The use case is similar to the [NYTVR](https://itunes.apple.com/us/app/nyt-vr/id1028562337?mt=8) app, where the user has the option of viewing a 360 video outside of cardboard mode.  Controlling the camera with touch controls in this scenario would allow the user to view a 360 video in confined spaces such as a train or bus, without having to wave their phone around to see all of the video content.

**Comment by nathanmartz** [comment]
Hi. Thanks for this report. It's on our tracker and high priority. There are a few workarounds already posted here if you look for them.

**Comment by steve-matthews** [comment]
Thanks for the quick response @nathanmartz!

**Comment by yalong5837** [comment]
I can't find workarounds.
How to do?

**Comment by tieyingli** [comment]
I got the same problem. Have anybody tried to pan the video by touching and dragging the screen?

In the official app Cardboard, you can drap and change the view.

**Comment by sajoneri** [comment]
Bump. Touching and dragging would really be awesome features!

Just as @yalong5837, I have not found any workaround.
It would be great if you could point us in the right direction @nathanmartz.

**Comment by songhongkang** [comment]
问题解决了吗？  Problem solved?

**Comment by sajoneri** [comment]
@songhongkang nope, problem not solved yet. I will switch to [https://github.com/Aralekk/simple360player_iOS](https://github.com/Aralekk/simple360player_iOS) since it has all features I need. It uses SpriteKit and Metal which causes [memory leaks](https://github.com/Aralekk/simple360player_iOS/issues/2), the current workaround is to [force OpenGL](https://github.com/Aralekk/simple360player_iOS/issues/11).

**Comment by dav-cz** [comment]
We're adding this feature in our next release which we plan to push in the next few days.

**Comment by sajoneri** [comment]
Great news @dav-cz!
We will keep Google VR in our app and hopefully the next release will solve our problems :)
Thank you for the feedback!

**Comment by dav-cz** [comment]
API is now available in v0.9.0
https://developers.google.com/vr/ios/release-notes

**Comment by richarddeanjohnson** [comment]
Sure, now there is a bool flag (BOOL) enableTouchTracking  but how do you expose it in Unity3D?
