### ISSUE TITLE
Feature Request: PanoramaView  Show Right

### ISSUE THREAD

**Issue by gityoung** [googlevr/gvr-ios-sdk#67]
When loaded a 360 image in a PanoramaView,the image Main content is Behind the camera ， maybe the camera put wrong?

**Comment by dav-cz** [comment]
Thanks for the report, in our upcoming release the camera will be looking at the image's center point.

**Comment by dav-cz** [comment]
Fixed with v0.9.0
https://developers.google.com/vr/ios/release-notes
