### ISSUE TITLE
hide Google Support iCON "i" and add UIButtons and get Click event of UIButtons in Panorama Image

### ISSUE THREAD

**Issue by anks62** [googlevr/gvr-ios-sdk#71]
Hi How i can hide google support icon"i" ?

how i can add Many UIButtons and get Click event of UIButtons in Panorama Image. so when user rotate her/his phone so one can see different UIButtons 

@nathanmartz or any other friends

**Comment by nathanmartz** [comment]
We do not plan to allow for users to customize the default UI for GVRView subclasses. We will remove the support icon when the user has no network connectivity.

Regarding adding other images, it's the same as any other View in iOS.
