### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by yalong5837** [googlevr/gvr-ios-sdk#72]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NBSSessionDelegate_GTMSessionFetcherSessionDelegateDispatcher setSession:]: unrecognized selector sent to instance 0x14899b980'

but other project is ok.. why?

**Comment by nathanmartz** [comment]
Hi. We'll need a much more complete stack trace to look into this issue.

**Comment by dav-cz** [comment]
Closing until we get more details. (like what samples or SDK API is used)

**Comment by xdf103** [comment]
Hi is NBSSessionDelegate_GTMSessionFetcherSessionDelegateDispatcher part of the GVR SDK? We are using the NDK GVR SDK, and we also encounter this error: 
[NBSSessionDelegate_GTMSessionFetcherSessionDelegateDispatcher setSession:]: unrecognized selector sent to instance 0x174006940
