### ISSUE TITLE
Have you Added support for HLS streams in GVRVideoView (0.8.5) for iOS?

### ISSUE THREAD

**Issue by lianguowu** [googlevr/gvr-ios-sdk#74]
you say YES ,but i have send the HLS streams to the FUC - (void)loadFromUrl:(NSURL*)videoUrl ofType:(GVRVideoType)videoType. i have not gotten the response.

**Comment by lianguowu** [comment]
Do you have the Release Notes of it ?

**Comment by lianguowu** [comment]
By the way， my HLS stream is the Type of m3u8

**Comment by jayspringfield** [comment]
same question.  is this supported?  the loadFromUrl header we have doesn't include "ofType" and GVRVideoType doesn't exist in the online docs (https://developers.google.com/vr/ios/reference/)

<img width="693" alt="screen shot 2016-07-19 at 4 38 34 pm" src="https://cloud.githubusercontent.com/assets/8238518/16966040/d190f934-4dd0-11e6-8881-4a5049c814ce.png">

**Comment by marcvanolmen** [comment]
I tried this and it seems to work fine.

**Comment by dav-cz** [comment]
HLS files are supported, we use a regular AVPlayer under the hood. So if your file plays with AVPlayer, it should normally play with GVRVideoView.

**Comment by dav-cz** [comment]
Closing this. Please re-open with more details, including whether your original video works with AVPlayer.
