### ISSUE TITLE
Video pausing issue

### ISSUE THREAD

**Issue by LyndseyS** [googlevr/gvr-ios-sdk#76]
When you run code to pause a video either (1) Immediately after the video has loaded or (2) immediately after switching between display modes, it doesn’t always pause.

**Comment by nathanmartz** [comment]
Thanks for posting this. We've got it in our tracker.

**Comment by mstana** [comment]
hello, 

is there any progress with this issue? Its kind of frustrating bug for me too. 

thanks for answer.

**Comment by nathanmartz** [comment]
It looks like the issue was specific to playing videos when the phone was already in landscape mode. We have a fix for that issue and it'll be available in our next release.

**Comment by sanjayc77** [comment]
This is a bug and with be fixed in the next release (post 1.0.1). You can try to call the pause method immediately after the video has loaded in a dispatch_async:

dispatch_async(dispatch_get_main_queue(), ^{
  [_videoView pause];
});

**Comment by sanjayc77** [comment]
Please try the 1.10.1 update.
