### ISSUE TITLE
GVRVideoView Load  m3u8 Error!

### ISSUE THREAD

**Issue by mishellfire** [googlevr/gvr-ios-sdk#78]
There's  a  m3u8 link,i can play it on safari correctly,but when i put the url in code like this:
NSString *videoPath = @"http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8";
[_videoView loadFromUrl:[[NSURL alloc] initFileURLWithPath:videoPath]];
video can't display and when UI Loaded,it XCode reports the error:  2016-07-17 21:25:42.500 VideoWidgetDemo[38631:2358703] Failed to load video: The operation could not be completed
I have tested  several m3u8 link that can play correctly on safari but  they can't dispaly on GVRVideoView,did i miss something in code?Thx  everyone.

**Comment by q273255702** [comment]
the same as you...

**Comment by dav-cz** [comment]
We use AVPlayer under the hood. Does your video work with AVPlayer?

**Comment by sanjayc77** [comment]
The supported video profiles and codec is dependent upon the iOS device.

http://stackoverflow.com/questions/1535836/video-file-formats-supported-in-iphone
