### ISSUE TITLE
bitcode is not enabled

### ISSUE THREAD

**Issue by Nandiin** [googlevr/gvr-ios-sdk#8]
Is there any plan to release a bitcode enabled version of library? The one fetched by cocoapod doesn't contain bitcode

**Comment by biscuitehh** [comment]
+1, Bitcode would be awesome!

**Comment by iosdevzone** [comment]
+1 on bitcode

**Comment by alxndalexeev** [comment]
+1

**Comment by yalong5837** [comment]
When to support bitcode？0.0

**Comment by nathanmartz** [comment]
This is a popular request, so I've added it to our internal tracker.

**Comment by LukeDurrant** [comment]
Any update on this?

**Comment by DanMorganiOS** [comment]
@nathanmartz also curious about an update on this?

**Comment by nathanmartz** [comment]
No update yet. We'll post here when there is.

**Comment by joridor** [comment]
+1

**Comment by karzn** [comment]
+1

**Comment by cprovatas** [comment]
+1

**Comment by zrxq** [comment]
+1

**Comment by Caspert** [comment]
Is there some update about the bitcode version of this pod? Is this to be expected soon?

**Comment by apan06** [comment]
+1

**Comment by ecristerna** [comment]
+1

**Comment by guitarrapc** [comment]
+1

**Comment by sanjayc77** [comment]
Bitcode has been enabled for a while. Feel free to re-open if this issue still persists.
