### ISSUE TITLE
GVRVideoView播放m3u8问题

### ISSUE THREAD

**Issue by q273255702** [googlevr/gvr-ios-sdk#81]
测试GVRVideoView播放hls的视频，无法播放，播放hls 需要怎么样的设置呢？是否支持http://xxx.xx.xx.xx/xxx.mp4的播放方式呢？

**Comment by nathanmartz** [comment]
I'm sorry but we can only answer questions posted in English. Can you update your title and description?

**Comment by q273255702** [comment]
GVRVideoView can support HTTP? Like http://xxx.xxx.xxx.xx/test.mp4?

**Comment by nathanmartz** [comment]
Yes. No problem at all.
