### ISSUE TITLE
CardboardSDK.bundle doesn't support Dynamic Framework

### ISSUE THREAD

**Issue by marcvanolmen** [googlevr/gvr-ios-sdk#82]
I was able to build a dynamic Framework from the GVRSDK, but I had to add one bundle to my main app resources that was the: CardBoardSDK.bundle. 

My app can't use the -ObjC linker flag because all my 3rd party dependencies are compiled as dynamic Frameworks. (Carthage)

**Comment by RikHeijdens** [comment]
https://github.com/googlevr/gvr-ios-sdk/issues/62

**Comment by sanjayc77** [comment]
There is no plan to support this future. Closing this issue for now.
