### ISSUE TITLE
Forwarding Feature 

### ISSUE THREAD

**Issue by anks62** [googlevr/gvr-ios-sdk#83]
@nathanmartz 
hi how are you?
I want to know that google provide any feature for forwarding video, I think you provided in Android in videoWidgetDemo
Actually I have already made Forwarding video by the use of slider controller and use your method seekTo (_videoView seekTo:45) to forward video

but i want to know any this type of feature provide by you in video widget for iOS

@nathanmartz 

Thanks
Have a nice day

**Comment by nathanmartz** [comment]
Hi. In time we will align the iOS API with the Android one, but we're
focused n fixing some more critical bugs right now.

**Comment by dav-cz** [comment]
As you wrote the GVRWidgetView API lets you do this programmatically with the ["seekTo" function](https://developers.google.com/vr/ios/reference/interface_g_v_r_video_view.html#adecfd8604417df8f46ee31f5f7144b92)

The only difference with Android is that the sample app doesn't have a slider, but that's not a shortcoming of the API itself, so closing this.
