### ISSUE TITLE
GVRPanoramaView: Fullscreen button does not show if the Cardboard button is enabled in config

### ISSUE THREAD

**Issue by vijaytholpadi** [googlevr/gvr-ios-sdk#84]
Code for GVRPanoramaView initialization:

```
    self.panoramaView = [[GVRPanoramaView alloc] init];
    self.panoramaView = self;
```

---

with

```
    self.panoramaView.enableCardboardButton = YES;
    self.panoramaView.enableFullscreenButton = YES;
```

The above code shows only VR/Cardboard button

---

with only

```
    self.panoramaView.enableFullscreenButton = YES;
```

The above code shows FullScreen button

---

How do I get both FullScreen as well as VR/Cardboard button? This is happening in the sample app too.

**Comment by nathanmartz** [comment]
This is a bug in 0.8.5. It'll be fixed in our next release a couple weeks from now.

**Comment by vijaytholpadi** [comment]
Great! Looking forward to it. 👍

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRPanoramaView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. Take a look at the updated Panorama sample app.
