### ISSUE TITLE
VideoWidgetDemo[1130:552274] Failed to load video: The operation could not be complete

### ISSUE THREAD

**Issue by q273255702** [googlevr/gvr-ios-sdk#86]
when url is such as http://192.168.0.109/congo.mp4,xcode log : VideoWidgetDemo[1130:552274] Failed to load video: The operation could not be complete

can you tell me why?

code:
  // Load the sample 360 video, which is of type stereo-over-under.
//  NSString *videoPath = [[NSBundle mainBundle] pathForResource:@"t" ofType:@"mp4"];
    NSString *videoPath = @"http://192.168.0.109/congo.mp4";
  [_videoView loadFromUrl:[[NSURL alloc] initWithString:videoPath]];

**Comment by nathanmartz** [comment]
Does that URL work if you put it into a web browser? My default guess is
that the URL doesn't actually work.

**Comment by dav-cz** [comment]
Closing this until more details are provided.
