### ISSUE TITLE
Feature Request: GVRVideoView URL to work with youtube videos

### ISSUE THREAD

**Issue by ws6ramair** [googlevr/gvr-ios-sdk#87]
Hello,

First off thank you for maintaining this awesome library.  Super excited to be using it.

I was wondering if there were any plans to have GVRVideoView support videos from a youtube url.

For example: 

loadFromUrl("https://www.youtube.com/watch?v=J---aiyznGQ")

I am trying to reproduce similar functionally to how iOS Youtube app provides stereoscopic viewing of any youtube video.

I'd be happy to provide more info or even help contribute.

Thanks,
-Jason

**Comment by nathanmartz** [comment]
Hi, Jason. We don't currently plan to support YT as a backend for VrVideoView.
