### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by ghenzhimura** [googlevr/gvr-ios-sdk#88]
i got this error when i'm trying to build the project. any solution?

```
Undefined symbols for architecture x86_64:
 "_OBJC_CLASS_$_GVRPanoramaView", referenced from:
      objc-class-ref in PanoramaViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dgoodine** [comment]
The SDK doesn't support running against the simulator (which it should).  So you can only build a project that includes it for the device.

**Comment by ghenzhimura** [comment]
@dgoodine its working on simulator if i run from the sample code GVR. but when i create new xcode project and added it that gave me that error message. is there any configuration that i missed?

**Comment by mboeddeker** [comment]
same Problem!

**Comment by sanjayc77** [comment]
Thanks. Added to internal bug tracker.

**Comment by sanjayc77** [comment]
Seems to me you are reusing the PanoramaViewController from the sample, but not adding the Cocoapod 'GVRSDK' to your new project. PanoramaViewController is from the sample app, but GVRPanoramaView comes from the Cocoapod.

Re-open if you think thats not the case.
