### ISSUE TITLE
EXC_BAD_ACCESS on GCRRenderUtil EAGLContextWithPreferredAPI:]

### ISSUE THREAD

**Issue by LukeDurrant** [googlevr/gvr-ios-sdk#90]
GVR SDK for iOS v0.8.5
# OS Version: 8.1.0 (12B411)
# Device: iPhone 5c
# RAM Free: 55.2%
# Disk Free: 71.4%
#0. Crashed: com.apple.main-thread

0  libGPUSupportMercury.dylib     0x31eb18fe gpus_ReturnNotPermittedKillClient
1  libGPUSupportMercury.dylib     0x31eb23cb gpusSubmitDataBuffers
2  libGPUSupportMercury.dylib     0x31eb2249 gldCreateContext
3  GLEngine                       0x2dab893b gliCreateContextWithShared
4  OpenGLES                       0x2db94ab3 -[EAGLContext initWithAPI:properties:] + 406
5  OpenGLES                       0x2db9486f -[EAGLContext initWithAPI:sharedWithCompute:] + 142
6  APPNAME                         0x8bd85f +[GVRRenderUtils EAGLContextWithPreferredAPI:] + 9087071
7  APPNAME                         0x8c2fa5 -[GVRWidgetView initWidgetViewWithFrame:] + 9109413
8  APPNAME                         0x8c35d9 -[GVRWidgetView initWithFrame:] + 9111001
9  APPNAME                         0x8b6f53 -[GVRPanoramaView initWithFrame:] + 9060179
10 UIKit                          0x2e691169 -[UIView init] + 44
11 APPNAME                         0x7b6a30 APPNAMEGalleryCarouselCell.init(frame : CGRect) -> APPNAMEGalleryCarouselCell (APPNAMEGalleryCarouselCell.swift:25)
12 APPNAME                         0x7b6de0 @objc APPNAMEGalleryCarouselCell.init(frame : CGRect) -> APPNAMEGalleryCarouselCell (APPNAMEGalleryCarouselCell.swift)
13 UIKit                          0x2ec751d5 -[UICollectionView _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:] + 1128
14 UIKit                          0x2e6d0f01 -[UICollectionView dequeueReusableCellWithReuseIdentifier:forIndexPath:] + 144

**Comment by LukeDurrant** [comment]
Replaced APPNAME with the actual APPNAME

**Comment by nathanmartz** [comment]
I'm not sure what's happening here, but are you loading an image or a
video? What are the dimensions of the media?

**Comment by LukeDurrant** [comment]
Loading an image. Looks like the open GL context is still being written whilst the app is in background. It's in a UICollectionView
I'll great a sample app to reproduce the issue.

**Comment by marcvanolmen** [comment]
I had this issue today, that I think is related:

It was just in the moment that I was going fullscreen and then app was going in the background, when I came back to my app. I got this error in Xcode:

libGPUSupportMercury.dylib`gpus_ReturnNotPermittedKillClient:

**Comment by sanjayc77** [comment]
Thanks. Added to our internal bug tracker.

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRPanoramaView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. Take a look at the updated Panorama sample app.
