### ISSUE TITLE
SDK Files Missing?

### ISSUE THREAD

**Issue by MattFedo** [googlevr/gvr-ios-sdk#91]
I cloned the lib but I only get the demo projects and none of the SDK files.  Every project is missing a GVRCardboardView, or GVRPanoramaView or others.

Is something misaligned?

**Comment by marcvanolmen** [comment]
I'm guessing you didn't run Pod install the iOS 3rd party package manager that downloads and installs the SDK. I would recommend reading the docs: https://developers.google.com/vr/ios/get-started

**Comment by MattFedo** [comment]
Cool cool, thanks.  I read that, but I wasnt sure where the SDK was coming from.  Thanks!
