### ISSUE TITLE
Failed to connect to www.gstatic.com port 443: Operation timed out

### ISSUE THREAD

**Issue by songhongkang** [googlevr/gvr-ios-sdk#93]
i'm Chinese , PODS instll the GVRSDK is failure，                                                                       platform :ios, '8.0'
#use_frameworks!个别需要用到它，比如reactiveCocoa
def pods
pod 'GVRSDK'
end
target 'TreasureHunt' do
pods
end

**Comment by nathanmartz** [comment]
You may need to use a VPN when performing this step.
