### ISSUE TITLE
Heavy memory leaks with 0.8.5 when you use the GVRVideoView

### ISSUE THREAD

**Issue by marcvanolmen** [googlevr/gvr-ios-sdk#95]
HI,

Build a sample app based on the Google VideoWidgetDemo, to demonstrate the issue:

We added an extra view so that you can go forward and backwards in the app, to be able to close the views. I verified all view controllers get deallocated etc. 

But after clicking Launch  + dismiss about 11 x on iPad Mini with 512GBytes the memory warnings come up and app crashes because runs out of memory.

I used a 512MBytes iPad Mini running iOS 9.2 because it runs quicker out of memory then a 1 GBytes iPhone.

Here is the code.

https://github.com/marcvanolmen/GVRSDK-VideoWidgetDemo

In case you have a beta version of the SDK that fixes this I'm willing to test this quickly,

best

Marc

**Comment by nathanmartz** [comment]
Hi, Marc. Thanks for the bug report. We're looking into this now. Hopefully we have more info soon.

**Comment by dav-cz** [comment]
Marc could you test your project again with v0.9.0 and report back?

**Comment by marcvanolmen** [comment]
Hi 

Thanks for looking into this,
I just upgraded to v0.9.0 SDK, and memory issue is still there.
I used my iPhone 6.0 and after 18 x Launch and Dismiss the app crashes 
This was reported in Xcode:

Message from debugger: Terminated due to memory issue

**Comment by marcvanolmen** [comment]
Just a quick update, could also be that this is an issue with texture memory that is running is out.

**Comment by sanjayc77** [comment]
It was the texture memory running out.

Please try the latest GVRSDK 1.0.1.

https://github.com/CocoaPods/Specs/blob/master/Specs/GVRSDK/1.0.1/GVRSDK.podspec.json
