### ISSUE TITLE
Can't create correct .xcodeproj with VideoWidgetDemo

### ISSUE THREAD

**Issue by arumani** [googlevr/gvr-ios-sdk#97]
SDK Version 0.9.0

1. `$ cd VideoWidgetDemo`
2. `$ pod update`
3. result in an warning.

> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `VideoWidgetDemo` to `Pods/Target Support Files/Pods-VideoWidgetDemo/Pods-VideoWidgetDemo.debug.xcconfig` or include the `Pods/Target Support Files/Pods-VideoWidgetDemo/Pods-VideoWidgetDemo.debug.xcconfig` in your build configuration.
> 
> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `VideoWidgetDemo` to `Pods/Target Support Files/Pods-VideoWidgetDemo/Pods-VideoWidgetDemo.release.xcconfig` or include the `Pods/Target Support Files/Pods-VideoWidgetDemo/Pods-VideoWidgetDemo.release.xcconfig` in your build configuration.

My workaround is modifying VideoWidgetDemo.xcodeproj/project.pbxproj after `pod update`.

```
$ sed -i -e 's/Target Support Files\/Pods\/Pods./Target Support Files\/Pods-VideoWidgetDemo\/Pods-VideoWidgetDemo./g' VideoWidgetDemo.xcodeproj/project.pbxproj`

$ diff original/project.pbxproj modified/project.pbxproj
737c737
< 			<string>Pods/Target Support Files/Pods/Pods.release.xcconfig</string>
---
> 			<string>Pods/Target Support Files/Pods-VideoWidgetDemo/Pods-VideoWidgetDemo.release.xcconfig</string>
765c765
< 			<string>Pods/Target Support Files/Pods/Pods.debug.xcconfig</string>
---
> 			<string>Pods/Target Support Files/Pods-VideoWidgetDemo/Pods-VideoWidgetDemo.debug.xcconfig</string>
```

**Comment by sanjayc77** [comment]
Thanks for catching that. We added this to our internal bug tracker.
