### ISSUE TITLE
Make GVRHeadRotation available for GVRcardboardView/Delegate

### ISSUE THREAD

**Issue by Izhido** [googlevr/gvr-ios-sdk#98]
Having the yaw and pitch angles already calculated for the Video viewer is a welcome addition. I would like to request exposing these values for the GVRCardboardView and / or Delegate classes as well; games are bound to benefit for having those already correctly calculated, instead of depending on a third party lib or manual inplementation that might not know all the intricacies of the VR tech in use.

**Comment by nathanmartz** [comment]
If you are using the lower level view classes, the left/right eye rendering callbacks already have the necessary transforms passed into them.
