### ISSUE TITLE
GVRCardboardView for Metal

### ISSUE THREAD

**Issue by Izhido** [googlevr/gvr-ios-sdk#99]
Lately, Apple has been pushing aggresively for developers to use Metal for 3D rendering, and I wholeheartedly agree Metal is a nice improvement over OpenGL. I would like to request adding a Metal version of the GVRCardboardView and related classes, alongside the existing OpenGL version.

**Comment by nathanmartz** [comment]
Although Metal can really improve the performance of apps that do a lot of complex rendering (like games), the benefits negligible for something as simple as VR View. As such, we have no plans to add support for Metal anytime in the foreseeable future.
